### ISSUE TITLE
Survey123 Connect on Win8 / Office 2013 Opens new surveys in "Read Only"

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#1]
You have to go to the file properties and turn off read only so you can actually save the excel form.

**Comment by HannahFerrier** [comment]
This issue has been resolved in Survey123 Connect (build version 0.0.20). 

When creating a new survey in Survey123 Connect on Linux, Mac or Windows, the resulting .xlsx file is read/write.

**Comment by sirws** [comment]
Thanks, the latest build seems to work.

**Comment by survey123** [comment]
Fixed. Closing.
