### ISSUE TITLE
Force saving as a draft if a 'Required' question is not answered.

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#10]
If a question is flagged as 'required' = yes and no answer is provided,  the Survey123 App should not let the user flag the entry as 'Completed'. The 'Completed' button should only be enabled when all 'Required' questions have been answered.

**Comment by survey123** [comment]
Thanks.
We will look into this.  Surveys should not be saved as completed unless all required questions have been answered.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. 
@Cintruenigo
