### ISSUE TITLE
Field with an associated list is always created as text field even when all the list's values are integer

### ISSUE THREAD

**Issue by cdarti** [Esri/Survey123Community#100]
Field should respect the types from the associated list. Otherwise this may result in conflicts with the a database schema that requires an integer field.

**Comment by survey123** [comment]
Thank you for your feedback. We are aware of this issue and are planning on including a fix in a future version of aurvey123.

**Comment by mindzia** [comment]
It would be useful when Survey123 is used with operations Dasboard, when some dashboard widgets are expecting integer field types...

**Comment by survey123** [comment]
Fixed Survey123 Connect Build 1.0.143

A new column called *bind::esri:fieldType* can be added in the choices worksheet to specify the specific esri field type you want for your question.
This new column has been added in the blank template for your convenience. The blank template also includes a drop-down with the typical values.

![untitled](https://cloud.githubusercontent.com/assets/10968332/9001632/b0d89e74-370e-11e5-9dda-448bbcef620a.png)
