### ISSUE TITLE
Default value from list is not used.

### ISSUE THREAD

**Issue by cdarti** [Esri/Survey123Community#101]
When a field has an associated choice list, if a default value from the list is set, this default is not used in the form.

**Comment by survey123** [comment]
I am unable to reproduce this issue. When I set a default value/s for _select_one_ or _select_multiple_ fields, the default value/s is always displayed on the form.

If you are not already using the latest version of Survey123, I would encourage you to try again after installing the updated version.

If you are using the latest version,could I ask for an example of your data to try and reproduce the issue? A copy of the offending code from the spreadsheet would be sufficient.

**Comment by survey123** [comment]
Christine: make sure your default is set to a value from the 'name' column, rather than a value from the 'label' column of your choice list. Values are case sensitive. Also be careful with spaces at the end.
