### ISSUE TITLE
Signin information not persisted in Survey123Connect

### ISSUE THREAD

**Issue by cdarti** [Esri/Survey123Community#102]
When checking Remember me in the Sign in to ArcGIS Online login window, the next time I tried to sign in, my username is populated but I need to reenter my password.

**Comment by survey123** [comment]
This is as designed. The **Remember Me** check box was only designed to remember your username. We do not save a copy your ArcGIS Online password.  

If you would like us to store your ArcGIS Online password in the Survey123 app, please let us know.

**Comment by survey123** [comment]
Update: Based on feedback (not registered in this forum), we are looking at implementing the following design in an upcoming update:

* If the Remember Me option has been checked in the Signin Dialog, the Survey123 app will not prompt for credentials again until the user explicitly signs out, or the user/password combination is no longer valid.
* By default, all surveys will show the 'Remember Me' option. However, from Survey123 Connect the Survey author will be able to disable this feature.
