### ISSUE TITLE
Can't republish surveys

### ISSUE THREAD

**Issue by cmartin616** [Esri/Survey123Community#104]
We haven't had any success republishing surveys.  Even making a minor change like a typo or capitalization correction results in the survey needing to be deleted from AGOL/Portal and republished.  All previous surveys are lost when this happens.

**Comment by survey123** [comment]
Please check that you are using the latest version of Survey123 Connect (1.0.89). 

When you have previously published a survey, you should be able to update the form package to make changes to the survey form (not the underlying data, the feature service is created during the first upload and will need to be recreated if you want to add fields or change field types and names). 

You should be presented with the following dialog when attempting to upload a survey that has already been uploaded before using the same ArcGIS Online account:
 
![form package](https://cloud.githubusercontent.com/assets/10968332/7718863/fed7c926-fef9-11e4-9b28-df5e1fc5fcd4.PNG)
