### ISSUE TITLE
Publish Survey 123 Error - Create Service Exception "null"

### ISSUE THREAD

**Issue by travelkev** [Esri/Survey123Community#105]
Has anyone else experienced an issue when publishing a new survey from Survey123 Connect that it fails with message "create service exception 'null'" ?  Screenshot attached...

![serviceexceptionnull](https://cloud.githubusercontent.com/assets/12529368/7726270/0db0ce3c-ff01-11e4-938d-e56bd3ba1ca7.png)

I am publishing a pretty standard form.

After this initial failure, if you attempt to republish you then get an error related to folders that exist already: -

![foldererror](https://cloud.githubusercontent.com/assets/12529368/7726328/7eb4bc38-ff01-11e4-90cc-40508e4dba82.JPG)

**Comment by travelkev** [comment]
After further experimentation I think this is a permission issue, perhaps linked to the fact that my account is a "trial" account using a 60 day license.  When I tried from a full account I had no problems to publish my surveys.

**Comment by survey123** [comment]
Thanks for reporting this. 
We have logged this as an issue in our backlog. We will provide a more descriptive error.
