### ISSUE TITLE
Unsure how to update S123 Connect to the latest version on OS X

### ISSUE THREAD

**Issue by djibo** [Esri/Survey123Community#108]
I haven't been able to figure out how to update S123 Connect to the latest version. I tried using the maintenancetool.app, but got this error message: "at least one valid and enabled repository required for this action to succeed." 

Any ideas on how to handle this without losing the surveys I've already created?

**Comment by survey123** [comment]
On a the desktop, you will need to use the maintenance tool to uninstall Survey123 Connect and then install the latest version. 

Don't worry, the uninstaller does not remove your project folder (~\users\ArcGIS\My Survey Designs), so when you fire up the latest version, all of your projects will still be there.

**Comment by djibo** [comment]
Great, thank you so much for the advice! I searched around on the GitHub
forum, but couldn't find the answer anywhere.

Cheers,

Devon
