### ISSUE TITLE
XLS template with XLSForm validation rules

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#11]
I have created an XLS template that includes a few validation rules.  While you will still be on your own, it helps a bit.

[Download the XLS template](https://esri.box.com/shared/static/22n5t1fhi8sq4l2vxs1c09462gn7x8ai.xlsx)

Here is what it does:
* The type, name and label columns are fixed. If you scroll to the right, you will always see these three columns. That is helpful because otherwise it is hard to know against which question you are working.
* The type column has a dropdown list showing only values currently supported by Survey123. You can still put whatever you want, but the list is there in case you want to use it.
* The name column has a couple of validation rules:
    * If you type a space in between characters, it will highlight the cell with an error. Database names do not accept spaces and it is a classic for people to add spaces in this column.
    * If you add two identical values in this column, both cells will be highlighted in red. You cannot have two fields with the same field name, so why would not you want this rule!

I am not an Excel guru. I am sure much more can be done. I leave this out there in case someone wants to try. It may be useful.

**Comment by Cintruenigo** [comment]
@sirws

**Comment by survey123** [comment]
Thanks!
We are now using this XLS template in Survey123Connect so everyone can take advantage of it. When you create a new Survey, pick the 'blank' template.
Lets keep evolving this template.

**Comment by survey123** [comment]
Closing issue since template is already part of the core Survey123 Connect.
