### ISSUE TITLE
The hosted feature services do not honor required column setting

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#110]
When a survey is created with required fields the underlying feature service nullable parameter for the attributes does not respect the required field setting in the survey. Please see attached screen capture of the feature service and the survey form. The Survey Date, Enumerator Name, and Site ID are all required fields but the feature service is nullable property is set to true.
![required field property](https://cloud.githubusercontent.com/assets/4204178/7949832/629f6660-0960-11e5-9c91-6431de9a9caf.png)

**Comment by survey123** [comment]
This is by design. The concept of a _required field_ is only present in the form, not in the underlying feature service. 
Building a form with a combination of required fields and relevant conditions is more complicated than the structure of the feature service allows us to be. This is why we are keeping the complex business logic in the form where we have much more flexibility, rather than the feature service itself.

**Comment by deepti10** [comment]
The required fields in the survey should be sent as "nullable: false" as the users can easily go and edit the feature service then in ArcGIS Online or portal and add records. If the required fields are not set as nullable false errors can be introduced in data and corrupt it. Else these services should not allow editing via ArcGIS Online or Portal. Additionally the integrity of the data is not maintained.

**Comment by survey123** [comment]
Hi Deepti.  Unfortunately we will not be able to satisfy your requirement until all ArcGIS apps behave consistently with Required and Relevant XLSForm statements.

For now, here is what you can do:
- If you would like to enforce the IsRequired rule at the database level, ensure that your Survey123 forms do not combine IsRequired and Relevant statements.  Then, go into your feature service and flag your fields as NotNullable.  You will need to do this manually.
-If you would like to take advantage of the smarts of XLSForm, always be aware that the only app that at the moment will support XLSForm logic is Survey123. The rest of apps in ArcGIS will ignore Relevants, Constrains, Groups etc

As described in our previous comment, it is not possible for us to enforce Required fields at the database level while supporting the Relevant/Required logic in XLSForms.

It is also not possible for us to flag a Feature service so it can only be editable from Survey123.  A feature service.. is a feature service.
