### ISSUE TITLE
Off Line basemaps

### ISSUE THREAD

**Issue by DavidATait** [Esri/Survey123Community#114]
Is it currently possible to download a (partial) basemap for off line use?  Like one would do in Collector App.  If not currently then is this planned?

**Comment by yrebois** [comment]
Affirmative, this will be  a great added value !

**Comment by survey123** [comment]
Hi. Use of basemaps offline is planned:
- You will be able to dynamically download your tiles directly from the tiled service
- Or alternatively define a tpk file to be downloaded with your survey
- Or point to existing basemaps that you may already have locally in the device

Thanks for your commnents.

**Comment by jlarios23** [comment]
+1

Taking basemaps offline would be needed by a company I'm working with that wants a more form-based app (vs. Collector) for doing utility construction inspections in the field!

**Comment by MrPaulg** [comment]
Super app, but the offline content is a must have, currently collector does what we need in the field but the forms based approach for simple point features approach is just brilliant - only thing missing is the offline access to a .tpk and if this is being planned would it be possible to use 'external memory' location as in sd card for access. Will there be Polygon and Line geometry capture in the future ?

**Comment by survey123** [comment]
Thanks for your feedback. 
We will consider the 'external memory' option you highlight.

For collecting polygons and lines, the XLSForm spec has two question types: geoshape and geotrace. As per the description in the [specification](http://survey123.esri.com/resources/XLSFormSupport/#question%20types) they are designed to help you capture polygons and lines from a series of GPS readings.  Our intent is to implement the XLSForm spec fully but we will want to prioritize what comes first.  It will be helpful if you add your enhancement request separately as a new issue so we can see what others think about it.  In that enhancement request you can also articulate if the [existing definition of geoshape and geotrace](http://survey123.esri.com/resources/XLSFormSupport/#question%20types) will serve you or if you are looking for something different.

**Comment by ljaupi** [comment]
offline content is a must have feature. it would be good to have not only raster base maps (i.e. imagery), but also vector data such as points, lines and polygons that are pre-loaded and then taken offline.

**Comment by DavidATait** [comment]
Hi, is December 1st still a potential release for offline basemaps?
I now have several customers who love the flexibility and ease of use (great app!!! well done), but must have offline basemaps for work in areas with limited or no connectivity.

**Comment by survey123** [comment]
Hi David. Tentatively yes. Tentatively.

**Comment by rlawrence58** [comment]
Please, please, please!!!  We have some great uses for Survey 123 but not all of them will ensure connection...we have remote surveyors out collecting lots of data in unconnected modes.  Offline basemaps is a MUST for about a hundred of these folks.  This is an IMMEDIATE need for us here at Arizona Game and Fish.  Contact me if you have questions.  Richard:  480.589.3642

**Comment by katyhaddock** [comment]
Offline basemaps would be a very beneficial to many users. It would be great if it was up and running by the December 1st. Thank you!

**Comment by rlawrence58** [comment]
Katy is right on...I think we could use this almost immediately in a remote testing scenario I have in mind, which we would likely roll out to all our regions by early next year...if the offline basemaps are there.  We have other uses that we likely will pursue immediately for those who don't require offline capability.

**Comment by DavidATait** [comment]
Thanks survey123, I have two large government agencies who want to deploy this to several hundred field data operatives but MUST have offline maps, these two projects are likely to open up many more in the UK

**Comment by jakc** [comment]
We have a large agency in Western Australia wishing to deploy this, but will require offline basemap access.  Ideally not just .TPK, but also ability to specify an AOI from the Esri Topo basemap for exporting alongside survey.

**Comment by mderink** [comment]
Offline basemaps is also a mayor requirement in the Netherlands. We have an inspection agency and they have to inspections in the field and in building (basements). Another large customer (Rijkswaterstaat) is using mobile devices on their vessels near the Dutch coast. They also don't have a sufficient mobile internet coverage, but it's crucial they have the information in offline mode. This functionality can help us positioning 123Survey.

**Comment by ctoledo-img-com-br** [comment]
+1

**Comment by survey123** [comment]
#70

**Comment by travisbutcher** [comment]
:+1:  (just adding my voice to the choir)

**Comment by scoxisda** [comment]
+1

**Comment by survey123** [comment]
Thanks to all for your feedback.
A first implementation for offline basemap support is available since the Jan 6, 2016 update of Survey123.
More details here: https://geonet.esri.com/groups/survey123/blog/2016/01/06/prepare-basemaps-for-offline-use
Closing this issue.

**Comment by DavidATait** [comment]
Hi

 

Thanks for letting me know, I will test today.

Thanks for all the work that is going into making this a great product.

 

Best regards

 

David
