### ISSUE TITLE
Basemap still appears offline

### ISSUE THREAD

**Issue by Alicia13** [Esri/Survey123Community#115]
I read in a previous post that the basemap offline functionality is coming in the near future, however when I take my survey offline and attempt to locate myself on the map, the map sometimes loads and allows me to zoom in to a certain extent.

Why is this? Where is it getting the basemap from if it's offline?

**Comment by survey123** [comment]
The Survey123 app will cache locally map tiles as you use them. This explains why you can still see the map even when completely disconnected. You will only see map tiles that you have downloaded previously. If you pan the map around you will most likely areas with gaps.
