### ISSUE TITLE
When the survey 123 templates is updated the test for the survey options field throws exception

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#116]
![update_xlsform_error](https://cloud.githubusercontent.com/assets/4204178/7967048/c20b3d3c-09f5-11e5-94e6-0d202d0987d6.png)

The options for select one were changed for the labels and Survey123 connects indicates that the xls spreadsheet has change do you want to update the survey. It throws the attahced error

**Comment by survey123** [comment]
Hi Deepti, it looks like when you changed the choices worksheet you left spaces in the 'name' column. xForms does not support spaces in the name column.
