### ISSUE TITLE
XLSForm conversion failed

### ISSUE THREAD

**Issue by cheungy** [Esri/Survey123Community#117]
I clicked on New Survey and chose Blank design and then received the "XLSForm conversion failed" error. Does anyone know how I can fix this problem? I really wanted to try this tool. Thanks. 

![image](https://cloud.githubusercontent.com/assets/12737316/7970777/568a9648-0a0e-11e5-893b-8f940a6ef543.png)

**Comment by survey123** [comment]
The XLSForm conversion service was temporarily unavailable. My first suggestion would be to try again today now that the service has been restored.

You should have created a project folder in the **My Survey Designs** folder even if the form conversion failed. You can browse to this folder using the **New Survey** menu and select the .xls file to try again.

**Comment by cheungy** [comment]
I just tried to add the survey again but still got the same "XLSForm conversion failed" error.

**Comment by survey123** [comment]
That is weird. Can you please email your xlsfile to survey123@esri.com?  Let us have a look at it.

**Comment by cheungy** [comment]
Please take a look at the xlsfile that I just emailed. Thanks.

**Comment by survey123** [comment]
@cheungy 
I am sorry, but we cannot reproduce this problem. See below. Your survey converts well. 
![untitled](https://cloud.githubusercontent.com/assets/10968332/8000357/6950f1b8-0b0e-11e5-8b67-4c2aab04d654.png)

**Comment by barellaj** [comment]
Hi! I do have the same problem..

**Comment by survey123** [comment]
@barellaj   @cheungy 
We believe we have found the issue. We are working on a new setup for Survey123 Connect for you.

**Comment by dev-pra** [comment]
I am facing the same problem. Do I need to have a 64bit excel?

**Comment by survey123** [comment]
@dev-pra 
64 bit excel will not make any difference.  We suspect that the problem may be caused by a network port used by Connect, which may be blocked in some environments. We are looking at this problem and will create a new setup for Connect for you to try. We will post in this same thread when available.
In the meantime, email us your xls file to survey123@esri.com just to make sure that the error is not caused by something in your excel file.

**Comment by dev-pra** [comment]
Yes, you are right. I am able to edit the form over 4G. Can you mention the port, maybe we can try to unblock and check it. Thanks.

**Comment by survey123** [comment]
http 8080 @dev-pra

**Comment by cheungy** [comment]
Hi,
Any updates on how to fix the problem?



Yuet Sim Cheung
Associate Staff Analyst
Department of Research & Management Analysis
250 Broadway, New York, NY 10007
Tel.(212)306-6072
New York City Housing Authority | nyc.gov/nycha<http://www.nyc.gov/nycha>



________________________________

**Comment by survey123** [comment]
@cheungy 
Survey123 Connect uses port http:8080 to communicate with an ArcGIS service that converts your XLS file into something that Connect and the Survey123 app can understand (an xForm).
In some networks, this port is blocked preventing Survey123 Connect performing the conversion. A new setup of Connect is on the works. One that will use the http:80 port. This port is typically OK. We will later on use https:443, which is also a standard port and hence open in most environments.

It is estimated that we will get the Connect setup out around June 18.  In the meantime, you could do two things:
* Ask your IT Department to open port http:8080 for Connect to work
* Move your machine into a network that does not block 8080. Do it from home, from Starbucks...

Again, new setup coming for you. Apologies for the oversight.

**Comment by survey123** [comment]
Please download the latest version of Survey123 Connect, check the Survey123 REST API URL is pointing to our new service and let us know if you are having any further issues with form conversions.

**Comment by barellaj** [comment]
It works! 
Thank you so much for your prompt response and the quick resolution.

**Comment by dtoy** [comment]
""Please download the latest version of Survey123 Connect, check the Survey123 REST API URL is pointing to our new service and let us know if you are having any further issues with form conversions.""

I don't know what it should be pointing to???

**Comment by survey123** [comment]
Hi Dustin.   Survey123 Connect versions 1.1.18 and prior used an old conversion service that has been decommissioned.  Survey123 Connect should point to https://survey123.arcgis.com/api  which is the new conversion service.  In practice, you should not need to make any edits, because newer versions of Connect all point by default to the correct service. Our recommendation is that you install the latest version of the software. Thanks.
