### ISSUE TITLE
Download attachments?

### ISSUE THREAD

**Issue by dbooth2** [Esri/Survey123Community#119]
So I created a sample survey and captured some photos. I can view them as an attachment from the web map using ArcGIS Online, but none of the available download formats allow me to download the pictures. How do I get the photos/attachments out of the survey and stored as files on my local machine? Thanks

**Comment by Cintruenigo** [comment]
Hi.  This Knowledge Base Article may be able to help. I have not personally tried this, but it looks close to what you need. Essentially, you would need first to download your data into a local file geodatabase. This can be done from the survey123 web site (in the View Results) panel. Once you have the File Geodatabase, you could run the script.

http://support.esri.com/em/knowledgebase/techarticles/detail/41763

This discussion in GeoNet may also help: https://geonet.esri.com/message/427450#427450
