### ISSUE TITLE
regex constraints don't appear to work

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#12]
I am trying to put a constraint on a text field to make sure the user enters an email address.  The regex is: 
regex(., '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}')

I can still enter anything in the box and it doesn't appear to validate it.

![image](https://cloud.githubusercontent.com/assets/793576/6240164/e0d290aa-b6bf-11e4-8242-298c1970d04f.png)

regex is from: http://opendatakit.org/help/form-design/binding/

**Comment by survey123** [comment]
Hi. Thanks a lot for reporting this. We were able to reproduce and it is in fact a bug. We will work on this. Stay tuned for updates.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. 
@sirws

**Comment by sirws** [comment]
Yay!  It works!

**Comment by survey123** [comment]
:)
