### ISSUE TITLE
Choice Filters

### ISSUE THREAD

**Issue by JayW78** [Esri/Survey123Community#120]
Has anyone had any luck setting up a choice filter?  When I set one up it essentially kills my dropdowns menus.  If this is not an option, has anyone created a logic statement where they can specify a look-up list dependent on the previous answer without creating a new field?

**Comment by Cintruenigo** [comment]
Hi. Looks like you want to use Cascaded Selects. Have a look at this issue #53
At the moment Cascaded Selects are not implemented in Survey123, but you may want to add a comment to the issue #53  if you think this is important to your workflows.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
