### ISSUE TITLE
Calculate not honored

### ISSUE THREAD

**Issue by tosiashall** [Esri/Survey123Community#121]
I have a spreadsheet in which I've set up Calculate Formulas, and in the Survey App Calculate property is not invoked.
![spreadsheet1](https://cloud.githubusercontent.com/assets/12941505/8216438/915a6446-1504-11e5-91f9-02613f264c0e.JPG)
![surveyform](https://cloud.githubusercontent.com/assets/12941505/8216479/d29f26d0-1504-11e5-936e-02e4e82f2464.JPG)
Will this calculation be supported soon?

**Comment by Cintruenigo** [comment]
You may need to cast the values to integer.

For example:   int(${Question1})*50

**Comment by tosiashall** [comment]
Didn’t work, unfortunately…

   Tosia Shall | Solution Engineer | Federal Civilian Team Lead
    Esri | 8615 Westwood Center Drive | Vienna, VA 22182 | USA
    T: 703-506-9515 x8015<7035069515,8015> | M: 703-939-0298<7039390298>
    tshall@esri.com<mailto:tshall@esri.com>| esri.com

**Comment by tosiashall** [comment]
I took out my begin and end repeat rows, and now the calculation works just fine.  Thanks for the help!!
