### ISSUE TITLE
XLSForm conversion failed - Unexpected token T

### ISSUE THREAD

**Issue by nemecb** [Esri/Survey123Community#124]
I started up Survey123 Connect today and am getting an XLSForm conversion failed - unexpected token T error message when trying to create a new blank form.

![capture](https://cloud.githubusercontent.com/assets/13004815/8288972/b81ffcaa-18d6-11e5-9c14-7f84d48dc1d8.PNG)

**Comment by Cintruenigo** [comment]
Hi, have a look at #54    This is an unresolved issue at the moment. Try by simply avoiding spaces in your survey name.

**Comment by nemecb** [comment]
Ismael,
That seemed to work.

Unrelated question…Is there a limit in the number of choices you can put in the choices tab?  I need a dropdown in the survey so a street can be selected, but that list is rather long.  It seems after I added all those choices I am having difficulties with the Survey….unresponsiveness.

Thanks!
Brian

**Comment by Cintruenigo** [comment]
Lists with many choices will always be problematic. A list with over 15 or 20 items may be a bit too difficult to navigate in a phone. Not to mention that lists with hundreds of choices will become unresponsive.

Will an auto-suggest style drop-down work for you? If so, you may want to open a new issue so we can flag it as an enhancement request?

**Comment by nemecb** [comment]
Thanks.  I would definitely like to see and auto-suggest style drop-down.  I'll be sure to add it as an enhancement request.
Thanks!
