### ISSUE TITLE
Login Handling

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#126]
If you login to an ArcGIS Online account with no surveys, check the 'Remember Me' box and then try to log out and log back in with another account, it's not possible. <a href="http://screencast.com/t/yKZz2J3G1nF">Video example here</a>. Only option is to uninstall/reinstall.

**Comment by survey123** [comment]
Thanks. Good catch. We will look into this.
Please see notes in this related issue: #113

**Comment by MKellyEsri** [comment]
Great thanks - I just came across it and thought it would be worth reporting!

**Comment by survey123** [comment]
Closing. Fixed in v171 of the Survey123 for ArcGIS app.
Thanks for reporting this.
