### ISSUE TITLE
Pasting Text for Login

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#127]
You cannot paste text into the username/password field on Android. If you use a password manager this can be problematic.

**Comment by zecviewer** [comment]
it will be great to paste texts in other fields too

**Comment by survey123** [comment]
This has been implemented in the 1.2.19 update of the Survey123 field app. Closing this issue. Thanks for your suggestion.

**Comment by esridoyle** [comment]
Has the Paste into other fields been supported yet?

**Comment by survey123** [comment]
Hi. Not yet. Please open a new enhancement so we can track it.
