### ISSUE TITLE
How to localize Survey 123 app?

### ISSUE THREAD

**Issue by anaymushina** [Esri/Survey123Community#128]
Is there any way to localize foms and interface of Survey123 app?
![image](https://cloud.githubusercontent.com/assets/13136343/8456451/32b838e4-2014-11e5-812f-5ed6d2a0a7db.png)

![survey123_localization](https://cloud.githubusercontent.com/assets/13136343/8456408/dcc46d18-2013-11e5-859a-fd75aaedcf83.PNG)

**Comment by marikavertzonis** [comment]
Would you be willing to complete the translations for you preferred language? We would be very happy to supply you with a file with all the strings in it. If you return this completed we can include it in the next build of Survey123. Email us at survey123@esri.com and be sure to specify the language you wish to complete.

**Comment by survey123** [comment]
It is intended that Survey123 will be translated into Esri's standard languages later this year. If you need it translated earlier and are willing to help - do contact the team.

**Comment by survey123** [comment]
Update on this:
* The first localized version of Survey123 is planned to be made available in the Google Play and Apple app stores around the 1st of August. 
* Some strings in your screenshot above will not be automatically localized. For example:
    * The 'GPS Coordinates can only...' text is really a default hint. If you go into your geopoint question and add your hint, it will show up as you specify.
    * The 'Other' option will not be localized. However, rather than using Select_One_Or_Other you could add an additional 'other' option to your choice list, and then if you would like the free text question following you could add a text question with a relevant. Like in the example below.
* The rest of the text highlighted in your screenshots will be localized automatically.

![untitled](https://cloud.githubusercontent.com/assets/10968332/8729117/0f0ffdf6-2b9e-11e5-8c30-1821193062dc.png)

@anaymushina

**Comment by survey123** [comment]
Translations are now supported in the latest version of Survey123. 
![italian](https://cloud.githubusercontent.com/assets/10968332/9265124/3ab7d3a8-4272-11e5-96b9-a43fb25caa83.PNG)

**Comment by yuki-26** [comment]
What are the 28 languages? Has it been translated into those languages? I would like to know if Japanese has already been translated or localized. Thanks in advance!

**Comment by spatialdude** [comment]
Yes Japanese is one of 28 languages.

**Comment by yuki-26** [comment]
When updating to the latest version of Survey123 app, the language has displayed back to English. The attached capture currently displays English, where used to display in Japanese in version 1.1.18. 
![screenshot_20160307-162254](https://cloud.githubusercontent.com/assets/17064065/13563142/78b6ed3a-e482-11e5-8733-da28555c2dfa.png)
![screenshot_20160307-163139](https://cloud.githubusercontent.com/assets/17064065/13563144/79dd8386-e482-11e5-86ae-c0bc45298b6b.png)

**Comment by marikavertzonis** [comment]
Interesting find. we are testing on the devices in our office and found that sony xperia, samsung s3, samsung tab 2 display, nexus 5, nexus 6P, and ipad (just to check if the issue was isolated to android or not) and we see japanese text as expected on those.
A new build has just been accepted in the android store (1.2.89) - can i please ask you download and install that and let us know if there is still a problem? No known change went into build 89 that is related to the language support - but its best to make sure were all looking at the same version.

**Comment by yuki-26** [comment]
The problem has been fixed when the app is updated to the new build at 1.2.89. Although some letters are garbled, Japanese is displayed as it used to be. 

![localizedjapanese1](https://cloud.githubusercontent.com/assets/17064065/13597605/da379aac-e55c-11e5-93c1-71140748367f.png)
![localizedjapanese2](https://cloud.githubusercontent.com/assets/17064065/13597608/dcc3921c-e55c-11e5-8976-86c7aadce0cb.png)

Are you considering providing the new build into App Store as well? The language of Survery123 app for iOS still displays English. 
![img_0211](https://cloud.githubusercontent.com/assets/17064065/13598030/f49fa388-e55e-11e5-8ae9-0ad79e7f0894.PNG)

**Comment by survey123** [comment]
Hi,

 1.8.9 was submitted to the Apple Store yesterday night. The update will be available for download as soon as Apple approves it. While time varies, lately we are getting updates to go through in about 4 to 5 business days.

**Comment by yuki-26** [comment]
Thank you @spatialdude @marikavertzonis @survey123 for your support.

**Comment by survey123** [comment]
1.2.89 available now.

https://geonet.esri.com/groups/survey123/blog/2016/03/09/1289-critical-update-to-the-survey123-mobile-app

**Comment by yuki-26** [comment]
Japanese now displays on the latest build on iOS device. Thanks a lot!
