### ISSUE TITLE
IOS APP - how to switch from AcrGIS online to portal

### ISSUE THREAD

**Issue by KevinCressyArup** [Esri/Survey123Community#129]
Hello,
I have successfully installed the iOS app and connected to ArcGIS online.
However I would now like to connect to my organisations portal site.  The weather does not appear to be an easy way to do this within the iOS app.

**Comment by KevinCressyArup** [comment]
*edit to the above comment - it should say:

There are however does not seem to be a way to change the server instance once the ArcGIS online has been specified within the app.

**Comment by survey123** [comment]
Hi Kevin, the login dialog has a settings button in the top-right corner from which you can control the target portal.

![untitled1](https://cloud.githubusercontent.com/assets/10968332/8601015/19cc3a5a-261e-11e5-8b10-dcc596870dfe.png)

Once you are in 'settings', type the url of your portal, add it and click on the left arrow at the top to go back to the login dialog.

![untitled2](https://cloud.githubusercontent.com/assets/10968332/8601028/391bce84-261e-11e5-86f6-661ce64e337d.png)

You may also find information in this [blog post](https://survey123forarcgis.wordpress.com/2015/06/25/survey123-and-arcgis-for-server/) relevant to your work with Survey123 and Portal for ArcGIS.
