### ISSUE TITLE
Problems with Constraints and Integers using Required Fields when Zero is a desired Value.

### ISSUE THREAD

**Issue by clrogers** [Esri/Survey123Community#130]
When using a field to collect a numeric value and the constraint is set to allow numbers between 0 (zero) and 9999, the validation treats the data entered different if a zero is entered and makes the app think that the field is empty when validated. I'm trying to use a field which holds an integer with the constraint set to allow numbers between 0 and 9999 (.0>= and .<=9999) the field is required when I enter 0 (zero) it validates and says "The filed is required and it is empty" making one think that it sees the numeric 0 as an empty value but it is in the data values when I look at them. Any ideas how to use constraint to allow values betwee 0 and 9999 and set the field to required. I've tried everything I can think of even set the constraint to .>-1 and .<=9999 Thanks in advance!

**Comment by clrogers** [comment]
Upon further discovery it appears with or without a Constraint set a Field of type Integer treats a Zero as an Empty Value during validation when the Field is set to required. Thus you can not enter a Zero in a Field with type Integer when a value is required.

**Comment by survey123** [comment]
Good catch!
We will try to fix this for the next update.
Thanks a lot for your feedback.

**Comment by survey123** [comment]
@clrogers 
Fix applied to Survey123 in Android. Please download again from Google Play to verify.
Fix to iOS has been submitted but will take a few more days to take effect. We will notify when the update is made available by Apple.

**Comment by clrogers** [comment]
Thanks I'll check and let you know if I see any issues.

**Comment by survey123** [comment]
Closing. Available in v171 of the Survey123 app.
Thanks @clrogers  for reporting this one!
