### ISSUE TITLE
Unable to publish surveys against an https-only ArcGIS organization v118 (Connect)

### ISSUE THREAD

**Issue by clrogers** [Esri/Survey123Community#131]
I had a Survey that was published up and running. I made a few changes and republished it locally then tried to upload it and our network disconnected in the middle of the upload corrupting the Survey. I tired to republish it and update the corrupted Survey but it would just hang when updating. I deleted the Survey from both Survey123 Control Panel and from ArcGIS Online but when I try to republish it Survey123 Connect thinks that the Survey has been previously published and won't let me perform a complete new Upload? Any ideas or tricks to remove a log entry perhaps would be greatly appreciated I need to get this republished ASAP... Also is there any way to undelete the previous Survey and restore it in the Survey123 Control Panel or ArcGIS Online...??? Thanks...!!!

**Comment by clrogers** [comment]
Even tried Publishing a Duplicate version of the Survey and now I'm getting an Error Message...

![survey123-publishing-error](https://cloud.githubusercontent.com/assets/12275464/8625724/29db9bb4-2706-11e5-8da6-34d3c6223583.png)

**Comment by Cintruenigo** [comment]
In Connect, open the folder containing your Survey (yellow icon on the left)
Then delete all files except:
-media folder
-the png and xlsx file
Publish again

Some additional info here: https://github.com/Esri/Survey123Community/issues/37

**Comment by clrogers** [comment]
Thanks tried that gave me a different Publish notification but still failed with the following message about SSL

![survey123-publishing-error](https://cloud.githubusercontent.com/assets/12275464/8626578/f3e54abe-270a-11e5-965c-29b9ea9dea77.png)

**Comment by Cintruenigo** [comment]
It looks like version 118 is not working properly against ArcGIS Online organizations configured to use https-only connections.
See #58   Looks like this is broken again.
While we figure this one out you may want to (if you can) enable http access. You will need admin privileges for that.

**Comment by clrogers** [comment]
Okay thanks! I am the Org Admin so I can do that and see if it resolves our issue at least for now.

**Comment by clrogers** [comment]
Yes setting the https back to http allows me to publish the Survey's though this is not desired as we need https. Please let us know when this is corrected. Also if you have any timeline on when the Online Survey Builder Tool might be available the would be awesome as well. Thanks Again.

**Comment by survey123** [comment]
Hi, we have identified the issue. We need to update the Survey123 app in the Apple store and that will take some time. Tentatively we will have a fix around the first half of August.  If this is really urgent we can share a quick fix for you through other channels.  Email us at survey123@esri.com if that is the case.

**Comment by survey123** [comment]
@clrogers 
Survey123 Connect has been updated (v130). You should be able to publish to your https organization now but let us know if that is not the case.  We have also updated the Survey123 mobile app in Google Play with a fix to handle https. The update to the Apple store has been submitted but may take a few days to take effect. We will notify when available.

**Comment by clrogers** [comment]
Awesome thanks...!!! When the Apple update is complete I'll check it and let you know.

**Comment by survey123** [comment]
Fixed Survey123 Connect Build 1.0.143
