### ISSUE TITLE
Survey123 for IOS

### ISSUE THREAD

**Issue by johnjcr** [Esri/Survey123Community#134]
I downloaded the Connectivity app for Survey123 and when I run it, I have a small square window with no information in it.

ESRI rep stated the MAC installer didn't work and to start submit and issue.

**Comment by Cintruenigo** [comment]
Can you send a screenshot of it?
What Mac OS are you running on?

**Comment by johnjcr** [comment]
Are you somewhere I can bring it to you?

John Culbert
Sent using OWA for iPhone
________________________________

**Comment by johnjcr** [comment]
I just talked with Sathya who told me you all were working on it

Thank you for the assistance and the best presentation I attended yesterday.

John Culbert
Sent using OWA for iPhone
________________________________

**Comment by johnjcr** [comment]
I am on IOS 10.10.3



Attached is th[cid:4e59c966-a3f5-4426-b17d-3775ff0da774]?e screenshot

________________________________

**Comment by shobanasuresh** [comment]
@johnjcr Thanks for reporting the problem. The issue has been fixed now. 

Please download the latest Survey123 Connect Mac installer from https://esri.box.com/s/fd1hoav2k26fu82wykj1d3wwhufr76xx. 

The Mac Survey123 Connect installer hosted on the Survey123 website will be updated soon.

**Comment by survey123** [comment]
Thanks John for reporting this. Turned out the Mac setup installer was corrupted. Please download installer again (it has been updated). Closing this issue.
