### ISSUE TITLE
ios app download survey screen not showing surveys 

### ISSUE THREAD

**Issue by MappingAg** [Esri/Survey123Community#136]
Created and Published a few surveys and after I publish and sign in to the app on iPad/iPhone under Download Surveys nothing shows to download.  It works great on the Android app.  Is there something I am missing for the iPhone?

**Comment by survey123** [comment]
Would you mind double checking the sharing settings for your survey in the http://survey123.arcgis.com web site? Check comments in this issue #113 
There should be absolutely no difference between Android and iOS in terms of sharing. If it works for one, it should really work for the other.

@MappingAg

**Comment by markgleveque** [comment]
I am having the same problem as @MappingAg.  Please see my comments on issue #113 .

**Comment by survey123** [comment]
@MappingAg   
@markgleveque 
We are puzzled by this one.
Please contact survey123@esri.com directly so we can get with you on a web cast session or phone call.

**Comment by survey123** [comment]
Thanks to @MappingAg  for the help reproducing the problem.
We pushed an update of the app to Apple which we hope will be approved by Apple around mid-August.
