### ISSUE TITLE
Select a web map from "My Contents"

### ISSUE THREAD

**Issue by dev-pra** [Esri/Survey123Community#138]
We have a project were we want to send the Surveyors to targeted locations. Do we have an option were I can set a web map with target locations?

Apologies for the novice question, but if someone pointing me in the right direction will be greatly appreciated.

Thanks.

**Comment by survey123** [comment]
Hi, unfortunately not. You cannot provision your Survey123 app with assets or locations to inspect/go to. At the moment, all you can do is to capture new data.

**Comment by dev-pra** [comment]
Thanks for the quick reply.
