### ISSUE TITLE
Sort surveys by date (Descending order)

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#14]
Currently the sorting by date puts the oldest surveys first. In my view it makes more sense to sort surveys in descending order. That is: first show me the newest, and last the oldest. The typical scenario is:  you go to Survey123 Connect to create a new survey, then you go to the Survey123 web site to share the survey.
It is much easier to sort by date and get your last survey upfront, rather than in the last page.

**Comment by survey123** [comment]
Thanks, this has been fixed. Closing issue.
