### ISSUE TITLE
Metadata type are not available

### ISSUE THREAD

**Issue by dev-pra** [Esri/Survey123Community#140]
I am unable to use Metadata type fields in the Survey.

**Comment by survey123** [comment]
Hi!  Can you elaborate a bit?
Below is an example of common metadata types:

![untitled](https://cloud.githubusercontent.com/assets/10968332/9066762/44626350-3a8e-11e5-8c9b-cad37bb86c73.png)

The following metadata types will not capture any information in Survey123: deviceid, subscriberid,simserial,phonenumber.

The rest will do:
* start: Captures the time when the user started filling out the form
* end: Captures the time when the user flags the form as done
* username: Captures the username that logged in into the Survey123 app
* email: Captures the logged in user's email (we pick that from the ArcGIS profile)
* today: Captures the date when the form was filled out
