### ISSUE TITLE
photo library list 

### ISSUE THREAD

**Issue by bcgisjosh** [Esri/Survey123Community#141]
When using Survey123 on an iPad or iPhone, and I want to attach photos from my photo library, for most apps it will give me thumbnails directly from the photo library. But Survey123 gives me some directory structure that seems to be housing icons for my apps and not my photo library. Can you fix that so that it is pointing to the right place? Or make it show the thumbnails like most other iOS apps?

**Comment by survey123** [comment]
Hi Joshua, thanks for your feedback. Adding this to the backlog.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
