### ISSUE TITLE
deleting surveys from "My Surveys"

### ISSUE THREAD

**Issue by bcgisjosh** [Esri/Survey123Community#142]
is there a way to delete surveys from My Surveys on the iPad? 
I was doing some testing and now cannot figure out how to get rid of my testing surveys on the tablet.

**Comment by Cintruenigo** [comment]
In your app, in the gallery of surveys, tap on the survey you want to delete. Then open the menu (hamburger style button in the top-right corner) and select Delete Survey

**Comment by bcgisjosh** [comment]
thanks!

**Comment by survey123** [comment]
More details here: #37

**Comment by survey123** [comment]
![pre-delete](https://cloud.githubusercontent.com/assets/10968332/9074765/51591208-3b50-11e5-8f00-81b4b9965586.PNG)![delete](https://cloud.githubusercontent.com/assets/10968332/9074766/54822fe6-3b50-11e5-9285-2ba65b41c6f6.PNG)
