### ISSUE TITLE
XLS Form Conversion Failed

### ISSUE THREAD

**Issue by ryanl44** [Esri/Survey123Community#143]
I have tried creating a new survey with the blank design and keep getting the for same form conversion failed message.

![image](https://cloud.githubusercontent.com/assets/13647685/9069051/da9783ca-3a82-11e5-88de-c3d30bd02992.png)

I have read through your previous topic on this subject https://github.com/Esri/Survey123Community/issues/117
and have made sure that the newest version of Survey123 connect is downloaded and that the API URL is pointing to the new service so I am unsure of what to do at this point.

**Comment by nemecb** [comment]
Remove the blank space from its name. There is a bug right now related to that.
Brian

Sent from my iPad

On Aug 4, 2015, at 12:31 PM, ryanl44 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have tried creating a new survey with the blank design and keep getting the for same form conversion failed message.

[image]<http://cp.mcafee.com/d/5fHCMUedEIcL3AmrLfCXCTHIe9I9CTHIe9LFCQXIIcI6zBd54SzsQsI6zCWbyr9K7G_ow2y5mPQfzqFZoWxnydj9IxlIZ3USGvmeElUzkOrIWNt6PX_nV5VZcszvHTbEKcKsOeos7c6zDG8FHnjlK-zOEuvkzaT0QSyrpdTV5xdVYsyMCqejtPpesRG9pBzWJEshBcCSgrFYrlxfUjVvdFjVQN5BNwsUY_xEVKUqerLEUxFEV7fcSQKPHOpt57TOXPO7BXcEcT88njd79EVjVq14SgGT2TQ02YMYMyOnvhod79u7G_owsgGSuxYrlfH7kaYhGp1l28DN6kOrp3BPrWdTPpFr66UCvb8FIylllmUiCmdbFEw0oaz1Ew5WNld40Bm1DUQBm1Ew5ZAvW1Ewd5068IcCyAS-MrEChL>

I have read through your previous topic on this subject #117<http://cp.mcafee.com/d/2DRPosrhopu78ITuvdTdLnosjojdLnosjvjdFTpopod7aqa9J6VEVod7dQn4Sjsfl-N054aJDEv6RjWNR2L4qCjp2HpW7NJk-ItgHN6FATpRyWdDT-LObPWoV6_nKnhspsVAsMUeod7fkhjmKCHtZ7BgY-F6lK1FJcSOrLOb2rPUV5xcQsCXCOsVHkiP2cFASO7bUdkzb1xK9DOOar8BlllK4FBIBizvQN54sr8lrxrW01uouohpbLEI6zAL3RvIge8lrfg-dGDRzG5u8RcwGx4jUzapdIxOVJZ6XVIQJz3sjfBAkShaGGHs9jb6BQQg0c5hwQg2ZoGCy0iH0PYqiH0Qg2-OfZ0Qg6yw34m6jhirvodQZB_ijyz_P1>
and have made sure that the newest version of Survey123 connect is downloaded and that the API URL is pointing to the new service so I am unsure of what to do at this point.

**Comment by ryanl44** [comment]
Thanks, but I tried that.  The last time I just named the survey "Test2" and still got the same result.

**Comment by survey123** [comment]
@ryanl44 
Would you please email us at survey123@esri.com your contact info? We would like to have a closer look via a screen sharing session or at least get on the phone to learn more details.

**Comment by jwielki** [comment]
I'm having the same issue. We just updated Office to 365 which seems to be an issue in other esri applications like Catalog. Could 365 be a problem?

**Comment by jwielki** [comment]
Just as an update, I'm having this issue on both my office PC, and my Mac at home. I've also tested this on another desktop with no luck.

**Comment by survey123** [comment]
@jwielki 
Please email survey123@esri.com with your contact info so we can talk and try to repro. Thanks.

**Comment by MelissahB** [comment]
I am also getting this error for each type of initial XLSForm designs

**Comment by giesea** [comment]
+1

**Comment by Lee1972** [comment]
Hi,
I am getting the XLS Form Conversion Failed error message when at work. (No problems though when using it on my home pc).
I have upgraded to version 1.0.143 but still get the same error message. It eventually opens an XLS document though, and it is saved in My Survey Designs. But when I browse to the folder still fails on the XLS form conversion, and nothing appears in the survey window.
My IT have checked access to port 8080 and checked firewall settings which seem ok at first glance.
My rest api url is set to https://survey123.esri.com/api 
I have also emailed feedback from my work account if you wish to discuss.
Thanks.

**Comment by martinGIS** [comment]
is there an update on this? we still can't make it work - have the same exact issue as described by Lee1972 above

**Comment by vxsunstriderxv** [comment]
I have the exact same issue as Lee1972 describes aswell.

**Comment by survey123** [comment]
We are looking at ways to make Survey123 more proxy aware, with the possibility of defining a range of IP addresses to be allowed on firewalls.

**Comment by yrebois** [comment]
Hi we still have the same issues and warnings with the portal connexion or online account. we could not convert any form version 1.0. 143 thanks for support

**Comment by jchisum** [comment]
Any update on this? I am having the exact same problem, I've tried everything discussed above and have even emailed survey123@esri.com. Was really hoping to get some survey's published quickly for a demonstration.

**Comment by survey123** [comment]
@jchisum  @vxsunstriderxv  @martinGIS  @Lee1972  @MelissahB  @jwielki @ryanl44 @nemecb 
Please check [latest version of Connect](https://geonet.esri.com/groups/survey123/blog/2015/09/01/random-acts-of-kindness-update-september-1st-2015 ). We incorporated fixes to address this issue.
Thanks a lot for your feedback!

https://geonet.esri.com/groups/survey123/blog/2015/09/01/random-acts-of-kindness-update-september-1st-2015

**Comment by Ephmuya** [comment]
I am experiencing the exact same problem. Did anyone find a solution that works? For me, updating did not work

**Comment by survey123** [comment]
Do you still see exactly the same error window as shown in the opening comment of this thread?
If so, you certainly have not updated the software. Please look in the bottom-left corner of Survey123 Connect and ensure that your build is 1.1.19 or newer.

If you happen to get a different error, please add the screenshot into this thread.

To download the latest version of Survey123 Connect for ArcGIS: go into http://survey123.arcgis.com and sign in. Then scroll at the very bottom and look for the setup.

Thanks!
