### ISSUE TITLE
All Data not being captured

### ISSUE THREAD

**Issue by CPolley7** [Esri/Survey123Community#147]
I created a quick survey and noticed when looking at the data that data I entered into the survey is not being captured when I view it in Survey123.com as well as downloading the data.

**Comment by survey123** [comment]
@CPolley7 Are you saying that there are records missing, or data within a record? Were you able to successfully send your completed surveys from Survey123 without any errors?

When viewing your survey responses on the map when using Survey123.esri.com - please keep in mind that a record without any spatial information cannot be displayed on the map. If you do not have an explicit **geopoint** field in your survey, Survey123 will attempt record your device location _where possible_. If Survey123 cannot determine a location, the record will be captured without geometry. These responses will not be shown on the map.

**Comment by CPolley7** [comment]
correct, i did not have the geopoint enabled .

**Comment by survey123** [comment]
@CPolley7 
If you really want to ensure that a location is always collected, you can make your geopoint type of question 'required'. You can do that by setting the 'required' column to yes for the geopoint question.
In this manner, even if the device is not able to capture a location, you will force the user to set the location manually with the map provided, or by typing the exact coordinates in the map control.
