### ISSUE TITLE
Likert appearance on select fields not supported in forms

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Survey123Community#149]
Setting appearance to likert makes no change to the selection list. Here is an example of a likert appearance:
![examplelikertscale](https://cloud.githubusercontent.com/assets/5713624/9242729/d7770348-41c9-11e5-9a89-71a4526eba0f.png)

**Comment by JeffOrton** [comment]
This functionality is important to several business functions I am evaluating.  Something like:
Is there a problem here? Y/N
List of Problems opens with Likert scale showing intensity of problem on 1-5 scale.

**Comment by survey123** [comment]
Implemented!
More details here: 
* https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
