### ISSUE TITLE
Delete Survey Button feedback

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#15]
When I click on Delete Survey in the Survey Gallery, nothing seems to happen. It would be good if after pushing the button, a clue is given that the Survey is being deleted. Otherwise people will click three or more times while the Survey is being deleted.

**Comment by Cintruenigo** [comment]
Thanks for the fix. Looks awesome now.

**Comment by survey123** [comment]
Closing.

**Comment by Cintruenigo** [comment]
@sathyaprasad 
Minor issue: After deleting survey, the survey gallery should be refreshed. Otherwise the user needs to refresh the browser manually.
