### ISSUE TITLE
Repeat Count Buttons don't remain within the Form Boundaries. 

### ISSUE THREAD

**Issue by clrogers** [Esri/Survey123Community#150]
When using the Repeat features the Count Buttons and the Remove button don't remain within the form boundaries. They appear to exceed the Form width on the laptop, iPhone or Android devices.  

![survey123-repeatbuttonsissue](https://cloud.githubusercontent.com/assets/12275464/9291472/12069752-4388-11e5-98ee-0284ecae8f2d.png)

**Comment by survey123** [comment]
We are hoping to make some significant improvements to the way Survey123 handles **Repeats** in the next release. I have made sure that the development team are aware of this issue.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
