### ISSUE TITLE
Text size of choices and of text boxes for Tablets (Android)

### ISSUE THREAD

**Issue by adismer** [Esri/Survey123Community#151]
The current default text size is for smartphones. I've increased the text size of my questions (see below), 
<font size = "13"> Q1 Label name </font>

but don't know how to increase the text size of the choices for Q1. Also, if Q1 required a text box, I don't know how to make the text box bigger so it is easier to tap on it for Tablets. Is there a way to change text box sizes in Survey123 and also font size of choices?

**Comment by survey123** [comment]
Hi. Unfortunately not at the moment. We set the font size for choices and responses to a value that is readable in phones, tablets and desktops... but this value is not configurable. This is a good enhancement request.  Lets see what others think about it.

**Comment by scoxisda** [comment]
+1
I have the same issue with an Android tablet.

If you have large fingers (me) it is hard to select the next text box when you are filling out a survey. Having the ability to increase the size of the text box, and text size would be a great enhancement.

**Comment by ArianaToth** [comment]
+1

**Comment by RooPitt** [comment]
+1 
When I ran a pilot last week everyone was asking for the ability to zoom in. If this is too much, at least the ability to increase font size would be useful. Unfortunately my fieldwork team do not agree with your assessment of 'a value that is readable in phones, tablets and desktops' :)

**Comment by pbond-idfg** [comment]
+1
Yep, I already know there will be folks in my shop who will complain about not being able to "zoom in" or change the font/text box sizes.

**Comment by DShokes** [comment]
+1 On the 9" samsung Tab A it takes multiple attempts to select any of the radio buttons and then its still a 50/50 that the desired value is selected. 
![image](https://cloud.githubusercontent.com/assets/3903212/13444320/24be862c-dfcb-11e5-84c3-f5d5f9a2f7fb.png)

**Comment by survey123** [comment]
Assigning to next update. Thanks for the feedback.
We are planning to add a new setting in the app that will let the end-user change the size of text in the Form. As the text gets bigger, choices arranged vertically will separate.
Stay tuned for the next update. We will be looking for your feedback! 

@pbond-idfg 
@DShokes 
@RooPitt 
@scoxisda 
@adismer

**Comment by fbrassard** [comment]
+1 
Anxiously waiting for font size update.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
