### ISSUE TITLE
Input masks

### ISSUE THREAD

**Issue by dtoy** [Esri/Survey123Community#152]
Is there a way to use input masks? I would like to enter things such as time and have the ":" automatically be in the entry box. Is this possible? A time picker would work as well, but I need the input masks for other fields as well. Thanks for any help!!!

**Comment by survey123** [comment]
Masking is not possible at the moment. Flagging as an enhancement request to see what others think about it. If you could describe some examples of the specific use cases for this it would be awesome.

**Comment by dtoy** [comment]
The 'time' category requires you to type "12:37:00". I don't want to enter the colons or the seconds. It would be nice if I just had to type "1237".

**Comment by RKnepper3** [comment]
Yes this is a pain.  If you do not want to auto capture a time I can deal with the colons but seconds are rarely needed.  It would be great if it defaults seconds to 00 if you leave it off though input masks would be ideal.

**Comment by survey123** [comment]
Initial implementation now available.
Check:
 * https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
