### ISSUE TITLE
Default fill fields not shown by due to relevant field

### ISSUE THREAD

**Issue by dtoy** [Esri/Survey123Community#153]
Given a certain answer to one question, can another question be defaulted to a certain answer? Example – Previously banded bird? (“No”) -> Before band combination? (“--,--;--,--“). When they selected no it will default without showing "Before band combination" entry box. When Yes is selected, the user would then be shown the option to give input to the "Before band combination" box. Currently, when No is selected, the "Before band combination" doesn't show due to the 'relevant' settings and logs them as blanks in the database.

**Comment by dtoy** [comment]
If you make something not show up due to the relevant category, then I would still want a default value for the question that doesn't show up. Currently if a question doesn't show due to the 'relevant' settings, they are logged as blanks in the database.

**Comment by survey123** [comment]
Hi Dustin,

 applying the default value to a question that is not relevant could be problematic.  The current design is such that if a question is not relevant we persist a NULL value in it. This makes it easier to differentiate the responses that were provided by the user versus those that were not provided (either skipped or not relevant).  Here is an example where storing the default could lead to issues:

 Say your first question is 'is the nest still there'?  If you say yes, the next question will be 'how many eggs did you find in it? with a default value of 2.  If you want to sum all the eggs found in nests, it would not help if we add the default for a record where the nest was missing.

 Not experts in eggs or birds, but we hope the example illustrates why we are hesitant about this one.
