### ISSUE TITLE
A required constraint prohibits submit

### ISSUE THREAD

**Issue by JulianInskip** [Esri/Survey123Community#155]
I have created a sample survey and used a constrain for adding an age if the gender is female (constraint = **(.>25) and (.<45)**, constraint_message = **You must be between 25 and 45 years of age** and relevant = **${gender} = 'f'**). When I am filling out the form on my device and select Male and try and submit, I get the popup **constraint_message**.

If the fields are "hidden" by the **relevant** option and has a **constraint**, should this not still allow you to be able to submit your survey?

Thanks, enjoying this new addition.

**Comment by survey123** [comment]
Thanks a lot for reporting this. Good find.
This is a known issue reported here #78 
We will try to fix this in an upcoming update.
