### ISSUE TITLE
Full page image cannot be opened when field appearance changed

### ISSUE THREAD

**Issue by jshepherd42** [Esri/Survey123Community#156]
If a select_one choice has an associated image, clicking on the thumbnail opens the image to full screen, which is great. If you change the appearance of the field with the choice images, clicking on the image no longer appears to allow you to open it full screen. Is there some way around this or is it a bug?

Cheers,

**Comment by survey123** [comment]
@jshepherd42 Unfortunately, there is no work around, but the fix is already in and will be included in the next release of Survey123 :)

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
