### ISSUE TITLE
Survey123 crashes on Windows 10

### ISSUE THREAD

**Issue by mariof247** [Esri/Survey123Community#158]
It's exactly what I wrote in the title. I've installed survey 123, i go into the menu and create a blank form and immediatly after creating it, survey123 crashes. Then when i start it and i try to open a saved form it will crash without opening it.

Any clues on what's causing it?

**Comment by survey123** [comment]
Please email your survey (the xls file) to us at survey123@esri.com.
Please carify what is your operating system, locale, version of microsoft office and version of Survey123 Connect. Thanks.

**Comment by IsaacDJ** [comment]
I´ve the same issue, when I run Survey I cannot loggin and if I try to create a new form it crashes.

I´m using Windows 10, Office 2013  and Survey 1.0.143. Thanks

**Comment by survey123** [comment]
We are working on a fix to support Windows 10. We are hoping to make it available in the next few days. Stay tuned.

**Comment by survey123** [comment]
@IsaacDJ   @mariof247 
Please check latest version of Connect. We incorporated fixes to address this issue.
Thanks a lot for your feedback.

https://geonet.esri.com/groups/survey123/blog/2015/09/01/random-acts-of-kindness-update-september-1st-2015
