### ISSUE TITLE
Report accuracy reading from the location manager in Survey 123

### ISSUE THREAD

**Issue by chrislesueur** [Esri/Survey123Community#159]
Enhancement Request: When collecting a location (geopoint) in Survey 123 using a GPS show me the accuracy being reported by the location manager in the operating system.  This could be a simple reading that says "GPS accurate to 11 m".

This is particularly valuable when using higher accuracy external GPS devices to verify that you are getting a better position.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.

**Comment by mwittie** [comment]
When I export the data from my form I see x and y columns, but not the accuracy. How can I enable accuracy reporting in my form?

**Comment by tedrick** [comment]
@mwittie - you need to set up a question to store the accuracy value and calculate it using the `pulldata()`function - see http://doc.arcgis.com/en/survey123/desktop/create-surveys/geopoints.htm#ESRI_SECTION1_0C78C5A67E824AC9A4EB47693D47D151
