### ISSUE TITLE
Default and appearance fields not working

### ISSUE THREAD

**Issue by NicholasFury** [Esri/Survey123Community#16]
For some reason, when I make changes to the "default" or "appearance" columns my changes don't seem to be picking up in Survey123Connect.

**Comment by NicholasFury** [comment]
Note -- the default values are important in our case for entering a date of birth.  Standard date default is to today's date -- that's annoying for a birth date.  The appearance is important for many reasons, but specifically here for entering a multiline notes field for physician notes.

**Comment by survey123** [comment]
Hi Fury!  Will get defaults working on our March 27 update.
To get date type questions to default to today, simply type Now() in the default column.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Let us know if this works now you and we will close issue.
Defaults should work for sure, no exceptions.
With Appearance, please try things out and report in separate issues specifics that don't work and are important to you.
@NicholasFury
