### ISSUE TITLE
iphone 6+ IOS 8.4 Photo Crashing

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#165]
We have full survery completed, works fine on the Ipad but on a users Iphone it keeps crashing when they take a picture sometimes there is an issue with it crashing.  This never happens on Ipads or android though?

**Comment by RKnepper3** [comment]
I had posted this in Geonet and they tested my survey, they said it might be a memory issue or possibly because I mentioned the wireless was not great at the time (not my phone so I didnt have full details).  I asked them to try it with nothing open and stable wireless and let me know if it happens still.

**Comment by survey123** [comment]
Cl
