### ISSUE TITLE
Relevant criteria not working (Connect build 158)

### ISSUE THREAD

**Issue by ryanl44** [Esri/Survey123Community#167]
In the current version of Survey123 I am unable to properly use the relevant questions option.  For instance, if I copy the example from your tutorial (regarding pizza and favorite toppings) into a new survey, the questions regarding favorite toppings will display regardless of whether the user selects "yes" or "no" to liking pizza.  Th question regarding toppings is only supposed to display if they select "yes."

**Comment by survey123** [comment]
@ryanl44 
Apologies!  Indeed build 158 was broken!
We just updated the Connect build to address this issue. The version number is 1.1.4

**Comment by ftm610** [comment]
@survey123 Where can I find the installer for the new 1.1.4 build? The link to the Windows Connect build at http://survey123.esri.com/#/home is still for version 1.0.158.

**Comment by survey123** [comment]
@ftm610 
Same link as usual, just checked and the setup is for 1.1.4.
Please make sure you are looking at the right file in your desktop. Refresh your browser just in case.

![untitled](https://cloud.githubusercontent.com/assets/10968332/9769896/ab0fc92a-56e1-11e5-89ad-c5188eee4c78.png)

**Comment by ftm610** [comment]
@survey123 Thanks. I just gave it another go, uninstalled previous version, downloaded from website (new browser) & reinstalled. Not sure what I am missing here see screenshots from both the installer and the GUI show version 1.0.158...
![survey123 connect 1 0 158 setup 992015 80405 am](https://cloud.githubusercontent.com/assets/8484676/9770085/b67b4ed2-56c9-11e5-9028-6478cd84aaa9.jpg)
![survey123connect 992015 80606 am](https://cloud.githubusercontent.com/assets/8484676/9770090/b85fba4e-56c9-11e5-926a-e3e6190bc621.jpg)

**Comment by survey123** [comment]
Direct link to windows installer: https://maps.esri.com/SP_DEMOS/qmlapps/Survey123/Survey123Connect-Setup-x86.exe

**Comment by ftm610** [comment]
That did it, thanks @survey123 !
