### ISSUE TITLE
Minimal appearance doesn't work for select_multiple question type

### ISSUE THREAD

**Issue by simontheguide** [Esri/Survey123Community#169]
Hi,

I developing a survey form and wanted to use the select_multiple type with minimal appearance to provide a drop-down list for selecting multiple options. However, the appearance defaults to the horizontal check-list. 

I have used the minimal appearance with the select_one type but it the minimal appearance doesn't seem to work with the select_multiple type.

I thought this was possible, I wonder why it's not working?

Thanks,
Simon

**Comment by survey123** [comment]
Hi Simon,

 As of v171 select multiples are not shown as a dropdown list even if you use minimal appearance, but this is something other people also have requested in the past, so we are going to look at this and see what we can do. :)
Stay tuned, we will post here a comment when we have news.

**Comment by simontheguide** [comment]
Thank you for the help, looking forward to the new beta release in October!

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
