### ISSUE TITLE
Error message when signing into arcgis online through survey123 and error publishing to ArcGIS Online account

### ISSUE THREAD

**Issue by simontheguide** [Esri/Survey123Community#170]
I am trying to submit a ArcGIS Survey123 form to my ArcGIS Online account so that I can trial it on a tablet. I have been getting this error message the when I try to sign into ArcGIS Online through ArcGIS Survey123 Connect. Although when I try to sign in after multiple tries I do manage to I get signed-in. Even our ArcGIS online Administrator Glen Clarkin, Bay of Plenty Regional Council, received this message.
![errror signing into arcgis online from survey123](https://cloud.githubusercontent.com/assets/14264365/9839519/28c252a0-5ad1-11e5-8f66-857e4262a23b.jpg)

Furthermore, after being signed in and trying to publish the form to my ArcGIS Online organizational account (as a publisher) I get a publishing error.
 ![error trying to publish form from survey123 connect to arcgis online account](https://cloud.githubusercontent.com/assets/14264365/9839521/2fefe3bc-5ad1-11e5-8c96-ff61c7957f72.jpg)

After trying to publish the form In ArcGIS Online, a folder is created in My Content called Survey-Form 3 and the survey form (Form 3) feature layer is there but it seems unusually small (1KB) and it doesn’t show any of the properties or attributes when adding it to a map.

Any suggestions or fixes would be great, 
Thank you,
Simon

**Comment by survey123** [comment]
Hi Simon,

 on the first issue (insufficient privileges), we only show that message when the logged in user does not have sufficient privileges. It is strange that using exactly the same account you get this dialog intermittently.   If you keep getting this and you are sure your users has the privileges listed, please send us your contact info at survey123@esri.com so we can setup a screen sharing session. 

 the second issue is easier: If Survey123 Connect for whatever reason fails to create a survey, it could leave leftover items in your ArcGIS Online account.  Have a look at this post to learn how to clean it up: #37

**Comment by simontheguide** [comment]
RE: ArcGIS Survey123: ArcGIS Online Login Error and Publishing Error - Issue Resolved

If you get an error when trying to login (insufficient privileges) to your ArcGIS Online account through survey 123 Connect and experience errors trying to publish your feature service, CHECK YOUR PROXY SERVER FIREWALL SECURITY.

These firewall/security settings can cause these errors. To troubleshoot this issue, try and login to your ArcGIS Online account through Survey123 connect on a different internet connection with less secure settings and publish your survey.

Thanks
