### ISSUE TITLE
Cascading Select with Survey123 is not working

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#173]
2.	Cascading Select did not work when we had a choice_filter set. Attached is the survey xls form we used.
  

![xls form_cascading select](https://cloud.githubusercontent.com/assets/4204178/9912644/afd6fe3e-5c76-11e5-996f-0ffb7fa6b7b5.jpg)
![xls form_cascading select1](https://cloud.githubusercontent.com/assets/4204178/9912649/b1db0522-5c76-11e5-903e-c89cc44ac024.jpg)

**Comment by survey123** [comment]
Hi Deepti,

Can you also provide a screenshot of the _choices_ tab? It is difficult to see what your _choice_filter_ expressions are referencing. Let's get to the bottom of this!

In general, the choice filter works by adding extra columns to your choice lists, like this:
![cascadeselect](https://cloud.githubusercontent.com/assets/10968332/9925827/20e3d5b6-5d53-11e5-8ee6-749113a475c8.PNG)

Then, when you build your expression, you can use the values in the extra columns to restrict the choices available in your list, like this:
![choice_filter](https://cloud.githubusercontent.com/assets/10968332/9925855/8eb8a788-5d53-11e5-939a-45d3467b4709.PNG)

When I use the expression **country=${country_name}** as a choice filter for **select_one states**, I am asking Survey123 to scan the _country_ column for the choices in my _states_ list, and then only show me the records that match the _country_name_ answer for the previous question.

**Comment by survey123** [comment]
Fixed on build 1.1.4. Closing.
