### ISSUE TITLE
Moto X - Feature attachments never upload. Retrying the upload just creates duplicate unfinished features in the feature service

### ISSUE THREAD

**Issue by ssylvia** [Esri/Survey123Community#175]

**Comment by survey123** [comment]
What device are you using to capture the photos?
Are you taking a new photo or browsing for an existing one in your device?
Do you get any error/warning in the app?

**Comment by ssylvia** [comment]
- Andorid Moto X 2014
- Browsing from existing
- No, uploading screen just continues to spin (waited 5 min)

**Comment by survey123** [comment]
#207
