### ISSUE TITLE
If disconnected, the x/y is not captured or not submitted to the website

### ISSUE THREAD

**Issue by aallegretti** [Esri/Survey123Community#18]
Steps to reproduce:
1) download survey
2) put phone in airplane mode
3) hit button to capture location
4) feature submitted but geometry is null

**Comment by survey123** [comment]
Some devices rely on the cell network to get a position, in which case when it airplane mode the positioning won't work. Other devices have a GPS which should continue to work even when in airplane mode.

We are working on compiling a list of devices and determine which can get a position when in airplane mode or there is no connectivity. We will use this information to appropriately define the behavior of the survey.

**Comment by survey123** [comment]
@aallegretti 

Do not be shy! Let us know if this is working please.
