### ISSUE TITLE
signature does not work anymore.

### ISSUE THREAD

**Issue by Cpolley** [Esri/Survey123Community#180]
it looks like the signature in appearance is missing, so now you cannot create signature to capture.

**Comment by survey123** [comment]
Hi.  You may be using a survey based on an old blank form?  If you use Survey123 Connect 1.0.143 or newer the blank for includes the signature appearance. If that is not the case, you may want to install again Survey123 Connect from the web site and create a new form with the blank form.

Alternatively, you can manually add the signature choice to the appearance list by simply inserting a new row in the appearance section of the types worksheet. Just make sure the new row with the word signature is not at the beginning or the end of the list of choices. Make sure it is somewhere in the middle. Below is a screenshot of the types as of 1.0.143 where signature is at the beginning... but you get the point.

![untitled](https://cloud.githubusercontent.com/assets/10968332/9946757/315795da-5d4a-11e5-8c2e-c0205b22efa8.png)
