### ISSUE TITLE
Field Constraint and Required Fields

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#182]
If a field has a constraint set, but is not required, there is no way of submitting the form. When you try to submit the form, the constraint message appears even though the field is not required - tested on Android, iOS and Survey123Connect.

name: text
label: email
hint: What is your <u>email</u> address?
email: Email address will be validated.
constraint: regex(., '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}')
constraint message: "Your email address must be in an email address format!! See specific constraint used below."

**Comment by survey123** [comment]
Thanks for the feedback.
We are working on this and will try to resolve as soon as we can.
Flagging as duplicate since the issue has been raised at: #78  #167  #155

**Comment by MKellyEsri** [comment]
Thanks for quick reply. Very good - I obviously didn't look through bugs before submitting!

**Comment by survey123** [comment]
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update

**Comment by MKellyEsri** [comment]
Great work guys - cheers!
