### ISSUE TITLE
Audio - 'Play' button not visible

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#183]
If you have audio setup with list options, the 'Play' button does not appear if you have a different appearance set - e.g. horizontal or minimal.

Note: the play button appears fine in Survey123Connect, but is not visible on mobile devices (tested on iOS/Android).

**Comment by survey123** [comment]
Thank you for your feedback,

This issue has already been addressed by our development team and will be included in the next release of Survey123.

**Comment by MKellyEsri** [comment]
Brilliant, thanks for the quick reply!

**Comment by pbond-idfg** [comment]
+1.  This is still an issue with version 1.2.12

**Comment by survey123** [comment]
Moving into the June 2016 milestone. Fix to be available in 1.5. Thanks for your patience.
@pbond-idfg   @MKellyEsri

**Comment by pbond-idfg** [comment]
Excellent! Thanks for the update.

**Comment by survey123** [comment]
Fixed in version 1.5.x (Available in the stores now)
