### ISSUE TITLE
excel form drop downs not available? (Office 2007 on Win8)

### ISSUE THREAD

**Issue by bcgisjosh** [Esri/Survey123Community#185]
I have Survey123 connect on my work computer (Win7) and today I downloaded it to my home computer on Win8. i noticed that the drop down in Excel when making the form doesn't work. for the "type" field there's no drop down to pick from "text" or "integer" etc. 
is there a problem with my excel version? (office 2007)

**Comment by survey123** [comment]
@bcgisjosh I am afraid you are correct - the drop-downs that are included in the Blank survey template will only work in newer versions of Excel.

However, the content for all of the lists is available on the 'Types' tab in the Blank template:
![types](https://cloud.githubusercontent.com/assets/10968332/9983775/45230f08-604d-11e5-8951-9cfe15ecd02d.PNG)
