### ISSUE TITLE
Opening previously sent survey, editing, and resubmitting creates new record

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#186]
Instead up updating the existing survey in the feature service, a new record gets created. I am using the build from 9/9 (iOS- HockeyApp).

http://statesales.maps.arcgis.com/home/webmap/viewer.html?layers=8e3e7e3d42c748119ffe00b85ac92d8d

http://statesales.maps.arcgis.com/home/item.html?id=cb979436d2234c5ca57774ef9c263d4b

**Comment by survey123** [comment]
Hi Scott. This is the behavior we have put in place for the moment. As we work into preloading CSV (as per the XLSForm spec) we will look into editing existing features.  Think of the Sent folder as in your mail: once you have sent an email... it is sent. You could open a sent email and send it again... but it would be a completely new email. :)

![untitled](https://cloud.githubusercontent.com/assets/10968332/9970673/5f9c8c4a-5e0b-11e5-8dde-6bb69727eb4a.png)

**Comment by johngillham** [comment]
@survey123 I couldn't find any other reference to it, but was wondering if editing existing records within Survey123 is on roadmap, and if so would you have a rough (unofficial) ballpark for seeing that critical functionality implemented?

**Comment by survey123** [comment]
Editing functionality will most likely come in the second half of 2016. In the meantime, some folks are implementing this feature on their own using AppStudio for ArcGIS, which includes the source code of Survey123 starting at v1.1
