### ISSUE TITLE
Username is Case Sensitive

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#189]
When logging into Survey123 on a mobile device or using Survey123Connect, the username is case sensitive. For example, my username in ArcGIS Online is as follows:

![image](https://cloud.githubusercontent.com/assets/9192183/9988723/e99d57bc-604a-11e5-9e31-b7126daf7488.png)

If I login with anything other than MKelly8 (e.g. mkelly8/Mkelly8) I get the following message:

Unable to generate token.
Invalid username or password.

![image](https://cloud.githubusercontent.com/assets/9192183/9988692/a30a5f98-604a-11e5-9cdb-5d2dff0546ed.png)

**Comment by survey123** [comment]
Survey123 will continue to enforce case-sensitivity for usernames when logging into ArcGIS Online.
