### ISSUE TITLE
Android - Field Value Text Too Light

### ISSUE THREAD

**Issue by dfabulic** [Esri/Survey123Community#19]
Font color for field values (including login username and password, and actual rendered form values) are so light to make it almost invisible:

![screenshot_2015-02-20-11-18-25](https://cloud.githubusercontent.com/assets/4203274/6290173/f82bd092-b8f2-11e4-8b6b-064918545f98.png)

In the screenshot above all fields are populated, but values are almost invisible.

I tried it with couple of forms, it always seems to be the same.

Screenshot was taken on Moto X 2nd gen, Android 5.0 (Lollipop)

**Comment by survey123** [comment]
Thanks. We plan on fixing this in the next few days. Expect a note shortly.

**Comment by dfabulic** [comment]
The form looks different in the latest build, but font is still too light.

![screenshot_2015-03-05-09-58-03](https://cloud.githubusercontent.com/assets/4203274/6507357/9baf6f40-c31f-11e4-9040-f42eaa09a7fc.png)

**Comment by survey123** [comment]
Hi.  We have updated the Survey123 App to accommodate your request. Please try again and let us know what you think.

**Comment by survey123** [comment]
@dfabulic   Please update Survey123 app and let us know if this is working OK now. Ready to close if you confirm.  App last updated March 18.

**Comment by survey123** [comment]
Closing
