### ISSUE TITLE
Dropdown menus in Survey 123 Forms

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#192]
I would like to use a dropdown menu instead of the select_one checkboxes because i have a list of over 200 items to choose from. With the check boxes, the user has to scroll through all of them to get to the next question int he form. Will this be added soon/ever?

Thanks.

**Comment by survey123** [comment]
Thanks for your comment.
Yes. We will allow you to use 'minimal' appearance ( dropdown ), with your select multiple questions. Additionally we will implement cascading selects which may help you break down hierarchical lists into multiple selects.
This will be available very soon.

**Comment by bowlesgsrcx** [comment]
Thanks. Looking forward to the enhancements.

**Comment by survey123** [comment]
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update
