### ISSUE TITLE
Sharing of data

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#193]
I am not sure if it is on my end or a constraint of Survery123.  Once you have data collected and stored on AGOL it seems only the creator of the survey can access the data?  I have the feature service and map shared to a group on AGOL and other people can view everything but if they goto the feature service there is no option to download the data and you can not check off allow other to export.  In the Survery123 site they can not see the survey data at all. How can you allow someone access to the data for export?

**Comment by survey123** [comment]
Hi Ronald,

 in the feature service item description, click on edit and scroll to the bottom. Check the box highlighted in the screenshot below and save.  At that moment, any user with access to your feature service will be able to download the data.

![untitled](https://cloud.githubusercontent.com/assets/10968332/10105305/ccc03720-6362-11e5-93f1-cba282bf1a17.png)

**Comment by RKnepper3** [comment]
Thanks, yes I checked off that options yesterday several times with another user online.  Each time I saved with that check it would not record the box as checked.  You sent this email so I went in again and this morning it was checked off.  Just odd, some kind of delay in added that to the service.  All good.

**Comment by RKnepper3** [comment]
Thanks, yes I checked off that options yesterday several times with another user online.  Each time I saved with that check it would not record the box as checked.  You sent this email so I went in again and this morning it was checked off.  Just odd, some kind of delay in added that to the service.  All good.
