### ISSUE TITLE
drop downs and images

### ISSUE THREAD

**Issue by ljaupi** [Esri/Survey123Community#194]
I'd like to have a drop down box that when I select an item it shows the picture in another box? For example if I select Anti-personnel Mine from the drop down it shows the picture of an antipersonnel mine in the picture box and if I select an Anti-tank Mine it shows the picture of anti tank mine.

Thanks ESRI!

Your friends at HALO Trust (www.halotrust.org)

**Comment by survey123** [comment]
Something like this may help.

![untitled](https://cloud.githubusercontent.com/assets/10968332/10124001/df0b4fd6-64fd-11e5-9600-32eca6311330.png)
