### ISSUE TITLE
Date fields don't appear to work when submitting surveys to ArcGIS Online (build 0.0.20)

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#2]
In the Review area, I get the following error:

The survey was not able to be submitted.  Please correct the survey data and resubmit.  Code 1000.  Conversion failed when converting data and/or time from character string.

![image](https://cloud.githubusercontent.com/assets/793576/6194638/ef32b924-b37a-11e4-837c-cae3c83bce16.png)

![image](https://cloud.githubusercontent.com/assets/793576/6194656/0df945bc-b37b-11e4-961e-3db0a1378c23.png)

**Comment by sirws** [comment]
If I remove the date field, it works fine.

**Comment by Cintruenigo** [comment]
I tried 0.0.22.  While I did not get the error reported by Scott, the submit process fails.

![untitled](https://cloud.githubusercontent.com/assets/1273440/6198949/1dc143e8-b3d8-11e4-95ec-996062d65efa.png)

Removing questions with type Date makes the survey submission work.

**Comment by HannahFerrier** [comment]
Please try again with Survey123 Build 0.0.24
We are aware that the default date values are not yet being accepted in this build. 
Please make sure you select a date - even if it is today's date - to make sure the date values are accepted correctly.

**Comment by Cintruenigo** [comment]
Thanks! Tested on 0.0.25 and it works great!

**Comment by survey123** [comment]
Fixed. Closing.
