### ISSUE TITLE
Taking photos causing Survey123 to crash and all data to be lost

### ISSUE THREAD

**Issue by ryanl44** [Esri/Survey123Community#200]
Hi,

We've recently run into issues with both tablets and phones crashing multiple times when trying to take one or more photos to complete surveys.  The specs for the devices are listed below.  Thanks for your help.

Samsung Note2; android os 4.4.2
•	Taking photo caused application to crash, needed to reload, lost all information. 
•	This occurred multiple times.

Samsung Tab 4 7”; android os 4.4.2
•	Taking photo caused application to crash, needed to reload, lost all information.
•	Had 3 photos taken, then scrolled, application crashed, needed to reload, lost all information.

**Comment by survey123** [comment]
We have been attempting to reproduce this on an Android Phone running 4.4.2 and I have a couple of questions:

- Are you seeing a freeze (unresponsive UI, need to force close) or a crash (application closes unexpectedly)?

- Are your photo fields inside repeats, or do you have multiple photo fields on your forms?

The more information we have, the closer we are to solving the issue :)

**Comment by ryanl44** [comment]
Regarding the photo fields, they are not inside a repeat, the form has 4 photo fields at the very end of the survey.  The inspectors responses to you other questions are as follows:

o	User1 (Samsung Note 2, 4.4.2 android os):  The user got to the end of the survey which allows them to take 4 photos.  The time between photo taking can vary in the field since the user is walking to manholes at different locations on the block.  The user had taken 3 photos.  On taking the fourth photo, the input screen disappeared and the initial Survey 123 screen appeared and started to reload the survey.
o	User2 (Samsung Tab 4, 4.4.2. android os):  The user got to the end of the survey which allows them to take 4 photos.  Upon clicking on the first camera button in Survey 123, the camera screen was black.  After a 5 second period, Survey 123 crashed and the tablet reverted to the home screen.
o	User2 (Samsung Tab 4, 4.4.2. android os):  The user got to the end of the survey which allows them to take 4 photos.  The time between photo taking can vary in the field since the user is walking to manholes at different locations on the block.  The user had taken 3 photos.  The user attempted to scroll down to the fourth Survey 123 camera button.  The screen froze.  A 5 second period elapsed, Survey 123 crashed and the table reverted to the home screen.
o	In all three cases, all data in Survey 123 was lost

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
