### ISSUE TITLE
Updating survey attributes ArcGIS Online

### ISSUE THREAD

**Issue by katyhaddock** [Esri/Survey123Community#201]
I have updated an existing survey and published using Survey 123 desktop, using an ISO device I then completed the survey and sent the survey to view in ArcGIS Online. Unfortunately within ArcGIS Online the attributes have not updated with the extra questions added to the existing survey and therefore only show the first survey questions published when the survey was initially created. Is it possible to update an existing survey or do you have to recreate the survey every time you make amendments? Thank you.

**Comment by RKnepper3** [comment]
Curious, did you delete the old survey off the device and download again?  I've redone surveys many times without issue.

**Comment by survey123** [comment]
Hi.  The latest version of Survey123 Connect handles much better amendments to your Survey. Please download the latest from http://doc.arcgis.com/en/survey123/download/ 

To be on top of the latest improvements to Survey123 or to ask technical questions, please participate in our GeoNet Group: https://geonet.esri.com/groups/survey123
