### ISSUE TITLE
Cascading selects example xls sheet - not working?

### ISSUE THREAD

**Issue by bcgisjosh** [Esri/Survey123Community#203]
I saw the blog entry about Cascading selects being a new feature with Survey123. (http://survey123.esri.com/resources/XLSFormSupport/#cascade) So I downloaded the latest version of Survey123 Connect and I downloaded the xls sample form.
But I got this error message when trying to use the xls form in Survey123. I’m using MS Excel 2010 version 14.0.7145.5000 (32 bit)

Error message: 

Error Report Details: 
Status Code: 500 
Error: 401 Error downloading https://survey123.esri.com/api/xls2xform - server replied: Internal Server Error 

Operating System: windows 
Application Version: 1.1.18 
Framework version: 1.0.1087 
[Please add any further comments here]

**Comment by survey123** [comment]
We are looking into this. Our server is having intermittent problems.
