### ISSUE TITLE
User interface for numeric questions on IPad vs android phone

### ISSUE THREAD

**Issue by simontheguide** [Esri/Survey123Community#204]
Hi,

I recently developed an survey123 form for stream habitat assessments and it is working great!  I am using an IPad mostly and I was wondering if it was possible to modify the user interface for numeric questions so that a calculator pops up rather than the keyboard?

When using an android phone, a calculator pops up for numeric questions which makes entering numeric data much faster and easier.

- Maybe it is as easy as upgrading the iOs of the IPad?

Thanks,
Simon

**Comment by survey123** [comment]
Hi Simon,

 Upgrading your iOS will not really help. We initially had the numeric keyboard active for numeric questions, but unfortunately in iOS it was not easy to close ( no done button) so we went back to the full keyboard. We had to do this only on iOS. Android, Mac and Windows behave as expected showing a numeric keyboard.
