### ISSUE TITLE
error downloading API

### ISSUE THREAD

**Issue by zecviewer** [Esri/Survey123Community#205]
i'm having this message, i cant upload my form. any suggestion?

![image](https://cloud.githubusercontent.com/assets/3708192/10356097/0d234f84-6d39-11e5-8b9a-e5999e14cb95.png)

Windows 7 x64

**Comment by survey123** [comment]
We are looking into this. Our server is having intermittent problems.

**Comment by spado** [comment]
I have that problem too! Please fix soon as my job depends on it

**Comment by spatialdude** [comment]
Thanks to error reports we have been receiving, we were able to pinpoint the source of the problem. Thanks for helping us improve!  

The latest version of Survey123 Connect for ArcGIS has been made available and includes a fix that will address the problem you observe. 

For details please have a look at our blog: https://geonet.esri.com/groups/survey123/blog/2015/10/18/survey123-xls-form-conversion-service
