### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by simontheguide** [Esri/Survey123Community#208]
I am currently working on a new aquatic pest plants survey form using survey123 connect build 1.1.18 and am having some issues when saving changes made to my form. Typically, changes results in a form conversion and I can see how my changes look as an app. I get the following error
![image](https://cloud.githubusercontent.com/assets/14264365/10442397/aa3b6cec-71ae-11e5-8ce8-a4f000175509.png)

Is this a problem with the xls form converter on the ESRI site? Usually, I can workaround the error but sometimes even a restart won't reset this error message and I have to create a new form.

Thanks,
Simon

Note: I see you are already looking into this as is is same issue as #205 - can't download API. Sorry for the double up.

**Comment by survey123** [comment]
Hi Simon, we are experience intermittent issues with our server. We are working to resolve this. Our apologies for the inconvenience. It will take us a few days to resolve this.

**Comment by spatialdude** [comment]
Thanks to error reports we have been receiving, we were able to pinpoint the source of the problem. Thanks for helping us improve!

The latest version of Survey123 Connect for ArcGIS has been made available and includes a fix that will address the problem you observe.

For details please have a look at our blog: https://geonet.esri.com/groups/survey123/blog/2015/10/18/survey123-xls-form-conversion-service
