### ISSUE TITLE
Repeats not working

### ISSUE THREAD

**Issue by NicholasFury** [Esri/Survey123Community#21]
Although they appear to work in the survey preview in 123Connect, repeats are failing to collect data on the app.  This is very important for our deployment, given that we're using repeats to capture multiple diagnoses per patient.

**Comment by survey123** [comment]
Thanks a lot. We will work on this although this is proving harder than we anticipated!

**Comment by nemecb** [comment]
+1

**Comment by vxsunstriderxv** [comment]
+1

**Comment by survey123** [comment]
Closing. 
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update
