### ISSUE TITLE
Survey Only Allows one Picture per field

### ISSUE THREAD

**Issue by clrogers** [Esri/Survey123Community#210]
Wondering why the Survey only allows one picture per Survey unless you put multiple Photo entries in the form? Best Practice would be to allow multiple pictures from the camera or selected from a folder(s) then iterate through each picture placing each one as a element of the Survey record. By having to have a one-for-one picture holder so to speak makes it impractical for creating a Survey which may have 25 or more photos such as when Surveying an area after a natural disaster. Or maybe I've missed something in the documentation somewhere. Thanks in advance!

**Comment by clrogers** [comment]
Thinking out loud can this be fixed/accomplished by placing a Photo field within a Repeat perhaps...???

**Comment by clrogers** [comment]
It was worth a try the Form seems to be able to take the multiple photos in a Repeat but when trying to submit/upload them the Survey123 App throws an Error Code 400... Any one have any ideas...???

**Comment by RKnepper3** [comment]
I like the one photo per field, it allows you to uniquely name each photo since the field name is the photo name in the fgbb.  I am curious about the repeats though, as you mention it should allow you (as that is mainly how I would always use them) and name each like field name 1, 2, .....

**Comment by clrogers** [comment]
I agree when you are only taking one or two pictures this is a relatively quick feature to be able to name the photo from the field name though when you are taking multiple photos it is very cumbersome. The form should be able to iterate through each photo taken and assign an incremental photo name from the field name perhaps or allow the user to add a brief and/or unique name to each photo perhaps. In the instance of collecting lots of photos such as in the case of Surveying community damage after a weather event I may be at a particular location 123 Smith Street taking photos of the damage to the house at that location but it would be most cumbersome to have to take 50-100 pictures and name each individually in separate fields before being able to upload them. Instead I should be able to take multiple pictures that use other data fields to include date/time/gps and incremental number to automatically construct a filename for each photo. This way I can take as many pictures as needed/required without having to touch and/or manage each one individually. Even in a Census type of setting I should be able to take multiple pictures of a family to historically recorded members of a family (assuming this is legally acceptable) and the Repeat capability may be part of the secret to this though each Repeat would then contain a separate photo field which would use the name (or other info) of each person to construct the final photo filename. These are just a couple of Use Cases I see that would be very handy.

**Comment by clrogers** [comment]
Upon conducting further testing I have built a Survey that has a Repeat containing a Photo field and a Photo Description field. When I use the Survey to collect multiple photos or images the data appears to be valid, the Feature Object appears to be valid, and the Survey in Connect shows its valid but it fails to send giving an Error.

Here are the Data Values the Survey produces...
![survey123-photorepeater-showdatavalues](https://cloud.githubusercontent.com/assets/12275464/10521489/be9bbfa6-7335-11e5-81e2-33337d4402eb.png)

Here is the Feature Object the Survey produces...
![survey123-photorepeater-showfeatureobject](https://cloud.githubusercontent.com/assets/12275464/10521518/e3e14f42-7335-11e5-8304-dc1f13b015f7.png)

Here is the Data Validation message the Survey produces...
![survey123-photorepeater-validateinput](https://cloud.githubusercontent.com/assets/12275464/10521540/ff0188e6-7335-11e5-8534-92b96c6f76e2.png)

Here is the Survey itself...
![survey123-photorepeater-photocollectorapp](https://cloud.githubusercontent.com/assets/12275464/10521480/b38ade26-7335-11e5-9fb1-aff096b988bb.png)

It appears that there is a problem when the Survey tries to upload the data when there are multiple Photos/Attachments/Images contained in the Object.

Any ideas, comments, and or advice would be greatly appreciated...!!!

**Comment by clrogers** [comment]
Almost forgot here's the Error that is produced when I try to upload the Survey...

![survey123-photorepeater-datasubmissionerror](https://cloud.githubusercontent.com/assets/12275464/10521731/09589a5e-7337-11e5-9a80-f7edd175c735.png)

**Comment by clrogers** [comment]
Testing Update... I was able to get the Repeat to work and upload multiple pictures with only a Repeat containing an Image Field and a Description Field but when the Files uploaded there was no location as I had not included a GeoPoint. Once I included a GeoPoint Field either above the Repeat or within the Repeat the Survey failed and threw an Error 1006 Application Rolled Back Error...

It appears that Survey123 or when the XForm is constructed it has a problem with multiple Pics with a Single GeoPoint... not sure why the multiple pics would load without a GeoPoint (or any other fields) reference but would not when adding the GeoPoint Reference...

Will continue running some different tests... need multiple pics with a single event in the easiest way possible and with this last test I could see being able to potentially assign a different GeoPoint to each Pic...

Cheers...!!!

**Comment by simontheguide** [comment]
You should be able to create a repeat for images. I have done this with a survey form I created. Just create a geopoint not in the repeat. The only trouble is downloading the photos back from the cloud. The only way I have been able to do this is to download a file geodatabase, run a script tool that downloads the photos from the geodatabase into a file folder. The naming of the picture is not very good though and would somehow need to include the address/house number linking it to the data.

Good luck.

**Comment by clrogers** [comment]
Has anyone been able to accomplish this to allow for multiple pictures in a single Survey Upload...???

In theory I should be able to use the Repeat Regions and add multiple records such as a list of cars each with it's own data and picture but I've had zero luck with this thus far...

Thanks in advance...!!!

**Comment by survey123** [comment]
@clrogers 
Most of the time the 400 error is caused by a time-out in the server. In the last update we included logic to reduce the size of photos by default (as a survey owner you can control the reduction, if any). See details here: https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release 
We continue working to resolve completely the 400 error. Will update again in May, but the latest release (1.3.38 of the app) should be much better.
We also enhanced the table view (Data tab) in the survey123 web site so you can see your photos (multiple) when clicking on a feature (row in the table).
