### ISSUE TITLE
select_multiple and more than one "relevant" choices

### ISSUE THREAD

**Issue by bcgisjosh** [Esri/Survey123Community#214]
I was testing out the "relevant" with the select_multiple as seen on the xls help with this example: selected(${favorite_topping}, 'cheese')

it worked perfectly the first time I tried it. I have a selection of languages. If the user picks one language a new question will pop up. This worked for me.

But I want to add a second question if another language is also chosen. This one does not work for me even though I copied/pasted the syntax and double checked for spelling errors in my list names. 

is this functionality possible? 
my excel sheet is here: ftp://ftpgeobc.nrs.bcgov/pub/outgoing/GeoBC_Regional/Coast/survey123/

**Comment by abrazell** [comment]
Not sure if this will help, but when I have copied text from help pages, there are sometimes curly quote marks instead of the straight quotes, this will cause an error.

**Comment by bcgisjosh** [comment]
the example uses curly brackets around the item name. I think that's a Survey123 convention as it's used in many examples on the xls help page (http://survey123.esri.com/resources/XLSFormSupport/#relevant)
