### ISSUE TITLE
Cascading Selects data not being saved to output data table

### ISSUE THREAD

**Issue by simontheguide** [Esri/Survey123Community#215]
Hi there,

I implemented a cascading select type question on my survey form. these questions display well and appear to be working properly in the Survey123 Connect and on the Survey123 app. However after submitting my surveys and looking at the feature service attributes on ArcGIS Online, the question answers are not being saved to the attribute table (only those questions that have cascading selects are not being saved - all other data is okay).

Any suggestions as to why this maybe?

Thanks,
Simon

**Comment by survey123** [comment]
Simon,
This is not something we have seen before - would you be able to provide your form spreadsheet so that we can reproduce this behavior?

**Comment by simontheguide** [comment]
Hi,

Thank you for looking into this for me. I have attached the xform spreadsheet in which I have a series of cascading select questions for rivers/lakes and selected countries, regions, and cities – for this one only new Zealand areas lead to the cascade down to the city. It is not a complete list but this how it is meant to be. I’ve included the folder so that the images are also included when you open the survey.

Cheers,

**Comment by simontheguide** [comment]
Hi there,

I think you can close this error message as the data that gets downloaded in the file geodatabase shows in the attribute table.

[cid:image002.png@01D111AD.41842A10][cid:image003.png@01D111AD.E06F4CE0]

What is really strange about this however, is that the data shows in the attribute window in ArcGIS online but does not get added to the attribute table. Everything that has lake or river or new Zealand as a city should be populated with values but where are they in the table in ArcGIS online?

I guess it doesn’t really matter as long as the data is there when I download the geodatabase.


[cid:image001.png@01D111AC.67879180]

Cheers,
Simon Allard | GIS Analyst | Bay of Plenty Regional Council | New Zealand | Ph: 0800 884 881 Ext 8219 | Email: simon.allard@boprc.govt.nz<mailto:simon.allard@boprc.govt.nz>   Web: www.boprc.govt.nz<http://www.boprc.govt.nz/>

“Thriving together - mō te taiao, mō ngā tāngata”
Please consider the environment before printing this email

**Comment by simontheguide** [comment]
Issues was a false alarm.
