### ISSUE TITLE
Publish Form to Portal for ArcGIS Error

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/Survey123Community#217]
I am using Survey123 Connect to create and publish a form to my Portal.  I have not yet been successful.  The following error is received when I attempt to include a feature service in the settings:

![image](https://cloud.githubusercontent.com/assets/4732590/10614628/25353dea-7710-11e5-9db1-122c181a962c.png)

**Comment by survey123** [comment]
Hi,

 it looks like you have a folder in your Portal contents conflicting with the survey you want to publish. Try the following:
1) Log into your Portal and go to My Contents
2) Look for the Survey-Form 3 folder and delete it completely
3) Back in Survey123 Connect publish again
If you get an error, let us know what that is.
Check out this blog entry to make sure you have the minimum requirements for Portal for ArcGIS in place.

 Thanks!
