### ISSUE TITLE
Survery Forms after Connect update

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#218]
I downloaded the current version of Survey123 Connect.  When I create a new survey I now do not see the full heading options as prior?  They now stop after Column D, Hint?

![untitled](https://cloud.githubusercontent.com/assets/14116002/10620261/0eebc490-7748-11e5-8e83-b1f93c5715ff.png)

**Comment by survey123** [comment]
The spreadsheet with the full XForm specification included is now under 'Template'. This simplified version is the 'Basic Form'. Sorry for changing things up on you, but there was demand for a less intimidating version of the spreadsheet for Survey123 newcomers.

![initial](https://cloud.githubusercontent.com/assets/10968332/10627271/19449550-7803-11e5-8c6f-8d0f0cb91f32.PNG)
