### ISSUE TITLE
Cascading Selects (choice filters) are not working

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#22]
I tried using this sample form:

https://docs.google.com/spreadsheet/ccc?key=0AjZ4hMHTat-YdFVpOWVBVWREUGdNVWZKbUl2akhfWkE&usp=sharing

This spreadsheet should populate drop down boxes based on what is selected in previous boxes.  From XLSForm.org:

A lot of forms start out by asking the location of the respondent, with each location selection specifying what the subsequent location choices will be (e.g., state  » district » village). Instead of adding a select_one field for each location option, you can use cascade select. In order to use cascade selects, you will need to create a choice_filter column in your survey worksheet and add the location attribute columns in your choices worksheet.

I included this sample because it is fairly straightforward, but I have a more complicated one I am building with a customer if you are interested in that.  It is definitely critical functionality.

**Comment by sirws** [comment]
When I look here: http://survey123.esri.com/resources/XLSFormSupport/#cascade it appears that Cascading Selects should be working now.  I have been unable to get this working.

**Comment by survey123** [comment]
Fixed. Closing. 
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update
