### ISSUE TITLE
Survey123 Connect wont load new XLS forms

### ISSUE THREAD

**Issue by DSSSGeography** [Esri/Survey123Community#220]
Any time I try and create a new survey I get a Status Code: 503 error stating that Service Temporarily Unavailable. Message has been in place since before the weekend. 

![screen shot 2015-10-21 at 11 46 12 am](https://cloud.githubusercontent.com/assets/15234219/10641936/7063ba42-77e9-11e5-8df5-e1b8dc6b24dd.png)

**Comment by survey123** [comment]
Thanks to error reports we have been receiving, we were able to pinpoint the source of the problem. Thanks for helping us improve!

The latest version of Survey123 Connect for ArcGIS has been made available and includes a fix that will address the problem you observe.

For details please have a look at our blog: https://geonet.esri.com/groups/survey123/blog/2015/10/18/survey123-xls-form-conversion-service
