### ISSUE TITLE
Multiselect and relavency issue

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#221]
Ok so I am not sure if there is a logic statement to cover this but if you have a multiselect question and then want to have additional questions based on that multiselect is this possible?  Say you have 5 items, if 1 is a selection red then you show a questions relating to red then if selection is green you show a question relating to green, etc.  When you select multiple items the relevancy is based on all items selected so if you select red and green a relevancy question that says relevant = 'red' it will be seen as not relevant.  Is it possible to do a contains logic statement of some kind?

I know I can write up a string of logic statements to accomplish this but when you have 5+ items this gets very tedious.

**Comment by survey123** [comment]
Hi Ronald. Try this in your relevant column: 

  *selected(${needs},'Water')*

Your question will show if the Water choice is selected in the 'needs'  select_multiple question

**Comment by RKnepper3** [comment]
Perfect, thanks!
