### ISSUE TITLE
Date input mask

### ISSUE THREAD

**Issue by ctoledo-img-com-br** [Esri/Survey123Community#223]
I have a “Date of Birth” question and the available data input mask is not  friendly enough for the input, is it possible to change the date input mask? Is “no-calendar” appearance attribute on the roadmap?

**Comment by sirws** [comment]
+1

**Comment by survey123** [comment]
Implemented. Closing!
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
