### ISSUE TITLE
Relevancy and Required Fields

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#225]
Ok this is likely something I am just missing, I know this was reported as an issue and reported as completed.  I have the segment below and if you select no and try to submit I still get a message "You must make a selection".  If I change it to yes and fill out that section it works.

![capture](https://cloud.githubusercontent.com/assets/14116002/10675524/c162a44a-78ce-11e5-8807-cb68ce1822b8.PNG)

**Comment by RKnepper3** [comment]
ok I figured it out.  You can't just set a group to relevant if the items inside are required.  You need to set the relevancy to each item.  It would make more sense to also also a user to select an entire groups relevancy and if its not relevant then all the items within wouldn't be required

**Comment by survey123** [comment]
#78
