### ISSUE TITLE
Sent and Outbox Surveys Title Format

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#227]
I don't think there is currently but it would be nice for us to be able to define the Sent and Outbox Survey titles.  There might be a key field (like address, date, etc) that would be most relevant to a user when they want to review items in these lists that would make it easier to identify which survey they want easier.

**Comment by survey123** [comment]
Hi Ronald, you may want to have a look at this: https://geonet.esri.com/groups/survey123/blog/2015/08/23/understanding-the-instancename-setting

**Comment by RKnepper3** [comment]
Thanks, I forgot about that!
