### ISSUE TITLE
Code 1003 when submitting survey

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#228]
I swear I read somewhere that you can add multiple geopoints within a repeat since those are stored in a related table.  I had a survey that worked fine then I decided to try a variation which included a main geopoint and then the collection of geopoints within a repeat for collecting related items.  It published fine and opened fine.  I filled out everything then submitted.  It never goes and ends up with a Send Error due to Code 1003 Operation Rolled Back.  Not sure what that might be referring to?

**Comment by survey123** [comment]
Check #212 
Be aware that only ONE geopoint question is allowed within a repeat.
Multiple repeats each with one geopoint question are allowed.
You can also place a maximum of ONE geopoint question outside the repeat blocks.

**Comment by RKnepper3** [comment]
ok, that is my issue then.  I will say that allowing a single geopoint inside a repeat kinda defeats the purpose of a repeat.
