### ISSUE TITLE
Share Dialog in survey123 web app needs scrolling

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#23]
See image:

![image](https://cloud.githubusercontent.com/assets/793576/6453550/fdba082c-c0f3-11e4-80b8-46f7fb7dfd68.png)

**Comment by survey123** [comment]
Thanks Scott. Will work on this. Expect fix by beginning of April.

**Comment by sathyaprasad** [comment]
Please test and let us know

**Comment by sathyaprasad** [comment]
@sirws Can you please test this issue and let us know if the fix is fine. Thanks!

**Comment by Cintruenigo** [comment]
@sathyaprasad 
Things get nasty starting at 10 groups. Notice how the link is pushed down.
Begs for a scrolling control?

![untitled](https://cloud.githubusercontent.com/assets/1273440/7016074/d9ee5a14-dc92-11e4-81da-43901dc846d8.png)

**Comment by sirws** [comment]
Still doesn't work for me...
![image](https://cloud.githubusercontent.com/assets/793576/7016884/25d74642-dca3-11e4-8d0f-b363997fa9d6.png)

Definitely need a scrolling control..

**Comment by sathyaprasad** [comment]
@sirws  @Cintruenigo Please refresh your browser and let me know if you are seeing it.

**Comment by sirws** [comment]
That works much better.
