### ISSUE TITLE
Selection list not showing correctly

### ISSUE THREAD

**Issue by jameseb** [Esri/Survey123Community#231]
The plant species list selection list I have very long, but doesn't show any of the selection options. This list is about 2500 selections. This is completed using an external sheet, and one selection set work perfectly while the other doesn't even show.

![10-29-2015 10-55-59 am](https://cloud.githubusercontent.com/assets/3534809/10827364/b143ca1e-7e2b-11e5-846d-828607c47b0d.jpg)

**Comment by survey123** [comment]
Please check your expressions in the _choice_filter_ column. This could explain the difference in behavior. Also, can you check for special characters in your lists?

Also, please make sure you are using the latest version of Survey123 Connect. 

Let me know how it goes,

Hannah
