### ISSUE TITLE
Code 400

### ISSUE THREAD

**Issue by skozlowicz** [Esri/Survey123Community#232]
Hi All-

I keep getting a code 400 when trying to send my completed survey.  I search "code 400" and it seems most people have the problem when a picture or lat/long point is collected within the survey.  So, just to get things moving, I took those out of my survey and it still is giving me Code 400.  I do have a repeat option in my survey, could that be the problem?

**Comment by survey123** [comment]
Could you please send your xls form to survey123@esri.com?

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
