### ISSUE TITLE
Calculations not working in repeats

### ISSUE THREAD

**Issue by MariannaC** [Esri/Survey123Community#233]
Hi,

I've been trying to perform a calculation (a simple addition of a few fields) which is then displayed to the user in a read only field. I can get this to work in the form, but not within a repeat. The fields that are inputs to the calculation, as well as the field displaying the result, are all within the repeat table. The 'result' field remains blank when the input fields are populated with numbers.

Thanks,
Marianna

**Comment by survey123** [comment]
Hi Marianna, this is a known limitation at the moment. We will be updating the Survey123 App to fix this limitation.

**Comment by mcjames76** [comment]
We are also looking for this functionality.  Any hints on when to expect the update with this fix?

**Comment by survey123** [comment]
Hi. We will try to define a target milestone for this issue around November 11. The milestone will define the expected delivery date for the fix.

**Comment by simontheguide** [comment]
Hi. I have recently been trying to implement a calculation within a repeat with no avail. I tried it the same question construct outside of the repeat and it worked fine. I am happy to know that others have also had this issue. 

Cheers,
Simon

**Comment by ltkaknm** [comment]
Hi,

I would also like to use calculations to concatenate some text fields into a new field within a repeat.  I checked an earlier post with the issue of calculations and the xlsform info does not contain info on how to concatenate text fields.  This would be very helpful.  Thanks!

**Comment by colgateg** [comment]
While you are working on this, it would be _extremely helpful_ if a calculate could also be used on the outside of a repeat. We want a form that can to record multiple individual lengths of pipe, calculate their individual allowable leakage (inside the repeat), and calculate the sum total of all allowable leakage for the group (outside the repeat).

![image](https://cloud.githubusercontent.com/assets/17730847/14469477/ac4b4c6c-0099-11e6-8abc-3da8c21fe581.png)

**Comment by survey123** [comment]
@MariannaC 
@ltkaknm 
@mcjames76 
@MariannaC 

Hi All, a fix to this in on the works. If any of you would be so kind to help us test the daily build before we make the fix final we would highly appreciate it.   If you would like to participate, send us an email to survey123@esri.com referencing this issue. Our plan is to make the fix available in mid-May, but we are looking for extra testing outside the core dev team.

**Comment by simontheguide** [comment]
I would be keen to test it but what version of survey123 connect/survey123 app am I supposed to use for testing. I would have to do this outside of my regular work day but would be keen to test this feature as I think it is something that would be really useful to implement.

Cheers,

Simon Allard | GIS Analyst | Bay of Plenty Regional Council | New Zealand | Ph: 0800 884 881 Ext 8219 | Email: simon.allard@boprc.govt.nz<mailto:simon.allard@boprc.govt.nz>   Web: www.boprc.govt.nz<http://www.boprc.govt.nz/>

“Thriving together - mō te taiao, mō ngā tāngata”
Please consider the environment before printing this email

**Comment by survey123** [comment]
Fix now available.

Connect download available at: http://doc.arcgis.com/en/survey123/download/
You will also need the latest version of the Survey123 field app (1.4.28)

Thanks to all for your feedback.
