### ISSUE TITLE
Slow Survey Load Times

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#234]
I was wondering what effects survey load times?  I have a survey downloaded onto a device already.  On wifi it loads up pretty quick, maybe 5-10 seconds, but when I am on a data plan or have no access it can take 30-60 seconds to create a new survey.  What causes this?  If there are changes that can be made on design to increase load times I'd like to know. 
I feel like if you are using it offline it should be pretty quick after the initial download. 

Also I am not sure if it is related to the slow response times but the app seems to randomly crash (and loose the data you were working on).  Not often but maybe once every 10 surveys and only on Android.  we had 2 different android devices report this.  IOS is always stable.

**Comment by spado** [comment]
This is a major problem for me too.  I made a couple of large surveys and they take about a minute to load on my phone.  I distributed them to people who work for me and they all started complaining that the surveys were taking over 10mins to load.   

What effects survey load times and what can I do to increase performance

**Comment by SonomaLandTrust** [comment]
I am also having significant load times that went from a few seconds to 3-5 minutes per form.

Aside from obvious things such as reducing image or media, how can I optimize this as this problem is becoming a deal breaker for adopters.

**Comment by survey123** [comment]
We are working on this. We are planning an update around February 15 to improve performance.
In the meantime, if you like we could have a look at your form and give you some tips. You can share the form with us by dragging and dropping your xlsx file in a comment here, or emailing directly to survey123@esri.com.
As we work on performance improvements, we will look into slow forms you share with us to validate progress.

**Comment by survey123** [comment]
Closing issue. Survey123 app has been updated in the Google Play and Apple stores with a fix that incudes performance improvements.  Version number is 1.2.49
We will update Connect and the Mac and Windows flavors of the app in the next few days.

Thanks to all of you that shared Forms with us. They were very useful.

@RKnepper3  
@spado 
@SonomaLandTrust 
@travisbutcher

**Comment by RooPitt** [comment]
Thank you! Before the update my survey was taking over 1 min 30 seconds to load (which feels like a long time when you're standing in the sun next to a busy road). Just tested it and it's now coming in under 20 second. Hooray!

**Comment by nicsi76** [comment]
I am not happy with 20 seconds loading time. I will send you my form to have a look at it. I used external choices to improve the loading time but maybe the data that is still in the choices table is still too much.
