### ISSUE TITLE
Date - Year appearance

### ISSUE THREAD

**Issue by danielhirner** [Esri/Survey123Community#235]
Do you know when Year will be added as an appearance attribute to the question type date.  I would like to restrict the user to only enter a year value.  

Thanks!

Dan

**Comment by HannahFerrier** [comment]
We intend to support both year and month-year appearance calendar widgets. This is already on our to-do list, but there is no firm delivery date yet. I will keep you posted :)

**Comment by survey123** [comment]
@danielhirner 
We will try to get this in our International Women's Day release (around March 8).

**Comment by survey123** [comment]
Implemented. Closing.
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
