### ISSUE TITLE
Select Boxes Resizing 2x 3x 4x Normal Size

### ISSUE THREAD

**Issue by clrogers** [Esri/Survey123Community#236]
I have a Survey that's been working just fine though now it's starting to throw errors and when I tried to look at it in the Survey123 Connect the Select Boxes in the select_multiple are resizing themselves automatically 2x 3x 4x or bigger than normal... what has happened to these controls...???

![newissuessurvey123-selectmultiitems](https://cloud.githubusercontent.com/assets/12275464/11048906/2960b82c-8700-11e5-935c-6628697201c5.png)

Thanks in advance,
Chris

**Comment by survey123** [comment]
Have you recently updated either Survey123 or your operating system?
Could you please screenshot the error messages you are receiving?

The check-boxes are re-sizing to stay at the same height as the text. As the text runs over two lines, the check boxes are also adjusting to be two lines high (and because they are square - two lines wide). I will log this as a bug with the development team to make sure that the check-boxes always remain single line height.

**Comment by clrogers** [comment]
Yes this happens in the previous 1.1.018 and the current 1.1.018 version of Survey123 Connect but didn't appear to be happening in version prior to those two... 

There are similar anomalies when viewing it in Survey123 Ver 1.1.16... 

The Error that began showing up is "CODE 1000 - String or binary data would be truncated" when our folks try to enter and upload data using the Survey123 we created, this began without warning...

I updated our Survey123 Connect to see if there was an issue there but Survey123 Connect 1.1.019 nor Survey123 1.1.16 fixed either of these two issues... 

I agree with you and believe that the Check Boxes should always be a standard one line high and wide and should not grow with the text "Fixed Size"...

Also when upgrading from one version to the next what is the best way to deal with previous versions while retaining any previously built Survey's... Thanks in advance...!!!

**Comment by clrogers** [comment]
One other thing that would be an awesome capability is to be able to define how many rows/columns a Survey has per Multiple Select region... that way if the titles/labels for each one is a little larger/longer each designer can determine the best fit and/or design...

**Comment by RKnepper3** [comment]
I ran into this as well, from what I remember this was only an issue via connect.  I think on the actual app it was fine

**Comment by clrogers** [comment]
Thanks RKnepper3 I'll check that out on my end and see if I can confirm same on my end,

**Comment by clrogers** [comment]
Confirmed it appears only in the Connect but is very bad depending on the length of text associated with the checkbox.

**Comment by clrogers** [comment]
Ooops I spoke too soon... It looks like the problem is now showing in Survey123 on the Desktop Windows version... The fix will be most welcome when it comes...!!!
