### ISSUE TITLE
Default value for time not working using now()

### ISSUE THREAD

**Issue by travisbutcher** [Esri/Survey123Community#238]
I am setting a time field with a default value of now().  In the form it is populating the value as a string not as the time:
xlsForm Entry
![image](https://cloud.githubusercontent.com/assets/1291442/11076371/e192fc06-87a6-11e5-8048-5cdaf2d0ffdd.png)
Form Entry
![image](https://cloud.githubusercontent.com/assets/1291442/11076385/f436d8c8-87a6-11e5-8552-f154acf95016.png)

**Comment by survey123** [comment]
Thanks @travisbutcher 
This is in our radar.
We would like to address this issue along with display enhancement requests to the Time question type.
Thanks for posting.

**Comment by SonomaLandTrust** [comment]
I am still seeing this as a problem and want to suggest that if time math is not part of calculation functions, then this would be an opportune time to add them.

**Comment by cconnolly91** [comment]
+1 vote for this as well!

**Comment by pbond-idfg** [comment]
+1

**Comment by Marie-Lou** [comment]
+1 vote for this as well!

**Comment by RooPitt** [comment]
+1

**Comment by survey123** [comment]
Closing issue. Thanks a lot for your feedback.
Implemented in the International Women's Release
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release 
Now() works with Time and Date.
