### ISSUE TITLE
Unable to take picture when collecting a survey 

### ISSUE THREAD

**Issue by lem19** [Esri/Survey123Community#24]
When collecting the survey, unable to capture a new picture when pressing/clicking the photo icon. Tried on both a Lenovo S850 834 tablet and a Motorola Droid phone. The icon highlights as if it has been selected, but then nothing happens.

![lenovo](https://cloud.githubusercontent.com/assets/8391360/6475873/536b85ae-c1c4-11e4-9157-54acf8a33764.png)

![screenshot_2015-03-03-16-35-37](https://cloud.githubusercontent.com/assets/8391360/6476063/2f0088a2-c1c6-11e4-9271-67dd64988c9f.png)

Able to upload photos in the same question.

**Comment by survey123** [comment]
Thanks, will look into this.

**Comment by survey123** [comment]
Please try again with the latest release of Survey123. When you load your .xlsx into Survey123 Connect, the image fields should have the _esritype_ of _attachment_ in the schema preview. After publishing the feature service, photographs will be able to be added to features as attachments.

**Comment by survey123** [comment]
@lem19 
Please download app from [Google Play store](https://play.google.com/store/apps/details?id=com.esri.survey123). This should be working now. Looking for your validation.
