### ISSUE TITLE
Issues with DATE fields

### ISSUE THREAD

**Issue by ericvanpraag** [Esri/Survey123Community#242]
Dates can’t be edited and the date entry table only allows you to move month by month, quite cumbersome. Is there another way to enter an “old” date, for example, if a company was created in June 1st, 1960? Otherwise, we might need to enter dates as text fields.

**Comment by sirws** [comment]
+1

**Comment by survey123** [comment]
Closing
You can now change years and months.
Tap and hold to move quickly!
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
