### ISSUE TITLE
Survey123 for Surface 3 (Windows 10) & Question re: Collector 

### ISSUE THREAD

**Issue by Nick-Shannon** [Esri/Survey123Community#244]
Three questions:

1.  Is there a PC version of the Survey123 app for a Microsoft Surface?  I see there's an app for Windows Mobile devices https://www.microsoft.com/en-us/store/apps/survey123-for-arcgis/9nblggh5wmrr

2.  I downloaded the Survey123 app on an iPad.  I get this error:  Please connect to a network to get started.  http://i.imgur.com/V7dNTO6.jpg  
The iPad has a mobile connection to a network.  Any ideas on how to fix it..? 

3.  Re: Collector for ArcGIS. 
I've added domains to a Geodatabase to enable drop down menus. 
Is it possible to configure the GDB to support dynamic/condition drop down menus?  
For example... http://i.imgur.com/90eMfqh.jpg  (please excused my quickly drawn diagram).  

I've played around with sub-types, but that only goes down one level.. Could I create a form in Survey123 that would meet my needs..?

Thanks for your help.

**Comment by survey123** [comment]
1- Temporarily, you can download the app on your Surface Pro from [here](http://esriapl.blob.core.windows.net/survey123/Survey123-Setup-x86.exe). We will add the link in the web site.
2- It looks like you never logged in and downloaded surveys before you took your iPad offline. Please ensure your iPad has an internet connection, then login and download a survey, then you can go offline and capture data.
3- Subtypes and domains only allow you do do what you want with one dropdown. In Survey123 for ArcGIS you can use Cascading Selects to chain as many dropdowns as you want. Check this [blog post for details](https://geonet.esri.com/groups/survey123/blog/2015/10/22/cascading-selects-and-external-selects).

**Comment by Nick-Shannon** [comment]
1 - Excellent. Thanks for the download link for the Surface Pro. 
2 - Okay. Give that a try tomorrow morning. 
3 - A colleague suggested created related tables in my Geodatabase for the condition reports... 
something like what is described here... http://blogs.esri.com/esri/arcgis/2015/02/18/related-tables-exploring-new-ways-to-use-collector-for-arcgis/ 
But I'm not sure if this will do what I want in the collector app. 

Either way, I'm will continue to experiment with both the Collector App & Survey123.

**Comment by survey123** [comment]
@Nick-Shannon 
1- We have now updated the survey123 web site at http://survey123.arcgis.com so you can download the app into your Surface Pro directly from there. Simply scroll down and you will find the links.

3- The way you do things in Collector and Survey is opposite. In Collector you first create the geodatabase schema, and then Collector interprets it. In Survey123 you first define what questions will pop in your app, and Survey123 Connect creates the feature service for you. Related tables are used if needed. For example, if you create a repeat, a related table will pop.

Closing issue.
