### ISSUE TITLE
menu bar missing options

### ISSUE THREAD

**Issue by spado** [Esri/Survey123Community#245]
On one of my devices the menu bar wont allow me to sign-in/out or download surveys.  It was ok yesterday when I downloaded some surveys, but now I'm stuck.

I've tried closing it down and starting it up again, but nothing seems to work.  As you can see from the attached picture, it only gives me the option to see the 'settings' or 'about'
![img_0361](https://cloud.githubusercontent.com/assets/15007800/11330257/28364bb8-91fc-11e5-909e-f2e3d9844720.JPG)
Any help is greatly appreciated

**Comment by survey123** [comment]
This is because your device is not connected to the internet. The options to sign in/out and download surveys are only available with an internet connection.

Hope this helps!
