### ISSUE TITLE
Update Feature Service when republishing survey

### ISSUE THREAD

**Issue by katyushak** [Esri/Survey123Community#246]
When a survey is republished, the existing feature service is deleted and a new one is created. This means any web map (and consequently app) referencing it now has a broken link. 

It would be beneficial to provide an option to overwrite (rather than delete and recreate) the service, so that apps (like Operations Dashboard, for example) continue to reference the (updated) service.

**Comment by travisbutcher** [comment]
:+1: We have many people that are interested in being able to link to the content in the Surveys but when a change breaks the links it is problematic.

**Comment by scoxisda** [comment]
+1

**Comment by clrogers** [comment]
+2

**Comment by cconnolly91** [comment]
+1

**Comment by pbond-idfg** [comment]
+1

**Comment by nicsi76** [comment]
+1
It would also be better if in the app there would be an "update" instead of downloading the survey again.

**Comment by kmsternhagen** [comment]
+1
I agree. We use the feature service service URL to pull the data into SQL, but it breaks every time we  make a change to a survey and republish.

**Comment by sunyu0530** [comment]
+1

**Comment by survey123** [comment]
Thanks to ALL for your feedback on this. 
We will bring some enhancements to this in our next update.
Survey123 Connect for ArcGIS will at 1.4.x look at the Survey and see if the underlying feature service can support the modifications to your Survey. If so, we will no longer delete the feature service, but just the Form.   Only if changes to the Form are made that require changes in the Feature Service, we will re-create the Feature Service.

**Comment by survey123** [comment]
Check out the latest version of Connect (1.4.30) and the App (1.4.28). You will now be able to change lots of things without having your Feature Service replaced: the title, description, summary, thumbnail, image size threshold, style, map properties as well as any label, grouping, media, calculations, constraints, defaults etc Only your changes to the survey require a feature service schema change, we will replace the feature service. 

Latest Connect available at: http://doc.arcgis.com/en/survey123/download/
App update available in the app stores.
