### ISSUE TITLE
Survey123 Beta - Cant add images from Camera Roll

### ISSUE THREAD

**Issue by jplunkett1** [Esri/Survey123Community#247]
Hi there
There appears to be an issue

I use
Image in type
This loads successfully in the survey giving me the choice of taking a new photo or adding a file

If I take a photo and add it directly to the survey it uploads

However if I select the browse to the camera roll, the photo loads however when I sync back to the server it fails

I get  Code 400

iPhone5S
iOs 9.1

Fails over 3G and Wifi

All other syncs work correctly

Thanks
John P
jfp@eagle.co.nz

**Comment by survey123** [comment]
Hi John. Thanks for your feedback. This is a known issue. Images from your camera roll are significantly bigger than the previews you capture with the camera. Large images fail to post.
We have plans to address this issue by allowing you to control the size of the images to be submitted.

**Comment by jplunkett1** [comment]
Thanks, this issue might also be related to the image size

Samsung S4mini: 4.4.2
Samsung S5 active: 5.0

These devices are having issues, we are taking photos off the camera and these fail to upload as well.

**Comment by jplunkett1** [comment]
Adding another device, when selecting the option for using the camera roll on 
Samsung Galaxy S2 – GT-I9100

Android 4.1.2 build JZO54K.I9100XMLSD

The camera folder is blank even though there are photos in it.

Cheers
John

**Comment by AndyMuma** [comment]
Hi  has this issue been fixed.  I am still getting the error when I attach a photo from my camera roll with survey 123

**Comment by survey123** [comment]
Hi @AndyMuma    Not yet. Still in the queue.

**Comment by survey123** [comment]
@AndyMuma 
@jplunkett1 
We were able to fix this issue in our internal builds. The fix is ongoing certification and will be made available in the stores around mid April.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
