### ISSUE TITLE
Navigation icons are too small and hard to select on Android 5.0

### ISSUE THREAD

**Issue by dfabulic** [Esri/Survey123Community#25]
See the screenshot. Device is Moto X 2nd gen, screen resolution 1080x1920, 424 ppi. The problem is not only aesthetic, but usability too: I'm frequently (somewhat randomly) unable to select navigation icon. (By navigation icons I mean icons near the corners of the screen: cancel, settings, submit, and the orange one)

![screenshot_2015-03-05-09-58-03](https://cloud.githubusercontent.com/assets/4203274/6507493/4f035282-c320-11e4-9426-5e2a064c3d64.png)

**Comment by survey123** [comment]
Thanks Dominik. Working on it.

**Comment by survey123** [comment]
Fix coming in on March 9. Please download the Survey123 App and try again then. Thanks!

**Comment by survey123** [comment]
@dfabulic  Let us know if this is looking good now.
Updated Survey123 on March 18 again.
Ready to close when you confirm this is fixed.

**Comment by survey123** [comment]
Closing
