### ISSUE TITLE
Form with 'Repeats' gives Code:500 error 

### ISSUE THREAD

**Issue by nitinmv** [Esri/Survey123Community#256]
When publishing forms with 'Repeats' gives Publishing Error in Portal - 
 Code:500 []  JSONObject["name"] not found. 

Sample form
http://survey123.maps.arcgis.com/sharing/rest/content/items/e5b142547ae14b488f0b5d38e5dd718b/data

**Comment by HannahFerrier** [comment]
Can you please let us know which versions of Survey123 and Portal for ArcGIS you are using?

**Comment by nitinmv** [comment]
Hi, 

Publishing using the default settings in Survey123 Connect Ver. 1.1.19. The Portal for ArcGIS is Ver 10.3.1.  

Thanks, 
Nitin

**Comment by bowlesgsrcx** [comment]
I am getting the same error. Portal is 10.3.1, Survey123 Connect (Beta) 1.2.12

Thanks,
--gary

[SWS.xlsx](https://github.com/Esri/Survey123Community/files/89440/SWS.xlsx)

**Comment by survey123** [comment]
Hi. This issue is fixed in Portal for ArcGIS 10.4
Portal for ArcGIS 10.4 is planned to be made available in a couple of days.

Closing. Please note this issue is not currently fixed in Portal for ArcGIS 10.3.1
