### ISSUE TITLE
Date with Timestamp?

### ISSUE THREAD

**Issue by trentmaceachern** [Esri/Survey123Community#257]
I've got a date field that looks normal when accessed through Survey123, but when I view the results through the query REST endpoint in ArcGIS online, all the dates are appended with 4:00:00 AM. 

Advice?

Thanks,
Jody

**Comment by insect1285** [comment]
My Guess is you are in the GMT+0400 timezone.  All Dates are stored with midnight by the base time, then with the GMT timezone change that puts it at 4 AM on the server.  This is common among databases - to remedy the server would have to read-out or save as UTC time.
