### ISSUE TITLE
iPhone App ignores relevant setting

### ISSUE THREAD

**Issue by insect1285** [Esri/Survey123Community#258]
I designed a survey with a select_one [list] and several child fields that only show when a "relevant" option from the list is chosen (e.g., selected(${list1},'something') or ${list1}='something')

This functionality works great in the Survey123ConnectBeta and the Survey123 on PC, works in Android 5.X and 6.X, but does not work on any iPhone version.

The only option was to not use the relevant field and to show everything all the time - which is impractical for the forms I'm developing.

**Comment by survey123** [comment]
Could you please confirm the version of the mobile app you have?
You can tell by going into the About section in the app.
Please also let us know the Survey123 Connect version number.

 Thanks

**Comment by insect1285** [comment]
iPhone and Android App: 1.1.18
Survey123ConnectBeta: 1.1.30
Survey123 (PC): 1.1.18

I've also attached the XLSX template I've used to generate the form in Survey123ConnectBeta so you can look into the possibility I've mis-configured.

[Boone Dam Manual Measurements.xlsx](https://github.com/Esri/Survey123Community/files/64642/Boone.Dam.Manual.Measurements.xlsx)

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The use of relevant statements on iOS was fixed in the August (1.7) release.
