### ISSUE TITLE
Calendar widget does not minimize after a date is selected (Android 5)

### ISSUE THREAD

**Issue by dfabulic** [Esri/Survey123Community#26]
When user selects input field of type date, a calendar widget pops up taking most of the screen. After user selects a date on the calendar the widget does not minimize (as it is common in web and Windows UI) but stays on the screen. User has to scroll pass the widget (possibly inadvertently selecting a different date) to tap on the next field to minimize the calendar. After the calendar minimizes the rest of the fields move up, and the field that user just taped on and selected is out of the screen.
![screenshot_2015-03-05-10-18-42](https://cloud.githubusercontent.com/assets/4203274/6507699/db2f9526-c321-11e4-953d-120ac6623bf2.png)

**Comment by survey123** [comment]
Thanks. We will look into this.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. 
@dfabulic
