### ISSUE TITLE
Unable to upload completed forms – 'code 400' error

### ISSUE THREAD

**Issue by djibo** [Esri/Survey123Community#263]
Our group of data collectors in Senegal has been working with a number of surveys, and can upload all of them fine, but one survey in particular won't upload for any of them, simply showing a 'code 400' error. When I upload it from my phone in the US it works without any issues.

This is an urgent issue, so if anyone has any solutions or ideas to try, please advise! They tried updating the form on their phones, in case not having the newest version was the issue, but this didn't help.

**Comment by travisbutcher** [comment]
Do the forms you are posted contain photos?  This may be that the form can not send the photo over the internet connection available in Senegal while your connection in the US is capable.  
Please see other issues related to the 400 error:  https://github.com/Esri/Survey123Community/search?q=400&type=Issues&utf8=✓

**Comment by djibo** [comment]
Thanks for the tip Travis. There aren't any attachment options in the survey though – just integer, select_one, notes, and text. It's actually a pretty straightforward survey, and the only other formatting used are groups, relevant clauses, constraints, and compact appearance for the select_one questions.

Looking over the typical 400 issues, it seems like data is usually sent, but it times out at a certain point due to slow upload connections. Given that we've got dozens of people trying to upload the form multiple times – and apparently the problem has been occurring since late November – we should at least see partial uploads from a number of people. Instead, all I see are the two uploads I tried from my phone yesterday and today.

Aside from location, the only differences I can think of are that they're likely all using Android phones, and I'm using an iPhone, and that we're using different accounts.

Any additional thoughts?

**Comment by djibo** [comment]
I'd be happy to send the form if it helps...

**Comment by Marie-Lou** [comment]
I'm getting the Code 400 error when I compete a survey out in the field, submit it to send later.  When I move to a different location (the office), open that survey to edit it, and try to submit & send it, the Code 400 error pops up.  It looks as though the form gets confused between the different locations.....

When I complete the survey in the field, and submit & send it from that location, I can open Sent, edit the survey in the office, and submit & send it without any problem. If I'm out of signal range, I can submit to send later, and then submit and send when I have a 3G/WiFi signal - as long as I don't try and open the survey and edit it before it has been sent....

**Comment by RooPitt** [comment]
We're getting a code 400 error when people attach a photo in the app, rather than take it in the app. Taking a photo using the app is okay - sometimes slow to upload if wifi is poor, but usually goes through eventually. But if the photo is taken with the camera and then attached it will not send, even in good wifi.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
