### ISSUE TITLE
Method to choose a date need improvements in Survey123 App

### ISSUE THREAD

**Issue by vtran3** [Esri/Survey123Community#264]
The Date field in Survey123 App automatically picks the current date on the calendar (ex. 01/06/2016). However, I tried to choose a date back in 1989 (for a birthday question), I'd have to push back through all the months and the years. It took a long time. It'd be better if the app let me choose year separately from month and date (i.e. I can scroll from 2016 back to 1989, then pick the month in 1989, and then pick the date).

Please fix this in your app.

**Comment by survey123** [comment]
Thanks for your comment. This request makes a lot of sense. We will keep this in our back-log for a future update.

**Comment by sirws** [comment]
+1

**Comment by survey123** [comment]
Thanks @vtran3  and @sirws  for your feedback.
We just pushed 1.2.82 into the app stores. This new build brings a new enhanced calendar widget. Give it a try. We hope you like it.
Closing issue.
