### ISSUE TITLE
Tooltip misspelling

### ISSUE THREAD

**Issue by str8wak** [Esri/Survey123Community#266]
When hovering over "Update Survey from XSLForm Spreadsheet", the tooltip that pops up has spreadsheets misspelled.
![spellingerror](https://cloud.githubusercontent.com/assets/7143064/12175043/a5222d30-b525-11e5-9c87-0c2f34845499.png)

**Comment by survey123** [comment]
Thanks Tim!
Will keep this in mind for the next Connect update.
