### ISSUE TITLE
Coded value domains are not created for select_one field

### ISSUE THREAD

**Issue by dfabulic** [Esri/Survey123Community#27]
My understanding is that Survey123 connect should create a geodatabase coded domain for columns created for form fields of type select_one, and insert code/description for each choice name/label. That doesn't seem to be happening.

I created a simple form:
![image](https://cloud.githubusercontent.com/assets/4203274/6677670/9859c664-cc08-11e4-8b86-1df81c760cd8.png)

![image](https://cloud.githubusercontent.com/assets/4203274/6677677/b2748430-cc08-11e4-8805-4a413f439ac9.png)

Form fields are generated as expected:
![image](https://cloud.githubusercontent.com/assets/4203274/6677691/e3a41ad4-cc08-11e4-83a8-329d011354b3.png)

but created feature service does not have domains:
![image](https://cloud.githubusercontent.com/assets/4203274/6677721/1e419b4e-cc09-11e4-9531-a06c5e86ee4c.png)

I can provide source if needed.

Thanks!

**Comment by survey123** [comment]
Thanks Dominik. We will work on this.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Closing.
@dfabulic
