### ISSUE TITLE
Survey Title Length

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#270]
I am using the beta to publish to portal and have found that if my survey name is greater than 19 characters in length, it will not publish. I receive the following error
Code: 500
ERROR: Creating feature class failed

I created the exact same survey with names of 13, 17, 19, 20, & 23 characters. All of the surveys with less than 20 characters published fine, 20 & 23 did not.

I have attached 2 of the surveys (19 & 20) for review.

Thanks.
[XXXXXXX_XXXXX_XXXXX.xlsx](https://github.com/Esri/Survey123Community/files/89351/XXXXXXX_XXXXX_XXXXX.xlsx)
[XXXXXXX_XXXXX_XXXXXX.xlsx](https://github.com/Esri/Survey123Community/files/89352/XXXXXXX_XXXXX_XXXXXX.xlsx)

**Comment by survey123** [comment]
Hi Gary. We got this one fixed in Portal for ArcGIS 10.4.  If using Portal for ArcGIS 10.3.1, we will continue having this limitation.  Thanks for reporting.
