### ISSUE TITLE
Unable to sign in to ArcGIS Online with version 1.2.12

### ISSUE THREAD

**Issue by Marie-Lou** [Esri/Survey123Community#272]
I've replaced my older Survey123 installation with a newly downloaded one - version 1.2.12.  When I try to sign in to ArcGIS Online to publish a new survey, nothing happens.....

Marie-Lou

**Comment by Marie-Lou** [comment]
I've uninstalled the version 1.12.12, and re-installed version 1.0.158.  This version does allow me to sign into ArcGIS Online, but it complains that I have insufficient Client Privileges - which is nonsense, as I am a Publisher....

**Comment by HannahFerrier** [comment]
Hello Marie-Lou,

We introduced support for OAuth sign in between these versions.

When you say 'nothing happens...' when signing in with Survey123 1.2.12 - could you please be more specific?

What platform are you on? What exactly are you seeing when you sign in? Can you provide a screenshot please?

Thanks,
Hannah

**Comment by Marie-Lou** [comment]
I've added a word doc with the screenshots...

When I click on the "sign in" icon, it opens the window with the spinning timer, and then nothing happens - no option to add a username & password, just a blank sign in screen.... I even tried to add our ARC Online URL (second screenshot), but this didn't make any difference.

We're on Windows 7

[Unable to sign into AGOL - ver1.2.12.docx](https://github.com/Esri/Survey123Community/files/89689/Unable.to.sign.into.AGOL.-.ver1.2.12.docx)

**Comment by HannahFerrier** [comment]
Hello Marie-Lou,

We have been able to successfully sign into Survey123 using a Windows 7 machine - is there another Windows 7 machine in your office on which you can install Survey123? Or any other operating system?

Are you familiar with the application Fiddler? It allows you to monitor network traffic on your machine and could help to expose any network errors that are causing the login page not to load correctly.

Also, if I was to send you a test application to troubleshoot this issue, would you be able to install it on your machine?

Hannah

**Comment by Marie-Lou** [comment]
Hi Hannah

I've installed Survey123 on another Windows7 machine, and I still couldn't sign in on that computer - gave the same screen as on mine.  Installed Fiddler on my computer, and tried again to sign in from my computer (with Fiddler open to monitor the network traffic), and this time I got the sign in window!     

I signed in successfully and published the form I worked on.

Don't know what changed on my computer to make it work, but I still can't see the sign in window on the other Windows7 machine....

You're welcome to send me a test application to troubleshoot this - I can install it on the other computer that doesn't show the sign in....

Cheers!
Marie-Lou

**Comment by Marie-Lou** [comment]
I can only sign in when I have Fiddler open.  When I close Fiddler, I get the blank sign in screen again.  Weird, but at least I have a work-around.

Cheers!
ML

**Comment by HannahFerrier** [comment]
Hi Marie-Lou,

It looks like your work network is using a proxy, which Survey123 isn't handling correctly.  
Running Fiddler before launching Survey123 Connect will create a local proxy, which is why the sign-in page is now loading.

We will look into the proxy issues further and hopefully have an answer soon :)

Hannah

**Comment by jeskill** [comment]
Hi, 

I'm just adding this here instead of creating a new ticket because I think I'm having the same problem. I can type in my username and password but then it opens the window with the spinning timer and nothing happens. Running Fiddler did not help.  Mind you, I have absolutely no idea how to figure out what's a network error and what isn't using Fiddler. 

I'm on Windows 7 as well.

- Jes Skillman

**Comment by lcooper1** [comment]
I am having the same issue. Windows 7. Connect v 1.2.12. Running Fiddler did not help.

Thanks

**Comment by bikeboy888** [comment]
On Windows, you can review your proxy settings by going Control Panel > Internet Options > LAN Settings.

Note whether you have any of the following:
1. Automatically detect settings checked
2. Use automatic configuration script
3. Proxy server

Enterprise typically deploy proxy configuration via either methods 1 or 2 and not set option 3.

If you explicitly set a proxy server via option 3, Survey 123 has a chance in automatically detecting it and will configure itself to use it accordingly.

Fiddler is a implements a proxy server and automatically registers itself as option 3. By running Fiddler first, followed by Survey123, Survey123 will automatically detect Fiddler's settings and route traffic through it.

**Comment by Marie-Lou** [comment]
Our proxy configuration has method 1 AND 2 selected.
I selected option 3 also, as suggested, but this didn't have any effect, though - still can't sign into ArcGIS Online with Survey123...

**Comment by Marie-Lou** [comment]
I’ve updated Survey123ConnectBeta to Version 1.2.53, and Survey123 for Windows Desktop to Version 1.2.82, and I still can’t sign into ArcGIS Online – I get the following:
[cid:image001.jpg@01D179D3.A7847070]
The only way around is to change my proxy settings by going Control Panel > Internet Options>Connections > LAN Settings, and select the Proxy server….


Marie-Louise Labuschagne
Senior GIS Specialist

Hutt City Council, 531 High Street, Private Bag 31912, Lower Hutt 5040, New Zealand
T 04 570 6840, W www.huttcity.govt.nz<http://www.huttcity.govt.nz> F huttcitycouncil<http://www.facebook.com/huttcitycouncil>

[cid:hccsmalllogo_12fb0640-f486-4c5a-a775-f4ab1b1dfb5d.jpg]

[cid:LaingsRoad_Moving_Emailsignature1_60px_6e689b56-62a0-42d9-94fa-7f2433a8b305.jpg]

**Comment by survey123** [comment]
We've made a change in the 1.4 release of Survey123 to improve connections behind firewalls. Could you please try 1.4 out and let us if it works for you?

**Comment by Marie-Lou** [comment]
Perfect !   I've tried it this morning, and I had no problem signing in - thanks :smiley:
