### ISSUE TITLE
Code 500 Layer '0' does not exist

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#273]
I have a survey that was published to Portal (10.3.1) using Survey123 Connect Beta 1.2.12. When i complete a survey and try to upload it, i get the following error:
 
Code 500 Layer '0' does not exist.
 
Thanks for the help,
--gary

**Comment by survey123** [comment]
do you by any chance have two geopoint questions in the same form?

**Comment by bowlesgsrcx** [comment]
I have no geopoint questions in the survey. I republished the survey to portal and the error went away. Not sure why.

**Comment by survey123** [comment]
Thanks. Closing issue.
