### ISSUE TITLE
Displaying Date and Time

### ISSUE THREAD

**Issue by Marie-Lou** [Esri/Survey123Community#274]
1. Time not displaying in AGOL Map
When I add a time type to the XLS form, it show as hh:mm:ss on the published survey, but the data doesn’t display when this is opened with AGOL Map.  
The format in AGOL for the time field that doesn’t display, is Text.  When I compare it to another AGOL map that does display a time field correctly, the field format is Date/Time.
My current work around is to add a start and end, to grab the metadata  - this gives me the time the survey was done.

2.  Calendar for Date too large for smart phone display
The calendar for date selection is a bit too large on a smart phone (iPhone 6s), so it doesn’t display the year after long month names (January, February, September, October, November & December).  Partially display the year for March and August.  
The only months that displays without a problem is April, May, June & July.
Can the month be shortened, eg Jan, Feb, etc?
[Date and time field display errors.docx](https://github.com/Esri/Survey123Community/files/91221/Date.and.time.field.display.errors.docx)

**Comment by HannahFerrier** [comment]
Hello Marie-Lou,

In answer to your first question, the 'time' questions collected in Survey123 are saved as a string field in the resulting feature service (see the **Schema Preview* tab in Survey123 Connect). This is why your times are not displaying as expected in the ArcGIS Online Map popups. I was able to create a time question and bind the field type to use an esri date field. After collecting data, I was able to configure the popup in ArcGIS Online Map Viewer to display the time.

This is achieved by adding a column called **bind::esri:fieldType** and entering the value _esriFieldType Date_ for the time question. 

In answer to your second question, the display of the calendar widget is not scaling correctly on the iPhone 6s - I have raised this as an issue with the development team.

I hope this helps,

Hannah

**Comment by Marie-Lou** [comment]
Thanks for the help to display time in the ArcGIS Online Map Viewer pop-up.   I'll add the column and value to my XLS-form, but I have to wait until Monday morning to publish the data.

**Comment by Marie-Lou** [comment]
Hi Hannah
The Time question displays now that I've added the column & value, but I now have the following 3 niggles:
1.  In this format, the ArcGIS Online Map Viewer can only display the Date and the Time, not the Time without an accompanying date.  It grabs the date the survey was sent, and if this differs from the Date field chosen in the Calendar, the map displays two different dates.  
2.  The Time added in ArcGIS Online Map Viewer is Universal Time.  In other AGOL maps with published Feature Layers, I usually convert the time zone to New Zealand Time (and I factor in the Daylight Savings bit also) before I publish the layer.  
How do I deal with that in the Feature Layer Survey123 creates – I can’t open it in Arc Desktop and change the Time Zone….?
3.  If the user is lazy (and my users definitely are:)), and they enter the time as hh:ss  - the Time will not display in ArcGIS Online Map Viewer….

These are not show-stoppers, my users are more than impressed with the survey as it is, but displaying the Time correctly will look more professional.
[Time Field in UT.docx](https://github.com/Esri/Survey123Community/files/95076/Time.Field.in.UT.docx)

**Comment by cconnolly91** [comment]
Marie-Lou, I've also come across the issue where if users only enter the time as hh:ss - it will not be recorded in the attributes when sent to ArcGIS Online. It's quite a lot to ask users to record seconds as well!!

**Comment by survey123** [comment]
Hi @Marie-Lou   Please check this [blog post](https://geonet.esri.com/groups/survey123/blog/2016/04/17/dates-and-time-in-survey123-for-arcgis) and specifically the portion describing how to display time information in popups. Hope it helps. Closing issue.
