### ISSUE TITLE
Ver. 1.2.19 gives Error 400 

### ISSUE THREAD

**Issue by nitinmv** [Esri/Survey123Community#275]
Following upgrade to the latest release of Survey 123 (Ver. 1.2.19), gives Error 400 page upon login to Portal. Tested on both iOS and Android. The Portal is Ver.10.3.1.

Was able to login fine with the previous release.

![error400](https://cloud.githubusercontent.com/assets/15861898/12436586/7ac33f1a-bf7b-11e5-8d1e-3b135aa61cae.png)

**Comment by HannahFerrier** [comment]
The _client_id_ for the latest version of Survey123 will be available in Portal version 10.4. It will also be made available in an upcoming update for Portal 10.3.

Please continue to use the previous version of Survey123 until you are able to update your portal.

**Comment by nitinmv** [comment]
Hi Hannah, 

Do we have a timeline on when the new update of Survey 123 for Portal 10.3 would be available?

Only the latest version of the App is showing up on the Apple App Store / Google Play Store. Is there a way to revert to the older version?

Thanks, 
Nitin

**Comment by HannahFerrier** [comment]
I don't have a date yet - but keep an eye on this page (http://support.esri.com/en/downloads/patches-servicepacks/list/productid/207) for any Portal 10.3 Updates. 

But - Portal 10.4 Pre-Release is available now! (https://blogs.esri.com/esri/arcgis/2015/12/14/prerelease/)

I don't think there is a way to roll back using the respective app stores, but I am sure we can make older versions available to you if you contact Technical Support. 

Hope this helps,
Hannah

**Comment by nitinmv** [comment]
Thanks Hannah. Will check with the TS. 

Nitin

**Comment by HannahFerrier** [comment]
Please see the steps for updating Portal 10.3 to work with Survey123 here:

http://support.esri.com/en/knowledgebase/techarticles/detail/46252

- Hannah

**Comment by nitinmv** [comment]
This works now! Cheers. 
Nitin
