### ISSUE TITLE
500 Error Publishing Survey to Portal

### ISSUE THREAD

**Issue by nickoadl** [Esri/Survey123Community#276]
500 error is occurring when publishing to our Portal. The survey folder is created, along with the feature service, but the creation of the data / featureclass is failing.

I have administrator privileges. survey 123 version 1.1.30 portal version 10.3.1

http rest response - {“error”:{“code”:500, “message”:”ERROR: Creating feature class failed.”}}

![image](https://cloud.githubusercontent.com/assets/16811984/12472351/0cc401de-c057-11e5-8562-adf753eb98a1.png)

[request-response.txt](https://github.com/Esri/Survey123Community/files/100121/request-response.txt)

**Comment by survey123** [comment]
Please attach your xlsfile so we can have a look.
Thanks for reporting the issue.

**Comment by nickoadl** [comment]
Here is the xlsx.

[Fatality Site Inspection.xlsx](https://github.com/Esri/Survey123Community/files/100315/Fatality.Site.Inspection.xlsx)

**Comment by survey123** [comment]
@nickoadl 
Closing issue. 
Fixed with the International Women's Release.
Thanks a lot for reporting.
