### ISSUE TITLE
Location map is not working

### ISSUE THREAD

**Issue by bart-richardson** [Esri/Survey123Community#277]
The Location map is now showing "Map preview not available".  

The map function used work fine and since I haven't changed anything on the forms, I can't figure out why it stopped working.  I'm using Survey123 1.12.12 on an iPad and iPhone with the same result - the map doesn't work but the lat/longs coordinate numbers are shown in the header.

**Comment by survey123** [comment]
Hi,

 this is an unfortunate bug that we introduced in the last update of the field app in the iOS version. We submitted a fix to the Apple store that is waiting for approval. We expect Apple to approve this fix shortly.

**Comment by sirws** [comment]
Any chance it will be available by Tuesday 1/26?

**Comment by survey123** [comment]
This is totally depending on the Apple App Review process at the moment. Given that this fix was submitted 12 days ago to the app store we believe the fix will be approved at any moment now, but it is out of our own control.   Looking at the history or reviews we anticipate that the update will be ready by the 26th, but again, it is not within our control.

**Comment by sirws** [comment]
Thanks!

**Comment by bart-richardson** [comment]
Can you let us know when the update has been published by Apple?  

Thanks!

**Comment by survey123** [comment]
Certainly. @bart-richardson

**Comment by survey123** [comment]
Quick update on this.  The App Review process at Apple for the Survey123 app got stuck, so we have decided to move forward with the next update to avoid a delay in our planned Valentine's Day release (Feb 14).
This means that the iOS version of Survey123 will continue to have the map preview broken until the entire Review Process for the next update is finished. We will cross fingers and hope that the Review Process in this round is faster. Based on past experience and ignoring the last update, it should take around 10 business days.


@bart-richardson 
@sirws

**Comment by survey123** [comment]
Closing this issue. Fixed in 1.2.49.  Please update the app from the Google Play or Apple stores to get the fix. Thanks for your patience.

@bart-richardson 
@sirws
