### ISSUE TITLE
Sharing surveys from survey123.esri.com does not work

### ISSUE THREAD

**Issue by ftiru** [Esri/Survey123Community#278]
Some users have reported that they are unable to share their surveys from http://survey123.esri.com/#/surveys page. I tested with at least two surveys and was able to repro the issue. When you click the share button > select the organization and/or group > and click  OK, the process never finishes. Fiddler does not show and request being sent when clicking OK to share.

![sharing](https://cloud.githubusercontent.com/assets/16827336/12497716/5b0d9ca6-c052-11e5-9979-0e0dbea79ae4.PNG)

Fasil T.
Esri Support

**Comment by survey123** [comment]
Hi. We are working on this issue. Thanks.

**Comment by terryiffland** [comment]
Did this exist in the previous version, or is it a new issue?

I'm interested in being able to create a survey for a group to use for collecting form-based data, so I am looking forward to getting this solved.

**Comment by survey123** [comment]
@terryiffland 
We have had this issue from day 1. It turned out to be harder to fix than we thought. 
The Sharing and View Results options in the web site stop working when you change the title of the survey in Connect. While this is fixed, I would suggest you:
1- Set the title of your Survey in Connect once (when you create it) and you do not change it later
2- If you still have the problem, download the data directly from the Surveys Feature Service using ArcGIS.com as shown here: 

 https://geonet.esri.com/groups/survey123/blog/2015/11/10/downloading-data-captured-with-survey123-for-arcgis

 We are doing our best to have this resolved.

**Comment by terryiffland** [comment]
In the error I've experienced I've had changed the survey title (or anything else).  I merely published the survey, looked at the survey to share from survey123. When I do, I get the in process circle over the OK button, but the action never ends.

**Comment by ftiru** [comment]
Terry @terryiffland,

In the meantime, you can use the following workaround option to share your surveys with a group or organization:

1. Sign in to ArcGIS.com
2. Click on My Content
3. Find the Survey folder from the left and click on it
4. Check the box next to both items (code sample and feature layer)
5. Click Share and select the group you want to share this survey with.

I hope this helps!

Fasil
Esri Support

**Comment by terryiffland** [comment]
This worked for me. I'd not had a chance to go in via AGOL and look at my content. I saw that a separate folder was created. I shared the code sample and feature layer from there, and others are now able to see the survey.

Thanks for the suggestion and clarification.

**Comment by WeASeL-Antigua** [comment]
When I share with my organization and click OK, I get a green check mark in the OK button to signal that the changes was applied but when I refresh the page, my organization is deselected.

**Comment by GeoJtaylor** [comment]
I am having this problem as other are.  I named my survey once.   When I check share with my organization, it unchecks itself as described. I can see my survey as an administrator, but no one else can. I shared my form with everyone and with my organization via ArcGIS online, but this has no effect. Has anyone found a work around?

**Comment by survey123** [comment]
Closing issue. This problem is now fixed. Remember to clear the browser's cache to get the latest from the web site.
