### ISSUE TITLE
Import Existing XLS Forms into Survey 123 Connect (Build 0.0.39)

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#28]
It is unclear on how to import an existing XLS Form into Survey 123 Connect (Build 0.0.39) and the user is not provided with any instruction other than the fact that it is possible.  Currently, the only way to import an existing form is to drag and drop it onto the New Survey (+) button.

![image](https://cloud.githubusercontent.com/assets/3289025/6685697/7c843610-cc9c-11e4-926c-d75b3bd06b6a.png)

**Comment by survey123** [comment]
Thanks. We will look into making 'imports' more obvious.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Closing.
@jmirmelstein
