### ISSUE TITLE
Date Picker formatting issues in iOS if non-default Dynamic Text setting is used.

### ISSUE THREAD

**Issue by esridoyle** [Esri/Survey123Community#280]
Hi
The Date Picker looks pretty bad on iPhone 6. Any suggestions?
![badedatepicker](https://cloud.githubusercontent.com/assets/3178275/12559593/e7a75cb8-c38d-11e5-8895-bb101d179452.PNG)

Eamonn

**Comment by survey123** [comment]
I do not seem to be able to repro. See calendar in iPhone6 (my test device).
You may want to open an Esri Tech Support incident so we can go with you through this.

![img_0142](https://cloud.githubusercontent.com/assets/10968332/12561120/548b4f46-c353-11e5-9e1a-72710d438821.PNG)

**Comment by Thadius** [comment]
i am experiencing that same issue.  iOS version 8.4.1
Survey123 Version. 1.2.19

**Comment by Marie-Lou** [comment]
I have iOS version 9.2.1 , and Survey123 Version 1.2.12, and I have the same problem.

**Comment by survey123** [comment]
Thanks to all for your feedback.
Our Esri Tech Support analysts looked into this and found the source of the problem.
The calendar control is reacting to the iOS Dynamic Type feature. To get your font sizes back to normal you will need to keep the Dynamic Text setting right in the middle. Avoid the read area.

I am flagging this issue as an enhancement request for now. Changed the Title to reflect the nature of the problem.

![img_0143](https://cloud.githubusercontent.com/assets/10968332/12564736/c2b4c346-c365-11e5-9092-de115b06f71a.PNG)

**Comment by Marie-Lou** [comment]
I've checked that the Dynamic Text setting on my iPhone 6s right in the middle, as you suggested - the calendar display didn't change at all.....  I even tried the smaller text setting, but still no change :(

**Comment by survey123** [comment]
After you change the setting, please restart your phone.

**Comment by Marie-Lou** [comment]
I've changed the text size to the smallest setting & restarted the phone.  The days of the week display well now, but the longer named months (September, November & December) doesn't the year fully.  It may be a good idea to use abbreviations for the months (Sept, Nov, Dec)?
This isn't a show-stopper, we'll work around it :)
[iPhone 6s text size.docx](https://github.com/Esri/Survey123Community/files/104081/iPhone.6s.text.size.docx)

**Comment by survey123** [comment]
Definitively Marie-Lu. We need to account for the real estate available better so the text is adjusted accordingly. We will put this in the back-log so we look at it in the future. Thanks!

**Comment by survey123** [comment]
@esridoyle @Marie-Lou @Thadius 
Working on this. 
Fix planned to be available in the International Women's Day release.

**Comment by survey123** [comment]
1.2.82 is ready for you to try.
Please download the app from the store. This issue should now be addressed.
@esridoyle @Marie-Lou @Thadius 
Closing issue.
