### ISSUE TITLE
Can't Publish Surveys with an 'end' type of Question (Portal for ArcGIS Only)

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#285]
Can we use the 'end group' and 'end repeat' types in apps that are being published to portal since end is a reserved key-word in PostgreSQL?

Thanks
--gary

**Comment by survey123** [comment]
Yes. The constraint is on the 'end' type of question. End repeats and End Groups should be fine.

**Comment by bowlesgsrcx** [comment]
I have attached 2 surveys for review. They are exactly the same, except one has several group types and one repeat type. The survey with the groups and repeats will not publish (JSON feature [name] not found. Error 500.
Thanks,
--gary
[SWS_ends.xlsx](https://github.com/Esri/Survey123Community/files/112810/SWS_ends.xlsx)
[SWS.xlsx](https://github.com/Esri/Survey123Community/files/112809/SWS.xlsx)

**Comment by HannahFerrier** [comment]
Hello Gary!

You have some spaces in the name column in your choices worksheet and one of your groups is missing a label.

However, the reason for the **Error 500** is the cascading select. It is a known issue that cascading selects are not currently supported when using Portal.

Thanks,

Hannah

**Comment by bowlesgsrcx** [comment]
Hannah,

The only difference between the 2 forms was the groups and the repeat. The cascading select worked fine and published when the groups and repeat are not in the form. I only received the error when the groups and repeat were added.

--gary

**Comment by HannahFerrier** [comment]
Gary,

Could you please try adding the missing label for the _begin repeat_ in row 17 and let me know if it works?

- Hannah

**Comment by bowlesgsrcx** [comment]
Hannah,

I still get the same error. JSON object[“name”] not found. Code 500.

Also, when I create a new survey from a template, there is a template.xml file that is left in the new survey folder in //My Survey Designs that shows up on in the survey list when I open Survey123 Connect to select a survey. I wound up with 6 choices of template in with my actual surveys. I went in and deleted the file from each folder survey. Not sure if this a bug or not but wanted to let you know.

Thanks for all your help with this,

--gary

Gary H. Bowles
GIS Database Administrator II | Seneca Resources
Office : 412-548-2544 | Cell Phone: 412-334-5273

**Comment by bowlesgsrcx** [comment]
Hannah,

Attached are the 2 forms I used this morning. Forms_1.xlsx published without error, Forms_1_Ends.xlsx returned the JSONObject error.

--gary

Gary H. Bowles
GIS Database Administrator II | Seneca Resources
Office : 412-548-2544 | Cell Phone: 412-334-5273

**Comment by bowlesgsrcx** [comment]
Hannah,
We upgraded Portal to 10.4 and the surveys that i sent above with the Groups/Repeats work fine.
Thanks,
--gary
