### ISSUE TITLE
Headings of related tables

### ISSUE THREAD

**Issue by spado** [Esri/Survey123Community#286]
Ok, this totally could be something simple I am doing wrong, but I can't find the answer anywhere.
I have a survey which has several spots where a repeat occurs.  When this survey is downloaded, the repeats appear as a related table linked to the feature class, which is great.

The question I have is that when I examine the downloaded data in Arcmap, the related tables don't have a heading.  See attached image:
![related tables](https://cloud.githubusercontent.com/assets/15007800/12707833/ff9a65ea-c8ec-11e5-9498-12cf3fff414f.PNG)

How do I structure my repeats so that the resulting related table has some sort of identifiable heading. 

I assume the answer may lie somewhere in the settings tab of the xlsx 

Thanks!!

**Comment by survey123** [comment]
Hi. Thanks a lot for reporting this issue. This has been addressed in version 1.6
You will need to publish your Survey again to see the difference. Thanks.
