### ISSUE TITLE
Survey123 Web Client

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#289]
I have another enhancement request! It would be great if there were a Survey123 web client similar to other ArcGIS Online applications. So when you publish a survey using Survey123Connect, it would create an app that you can access from a browser.

**Comment by survey123** [comment]
Thanks for your comment. We are looking at building a web client to Survey123 smart forms in the second half of 2016. Think of GeoForms in steroids. We appreciate your feedback. If someone else is interested... push your comments in this issue.

**Comment by Marie-Lou** [comment]
Yes - definitely interested!  I have a number of users used to access my different ArcGIS Online creations from a browser, and it will be wonderful if they can use Surveys in a similar way.

**Comment by johngillham** [comment]
+1 A Geoforms on steriods would be awesome!  Especially if it included the ability to edit existing records....something both (great) products are lacking (but highly requested functionality).

**Comment by travisbutcher** [comment]
:+1:

**Comment by gisjoel** [comment]
+1 This would be great!

**Comment by survey123** [comment]
The first cut of a web client to Survey123 surveys is ready now for you to try. More details here: https://geonet.esri.com/groups/survey123/blog/2016/06/23/international-public-service-day-update
