### ISSUE TITLE
Incorrect Syntax Error While Uploading XLSForm from Survey 123 Connect (Build 0.0.39)

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#29]
The following error is received while trying to publish a Feature Service from Survey 123 Connect (Build 0.0.39) from an XLSForm that contains repeats per http://xlsform.org/#repeats.  As soon as the repeats are removed from the XLSForm, the Feature Service is created successfully.

![image](https://cloud.githubusercontent.com/assets/3289025/6685761/11fe63a0-cc9d-11e4-92d4-b51ab34201a9.png)

**Comment by survey123** [comment]
Thanks. We are working on this. We will try to get repeats working soon.

**Comment by jmirmelstein** [comment]
Thanks for the quick response.  Yes, I can confirm that the repeat was surrounding an image capture field.

**Comment by survey123** [comment]
Closing. Acknowledged that we need to support Images and Repeats. Working on them.
