### ISSUE TITLE
Android Compatibility query

### ISSUE THREAD

**Issue by Londonite** [Esri/Survey123Community#290]
I have users who are unable to download Survey123 as they are getting a device compatibility issue (Galaxy S and a 2014 Toshiba tablet running android gingerbread, firmware version 2.3.5). I understand this may be older than the current version is compatible with, but it there an older version or alternative solution for these users?

**Comment by survey123** [comment]
Hi!  The oldest version of Android we support is: Android 4.1 (Jelly Bean).   Anything older than that will not work for Survey123. We are sorry, but there is no workaround to this.

**Comment by survey123** [comment]
Closing this issue.  @Londonite
