### ISSUE TITLE
Relevant-field doesn´t work in iOS

### ISSUE THREAD

**Issue by jekenstedt** [Esri/Survey123Community#293]
I have made a survey in Survey123Connect and it uses relevant fields. It works very good in the simulation in Survey123Connect. I export it to AGOL and when I open it in iOS the fields doesn´t show as expected. I want to se more fields when the requirements are met.

The field looks like: ${Provyta1}=1 

Do you have any idea why this happens?

In simulator:
![simulation](https://cloud.githubusercontent.com/assets/17064926/12814835/5ee65d90-cb42-11e5-8eab-098ac6ddaa0e.jpg)

On Iphone (latest app-version):
![iphone](https://cloud.githubusercontent.com/assets/17064926/12814994/99c07fa8-cb43-11e5-982f-d2da085f8331.PNG)

The XLS-file
[Bestandsdata.xlsx](https://github.com/Esri/Survey123Community/files/117387/Bestandsdata.xlsx)

**Comment by survey123** [comment]
Hi Johan. I posted answer in GeoNet: https://geonet.esri.com/message/585861#585861

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The use of relevant statements on iOS was fixed in the August (1.7) release.
