### ISSUE TITLE
'ascii' codec error

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#294]
I am creating a new survey. Until a certain point the conversion to Survey123 works very well but after changing/adding "something" (I can't figure out what) I receive the error message

'ascii' codec can't decode byte 0xcd in position 170: ordinal not in range(128)
![error](https://cloud.githubusercontent.com/assets/11991954/12816617/080583ac-cb56-11e5-8ff4-c6dafca2d849.jpg)

Searching for this error I found issues related to python but unfortunately unresolved. 
I am guessing that somewhere in the data that I am copying from other files to fill the choice lists in xls, there is a character that's not unicode. 

Any idea how to solve this?

Edit: After deleting everything and copy&paste the content from another xls-file to the survey form I figured out that my mistake was to write as a relevant clause `{list}='yes'` instead  of `${list}='yes'`. 
Is there maybe a way to make this error message more selfexplaning?

**Comment by survey123** [comment]
This error is typically triggered by expressions. For example, expressions in the Relevant column. The crux of the problem generally is an expression where you are missing the symbol $ in front of the curly brackets. For example:

${HasJob}='yes' is correct. {HasJob}='yes' is not correct.

It is good to validate often so when you get once of these errors you can easily identify the question that caused the problem.

**Comment by r2thom** [comment]
I am having this same error, although all of my expressions are correct.  I am triple checked them at this point and I still continuously get the same error.
Anyone have any additional feedback in regards to this error.

Thanks

**Comment by TViveiros** [comment]
I received a similar error when using regular brackets rather than curly brackets in an expression. The error went away after replacing the regular brackets with curly brackets.

**Comment by Bronx2AK** [comment]
I've found that if you try to manually type in the 'Type Field' or copy and paste the 'Type' to another row it causes the error. It seems Survey 123 does not like the drop down altered. You have to use the drop down every time. I had a 300+ lines and it kept displaying the same error which it said was on line 197. I have the survey in 12 groups so I took 11 of them away, refreshed and the error disappeared. I then added each field back in row by row and copied the previous row's 'Type' with the drop down information. This fixed the issue.

**Comment by survey123** [comment]
@Bronx2AK @TViveiros @r2thom @nicsi76 
We have improved  the error messages quite a bit.
Please trying installing [Survey123 Connect for ArcGIS 1.6](http://doc.arcgis.com/en/survey123/download/)

You can stay tuned regarding latest updates to Survey123 through our [GeoNet Group](https://geonet.esri.com/groups/survey123)
