### ISSUE TITLE
How to use regex for "time" field?

### ISSUE THREAD

**Issue by dtoy** [Esri/Survey123Community#295]
Just wondering how I can use regex in a text field. The current "time" option for a time field is not practical. Does anyone have code that I can put in the constraint field. I don't know much about regex.

Thanks,

**Comment by dtoy** [comment]
Also is there any way to have the colon automatically in the field so all you have to enter are the numbers. I don't want to split the hours and minutes into two fields.

**Comment by pbond-idfg** [comment]
It would also be cool if you could set a default time of now().

**Comment by travisbutcher** [comment]
@pbond-idfg The now() issue is logged:  #238 give it an upvote so it can take some priority.

**Comment by survey123** [comment]
Closing issue.
Please try input masks.
We support them starting at 1.2.82
More details here: https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
