### ISSUE TITLE
New survey xls forms are missing most of the fields

### ISSUE THREAD

**Issue by dtoy** [Esri/Survey123Community#296]
When I start a new survey and go to setup the xls form. The only column headings (4 total) under the survey tab are: type, name, label, hint. Where are the relevance and constraint fields? I just downloaded the new version of Survey123ConnectBeta

**Comment by survey123** [comment]
Hi Dustin. Sorry for the confusion. Try the 'Tempate'. The Template includes a blank XLS file with ALL fields.

**Comment by dtoy** [comment]
Awesome! Thanks!
