### ISSUE TITLE
can I retrieve a value from a choice list?

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#298]
Following scenario: The field trac_letter is filled by select_one from the list trac_letter. Now the next field should show a trac number which should be filled from either the list trac_letter (or a new list trac_nr for example) where I would list the numbers to show, depending on the trac_letter that was chosen before. I would assume that should be possible through the calculate field and readonly but I can't figure out how to access the according field in the list. I tried ${trac_letter.nr} for example but that obviously does not work. 
Thanks for any hints!

**Comment by anaymushina** [comment]
Maybe it will help: http://survey123.maps.arcgis.com/sharing/rest/content/items/a125be1d5fb34855a0c2e035a7a154ae/data
Cascading selects sample form this page http://survey123.esri.com/resources/XLSFormSupport/#default

**Comment by nicsi76** [comment]
Thank you anaymushina. The cascading selects are working well and are really helpful. But in this case I want to write the according trac number straight to the database without selecting it in the front end. So it should be something in the calculate field like "select trac_nr from trac_nr_list where letter=trac_letter" - only in the correct language ;-)

**Comment by nicsi76** [comment]
Looks like this has to be done after data collection :-(
