### ISSUE TITLE
not-relevant field shows 

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#299]
I saw that some other people had already issues with the relevant attribute but I think mine is different since it does not seem to be app dependent. In Connect, Android (phone) and iOS (iPad) the behavior is all the same: 

The first field works well: When `bf_list` is selected `yes (1)`, the next field shows up and the text can be entered. 
The next field that is depending on the relevant attribute (`anti-erosion='1'`) is the field `erosion_act` but this one is shown from the beginning and also does not disappear when no is selected. I already tried putting it into a group but that also did not help. I also checked for spelling mistakes, removed the required attribute and put it back but I can't find the mistake. For all other fields that depend on the relevant attribute it works well that they only show if a certain selection was done.

I attached the current draft, maybe someone finds the mistake. 

[Uploading agri.xlsx…]()

**Comment by survey123** [comment]
@nicsi76 
It looks like the spreadsheet did not upload correctly. Would you mind trying again?

**Comment by nicsi76** [comment]
[agri.xlsx](https://github.com/Esri/Survey123Community/files/126063/agri.xlsx)
Next try :-) I think I didn't wait for the upload to finish last time...

**Comment by HannahFerrier** [comment]
@nicsi76 I changed the name of the field from **anti-erosion** to **anti_erosion** and it now works fine. Please only use word characters (a-z, 0-9 and _ ) in the _name_ column.

- Hannah

**Comment by nicsi76** [comment]
Thanks a lot Hannah! I don't even know why I used the "-" there because I always use the underscore normally....
