### ISSUE TITLE
Survey Actions Toolbar not displaying correctly in Connect. Build 0.0.20

### ISSUE THREAD

**Issue by IsmaelInRedlands** [Esri/Survey123Community#3]
Toolbar at the bottom does not display correctly.

![untitled](https://cloud.githubusercontent.com/assets/5918689/6197720/55541c4c-b39f-11e4-8e4b-0b2af25831dd.png)

**Comment by survey123** [comment]
Thanks. This is in our radar.

**Comment by survey123** [comment]
Fixed. Closing.
