### ISSUE TITLE
Relevant and Calculate are not honored

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#30]
The Relevant (http://xlsform.org/#relevant) and Calculate (http://xlsform.org/#calculation) XLSForm fields are not honored in the Survey 123 App for Android. 

Fields that should appear based on meeting their 'Relevant' condition are visible at all times in the app. 

Fields that should have their value 'Calculation' happen as a result of a formula are empty fields in the app.  i.e. - Field 1 is text, Field 2 is text, Field 3 should automatically concatenate Fields 1 & 2.

**Comment by survey123** [comment]
Hi Jeremy,  Calculate fields are on our road map, although not implemented just yet. As for Relevant, they should work as of Survey123 app  v. 0.0.42.  If Relevant is not working for you, please post your XLS file in a place we can download it so we can reproduce. Thanks.

**Comment by jmirmelstein** [comment]
The spec for XLSForms allows for the calculate to do simple calculations as well as concatenations via the formula.  My XLSForm validates according to the spec, so will it not be supported?  I can provide the XLSForm separately to the dev team - just let me know where to post it. 

I can currently see that my version of Survey123 Connect is 0.0.39, but the app for Android is 0.0.42.  Should these match?  And if not, should I be testing against the mobile app of the validation of Survey 123 Connect?

**Comment by survey123** [comment]
Please send your xls to Ismael
Survey123 and Survey123 Connect versions don't match. You have the latest of both at the moment.

**Comment by spatialdude** [comment]
Hi @jmirmelstein in your 'Anode' form you have the expression -

**concat(substr(${quayWallSection},0,20),'-',${bollardSpaceNumber},'-KAB-',${anodeNumber})** 

for the calculation of the **anodeFunctionCode** field.

Is the intention that this field is always automatically calculated and the user just sees the automatic code in the form? ie the user cannot change the automatically generated code.
or is the user supposed to be able to override the calculated code value?

**Comment by jmirmelstein** [comment]
Hi @spatialdude - Yes, the intent is that the value of that field is automatically calculated from the other input values in the form.  I would expect the user can still change it unless that field is otherwise designated as read-only in the XLSForm spec.

**Comment by mhogeweg** [comment]
I can see some ambiguities if we sometimes apply the formula and other times don't. The spec is not very specific on this topic either: http://xlsform.org/#calculation

**Comment by spatialdude** [comment]
Thanks @mhogeweg @jmirmelstein 

The next update will have the improvements in the relevant and calculate support.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Let us know if this works now you and we will close issue.
 @mhogeweg @jmirmelstein

**Comment by jmirmelstein** [comment]
@survey123 This looks good in the new Survey 123 Connect app (1.0.59).  FYI - I had to grab this from an Esri-internal file share as the public download link is currently returning a 404.

**Comment by survey123** [comment]
Thanks @jmirmelstein   We have fixed the 404 problem.
Also closing this issue for Relevant and Calculate.
