### ISSUE TITLE
Error: 401 Error downloading. Server replied: Internal Server Error 

### ISSUE THREAD

**Issue by CSHenriques** [Esri/Survey123Community#301]
Hi,

Can you tell me, please, I do I have this error?
Thank you!
Best!

Error Report Details: 
Status Code: 500 
Error: 401 Error downloading https://survey123.arcgis.com/api/xls2xform - server replied: Internal Server Error 

Operating System: windows 
Application Version: 1.2.12 
Framework version: 1.0.4 
[Please add any further comments here]

**Comment by survey123** [comment]
This error is typically caused when you add non ASCII characters in the NAME column. To avoid this error, carefully check the values you put into the NAME column in both the Choices and Survey worksheets. Remove any special characters, accents etc.

**Comment by survey123** [comment]
Better error handling has been added.
Please download [Survey123 Connect for ArcGIS version 1.6](http://doc.arcgis.com/en/survey123/download/)

To stay tuned regarding latest updates, join our [GeoNet Group](https://geonet.esri.com/groups/survey123)
