### ISSUE TITLE
Autofill info within a repeat

### ISSUE THREAD

**Issue by spado** [Esri/Survey123Community#303]
I can't seem to be able to get something that is entered outside of a repeat to autofill within a repeat.  

At the start of my survey my workers enter in an Asset ID number.  I have a multiple repeats related to various building damage encountered and I want each one of them to have the asset id so that my manager can look at all the roof damage etc from multiple locations.  In order to do that my workers currently need to enter the same ID number over 50 times.   Is there anyway to make this autofill?  

I've tried using defaults.  The ID is an integer and I've tried using a calculation. However  I can't seem to get it to work when the info is outside a repeat and you want it inside a repeat. 

Any solutions, however creative, are most welcome

**Comment by survey123** [comment]
@spado 
This is a bug. Calculations within Repeats do not work correctly.
Flagging as Planned.

**Comment by jdaviesmitcham** [comment]
This is a vital aspect of my project also, default values need to work within repeat fields, 
Thanks Jake

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The ability to calculations in repeats was added in the November (1.9) release. 
We do know of a problem when one or more repeats are created, then deleted, then new repeats created - the calculation no longer works.  But the scenario describe in this issue, does work.
