### ISSUE TITLE
Upload Completed Survey Errors Cause Multiple Data Records

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#305]
I am finding that for some completed surveys, when we attempt to upload the data, we receive a generic Code 500 error (see attached screen cap) that says the survey was not sent. We attempt to send the survey and keep receiving this error. However, when i look at the data in a webmap in Portal, I have multiple copies of the survey data matching the number of "unsuccessful" upload attempts. There does however appear to be an issue with the photo attachments as some of the surveys contain no attachments, some contain 1 attachment and once the survey has finally successfully uploaded, the data contains the 2 photo attachments that were taken. I am connected via our company wi-fi with very strong signal. Portal 10.3.1 Samsung Galaxy S6.
![screenshot_2016-02-10-10-11-52](https://cloud.githubusercontent.com/assets/14822701/12951243/655c017e-cfdf-11e5-99d2-18def97bfe0e.png)

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
