### ISSUE TITLE
Double Field - Precision & Scale

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#306]
Is there a way to force a certain number of decimals for a Double field? I have a pH input that want the gdb field to have a precision of 6 and scale of 2. Doable??

Thanks

**Comment by survey123** [comment]
Hi Gary:  we will try to get this for you in the next update.  We will resolve this through the use of 'masks'.
  Assigning this to the next Milestone.

**Comment by survey123** [comment]
Closing issue.
https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release 
Please open new issue if you run into problems. 
Input masks tend to work well on iOS with 1.2.82, in Android we have identified issues. If you do too, please report and will try to fix.
