### ISSUE TITLE
Putting contraint of >= throws an error

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#307]
I am trying to put a constraint where the age >=18 to answer the survey and when I do that I get an error. using just >17 also threw exception. < worked but using <= gave same error.

![image](https://cloud.githubusercontent.com/assets/4204178/12961174/18bdf268-d00d-11e5-8058-556f6e62b0f3.png)

**Comment by bowlesgsrcx** [comment]
try adding a . before the >=

https://geonet.esri.com/groups/survey123/blog/2015/08/24/using-formulas-in-survey123

--gary

**Comment by survey123** [comment]
Closing.

**Comment by deepti10** [comment]
that worked. Thanks
