### ISSUE TITLE
Multiple choice check boxes do not auto resize (Windows and Android)

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#309]
When the multiple choice check boxes are used and the length of the option is longer than a single line the check box do not auto resize. This issue is happening only in the windows, Android 5.1.1 (did not test other versions). iPhone does not have the same issue 
![image](https://cloud.githubusercontent.com/assets/4204178/12961886/b561d08c-d010-11e5-9483-5df0ba928e36.png)

![image](https://cloud.githubusercontent.com/assets/4204178/12961909/ceb838aa-d010-11e5-8981-82bda71835f8.png)

**Comment by survey123** [comment]
Closing. 
Fixed.
