### ISSUE TITLE
Image field does not respect Relevant setting

### ISSUE THREAD

**Issue by kengorton** [Esri/Survey123Community#31]
I have an image field with a Relevant setting that makes it visible only if the selected answer on a previous question is not 'none': ${docOwnership}!='none' 

However, regardless of which of the 6 values is selected for docOwnership, the image field is always displayed.
An image of the XLSForms spreadsheet with the Relevant setting on the image field:
![relevant](https://cloud.githubusercontent.com/assets/5541824/6694846/43da8398-ccb3-11e4-8ce0-414426ea0d5b.JPG)

An image of the value list for the docOwnership field:
![doclist](https://cloud.githubusercontent.com/assets/5541824/6694856/586a5914-ccb3-11e4-93d8-346079814bbe.JPG)

An image of the image field being displayed despite ${docOwnership}='none': 
![imagefieldscreencap](https://cloud.githubusercontent.com/assets/5541824/6694861/5eedc5dc-ccb3-11e4-8417-434d0e506c1c.JPG)

**Comment by survey123** [comment]
Thanks Ken. We can repro this and will look into it.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Let us know if this works now you and we will close issue. @kengorton

**Comment by survey123** [comment]
Fixed. Closing.
