### ISSUE TITLE
crypted letters in error message and notes

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#311]
I wasn't even sure how to call this issue because I don't know a word for this kind of appearance.

Converting my xls-file I get the following error message: 
![error_crypted](https://cloud.githubusercontent.com/assets/11991954/13003055/dd1f1078-d17b-11e5-850e-0b6478e9e59b.jpg)

As you can see it's hard to read ;-) I get the same kind of "characters" in the form instead of the notes. 
I think it is related to my bad internet connection. 

Are you aware of this behavior?

**Comment by survey123** [comment]
@nicsi76 
Could you please check with version 1.4.x? Let us know if the problem persists.

**Comment by nicsi76** [comment]
It is difficult to reproduce this issue but I will keep my eyes open for it.
