### ISSUE TITLE
Updating existing surveys, rather than re-publishing them

### ISSUE THREAD

**Issue by Marie-Lou** [Esri/Survey123Community#313]
I have found that my surveys usually need minor tweaks when the users start working with them - what seems like a brilliant idea when you design something while sitting behind the desk in an air conditioned office doesn't always work that brilliantly out in the field....  :smile:  

I've perfected the system of exporting the data already captured to a file geodatabase before re-publishing the updated system, but the upgrade we did on our surveys after this Valentines Day update got me thinking - can you add an "Update" function so that we can do minor changes to existing surveys without needing to jump through hoops to retain existing data which will be lost when you re-publish?

**Comment by RooPitt** [comment]
+1 
I understand that the a major overhaul would (and should) result in a whole new survey, but I need to add one more answer option to one multiple choice question.... it would be great if these kinds of minor edits were possible.

**Comment by RKnepper3** [comment]
Actually you can manually add another choice and some minor changes via AGOL.  That said I tested it once and had no issues a while ago but make no promises.  I would test it yourself before using it on an active survey.

https://blogs.esri.com/esri/arcgis/files/2014/10/How-to-Update-Hosted-Feature-Service-Schemas1.pdf

**Comment by survey123** [comment]
Thanks to all for your feedback
@RooPitt  @RKnepper3 @Marie-Lou 

Check out the latest version of Connect (1.4.30) and the App (1.4.28). You will now be able to change lots of things without having your Feature Service replaced: the title, description, summary, thumbnail, image size threshold, style, map properties as well as any label, grouping, media, calculations, constraints, defaults etc Only your changes to the survey require a feature service schema change, we will replace the feature service.

Connect download available at: http://doc.arcgis.com/en/survey123/download/
