### ISSUE TITLE
iOS 7.1

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#317]
I have an iPhone user with iOS 7.1 (11D167) that cannot connect to portal in Survey123. She keeps getting an error that Host not found. Is this os still supported or do I need to inform this user to update their phone?

thanks.

**Comment by survey123** [comment]
Hi Gary,

 iOS 7.1 is a supported operating system and passes our regular certification tests. We believe that the issue may relate to connectivity issues. Try typing the URL of your portal in the device's browser to ensure you have access to the portal.
