### ISSUE TITLE
Constraint Message

### ISSUE THREAD

**Issue by Thadius** [Esri/Survey123Community#318]
Is it possible to only show the constraint message without including the actual constraint code

**Comment by Marie-Lou** [comment]
Do you want a message to display in the survey, e.g "You must be 18 years or older to complete the survey", without actually adding that as an constraint code, or do I misunderstand your question?

If you only want the message to appear, try to add it as a "note" type....

**Comment by survey123** [comment]
@Thadius   How critical is this to you? We could hide the expression if a message is used, but some other people have expressed to us that showing the expression is useful even if the message is specified. Can you elaborate a bit on your request?

**Comment by survey123** [comment]
@Thadius  Issue addressed. Please check the 1.6 version of the Survey123 mobile app. The Constraint dialog now shows your message and hides the actual expression code.
