### ISSUE TITLE
Georeferenced photos

### ISSUE THREAD

**Issue by AurelineGrange** [Esri/Survey123Community#319]
For field work, it would be very useful if : 
- multiple photos could be taken and saved with a single "Take a photo" button
- photos could be georefenced automatically (with validation to check that the location is correct)

Any planned development for these features ?

**Comment by damonTRC** [comment]
This is exactly the same question/issue my users have raised.

**Comment by survey123** [comment]
@AurelineGrange   @damonTRC   This note is just to let you know that we are looking into this, although we still do not have a solution to the problem. Stay tuned.

**Comment by survey123** [comment]
Moving into the Sep 2016 release.

**Comment by cconnolly91** [comment]
That's great news! Do you know how the multiple images will behave ArcGIS Online/Ops Dashboard/Collector?

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release support for EXIF information.
Handling multiple photos still on the works. Refer to: https://geonet.esri.com/message/552266?commentID=552266#comment-552266
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
