### ISSUE TITLE
data in repeated groups 

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#320]
I have a survey that has nested repeats: I have an operator who can have a certain number of plots and on each plots he is growing different types of crops. 
Filling the form I enter first the operators information, then the plot information, then the information on the first crop and the second crop (...). When I then add a new plot it fills automatically the information on the crops from the first plot. So e.g. even if I only have one crop on the second plot it fills automatically the two crops I had before. That means I have to manually delete the crop and refill the data for the remaining plot which easily will cause errors I'm afraid. 
Did I do a mistake setting up my survey or is that a bug?

**Comment by nicsi76** [comment]
Info from the team: This is a bug.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)

**Comment by nicsi76** [comment]
This problem was still not solved in total. While a single repeat works well now, the nested repeats still just repeats the data.
