### ISSUE TITLE
Unable to Sign In to ArcGIS Online - Survey123

### ISSUE THREAD

**Issue by potterg** [Esri/Survey123Community#322]
When I try to sign in using the 123Survey app on my iPhone 6 or using the 123Connect app on Windows 10 the system just spins.  I am able to enter my login name and password and then it just sits on the signing in page and never seems to connect.

![Uploading 123ConnectLogin.JPG…]()

**Comment by survey123** [comment]
Hi. You may be using a Public ArcGIS Online account. These accounts are not supported with Survey123 for ArcGIS. We will try to pop a proper message, but at the moment you get the behavior you describe (wheel spins forever).

Please use an ArcGIS Organizational account if you would like to publish or use Surveys. If you do not have one, you can create a free 60 day trial as follows:
1) Go to survey123.arcgis.com
2) Open the login dialog. In the left panel, select the option to create a Trial ArcGIS Organization. 
3) Use your new ArcGIS credentials to login

**Comment by potterg** [comment]
Thanks, was logging in under the wrong account.  Forgot to use the organizational account versus personal account.

**Comment by nmilne** [comment]
I get a similar issue, however only have an organisational account and never experienced this on previous versions of S123. After signing in I get a "ArcGIS public account is not supported" page - this account worked on my Android device but not on IOS - when I did (once) manage to log in the downloading survey phase incurred wheel spin for over 15 mins.

**Comment by survey123** [comment]
We have recently observed on a device running Androids new 'N' OS, this behavior and believe its to do with network security. We are working on improving how Survey123 handles network security requests (should be better in next release), but in the meantime can you please try this device on a different network and report here if it works?
