### ISSUE TITLE
Manual GPS Coordinate Not Being Saved

### ISSUE THREAD

**Issue by pbond-idfg** [Esri/Survey123Community#323]
While I was testing the Survey123 app on my Android, I was just manually moving around the GPS coordinate map to capture a location out in "the field".  The pin appears on the map in the app in the correct location but after I send the survey and view it via survey123.esri.com, the shown location is my true phone location (my office).  Also, the data collected using repeats is not represented in the attribute table. 
When I view the survey  through ArcGIS Online Map Viewer, I see two locations, both my office and field locations.  The office location is to my survey feature service and the field location is tied to a stopRepeat feature service.

![image](https://cloud.githubusercontent.com/assets/6034863/13149399/a1f2888e-d61e-11e5-9bd4-67eea54edd9b.png)

I am not sure if this is a bug or if I am not suppose to be manually mapping my location.  Although, if this were the case I wouldn't think you would be able to move the map around in the app.

**Comment by HannahFerrier** [comment]
If you do not have a geopoint control in your main form (ie. not in a repeat), then Survey123 will use your phone location to attach a location to your data. This is why you are seeing the 'parent' record in your current location.

When you have a geopoint question in your repeat, you are able to add multiple locations for each repeated record. This is why you are seeing the locations you manually selected for your related records.

Let me know if you have any further questions,

Hannah
