### ISSUE TITLE
survey123.esri.com - remove html formatting text from attribute table

### ISSUE THREAD

**Issue by pbond-idfg** [Esri/Survey123Community#325]
When I view the attributes of a survey using survey123.esri.com, you can see the html formatting as well:
![image](https://cloud.githubusercontent.com/assets/6034863/13150372/b0d5fd1e-d622-11e5-89d5-4c72f8d73916.png)
Just to make it cleaner, it would be nice if the html text could be hidden, like when you view the attribute table in an ArcGIS Online map:
![image](https://cloud.githubusercontent.com/assets/6034863/13150399/da4c867c-d622-11e5-9235-1f57bad7e13e.png)

**Comment by zhif7782** [comment]
Hi Pam,
Could you share us some using scenarios that need to include html tags in the feature service's content?

**Comment by pbond-idfg** [comment]
I used the html formatting in the XMLform to change the font color (see the first graphic above).
![image](https://cloud.githubusercontent.com/assets/6034863/13412442/8779c950-df00-11e5-8f1d-0c0302f5af3f.png)

**Comment by zhif7782** [comment]
Pam,
Thank you for the feedback. We'll have this fix on our road map and let you know when it has been done. 
Please stay tuned with Survey123:)

**Comment by survey123** [comment]
@zhif7782 
FYI: The next update to Connect will no longer carry HTML formatting into the field aliases. Surveys published with the next update will not cause the issue above in the web site.
We still will get HTML formatting from old published Surveys.

**Comment by survey123** [comment]
Thanks Pam.
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)

**Comment by pbond-idfg** [comment]
Sweet!  Thanks for the quick fix.
