### ISSUE TITLE
Duplicate data with unique objectID

### ISSUE THREAD

**Issue by RooPitt** [Esri/Survey123Community#326]
A problem with the data collected in the app...
Fieldworkers took photos in the field using the app and tried to upload the data, but found that it was very slow. They then returned to the office, and uploaded the data once they had a wifi connection. 
In some cases, this was connected to issue #247... they attached a photo (rather than taking it with the app) and got the Code 400 error message, so once they were back in the office they replaced the photo and uploaded the data.
Looking at the resulting data set, I have duplicate data for the surveys where this happened - in some cases up to 8 copies of the same data! But each copy has a unique objectID...
Any suggestions as to what is going on and how to prevent it? 
We now know about issue #247 so the fieldworkers have been instructed to avoid this, but given that a failed upload would be a common occurrence it seems strange that this would result in data duplication.
Thanks for your help!

**Comment by bowlesgsrcx** [comment]
I have had the same experience. See issue #305 
--gary

**Comment by deanmostad** [comment]
I just had this happen to me today.  I think the end user, myself included, hits the end survey button more than once.  It seems that sometimes the program hangs after the initial submission, instinct says to tap it again.... Ask the field folks if they hit the button more than once. I know I did.

**Comment by bowlesgsrcx** [comment]
For mine, the upload threw an error, then i resent it, it threw an error, etc. and when it finally went through, there were multiple data records uploaded. The final upload that went through successfully contained all 3 of the attachments, the rest contained varied between 0 and 2 attachments. It appeared that the survey sent the form data and got hung up on the pictures, however i had very strong wi-fi in office when these were sent.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
