### ISSUE TITLE
using 'OR' in relevant field

### ISSUE THREAD

**Issue by JoeWells27** [Esri/Survey123Community#327]
Is it possible to use OR in a relevant field? 

${Species1} = 'BLB'  - this works just fine
${Species1} = 'BLB' OR 'LMB'  - does not work

I'd like to use the relevant field on a "select_one", that has many choices.  Pretty much hide the next 'species' until one is selected (hide 2nd field until something is picked in first)

**Comment by deanmostad** [comment]
It Needs to be written as follows... i.e. the field name is required for each operator.

${Species1} = 'BLB' 
${Species1} = 'BLB' OR ${Species1} 'LMB'

**Comment by nicsi76** [comment]
${Species1} = 'BLB' OR ${Species1} = 'LMB'

to be consistent...

**Comment by nicsi76** [comment]
It seems like the `or` needs to be written in small letters!

**Comment by JoeWells27** [comment]
I didn't even think to put the 'or' in lower case.  Appreciate it!

**Comment by deanmostad** [comment]
G5figmkf

**Comment by deanmostad** [comment]
Ft he has h
