### ISSUE TITLE
Survey123 Connect fails to validate XLSForms when sitting behind a forward internet proxy

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#33]
Survey123 Connect (Build 0.0.39) is unable to import an existing XLSForm.  User receives the following error:

![image](https://cloud.githubusercontent.com/assets/3289025/6735851/5698ec90-ce61-11e4-9603-05e70178096b.png)

This error is received when Survey123 Connect is installed on a machine that sits behind a forward proxy server for internet access.  Wireshark shows that the application tries to make a request to xformshub.cloudapp.net.  This same XLSForm imports perfectly fine on a machine that is not behind a forward proxy server.

**Comment by survey123** [comment]
Thanks Jeremy. We need to look into this.

**Comment by survey123** [comment]
Closing issue. Fixed.
