### ISSUE TITLE
Making shared surveys visible to the group 

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#331]
I was wondering if it is possible to make the shared survey also visibly under My Surveys on the survey123 website. When I share the survey with my colleagues I also want them to be able to look at the results. It's working going through the AGOL to visualize the data in the Map Viewer but that's quite complicated if we only want to have a quick look at the results. Or an extra button with "shared surveys" or something like that?

**Comment by Marie-Lou** [comment]
Hi Nicole - have a look at  #283:
 *"....We also want to enable the author of the survey to allow participants to see everyone else's contributions or alternatively restrict read-access to preserve privacy.
We will work on this most likely in the second half of 2016..."*  
Its on its way  :smile:

**Comment by nicsi76** [comment]
Thank you, didn't see this one yet.

**Comment by WeASeL-Antigua** [comment]
In the mean time, you can use the web map with the enabled feature layer to create a Summary Viewer Web Application through AGOL.

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The ability to share your survey results with stakeholders was added in the December (1.10) release. See http://doc.arcgis.com/en/survey123/browser/analyze-results/sharesurveyresults.htm for more details.
