### ISSUE TITLE
media::image field and variables

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#332]
Does the media::image field recognize variables for image names? I have a calculated variable inv_species_calc which is equal to the selected species name plus .jpg ie. goatsrue.jpg

I am trying to display a fact sheet called goatsrue.jpg as a note by placing ${inv_species_calc} in the media::image field. No image displayed.

thanks,
--gary

**Comment by HannahFerrier** [comment]
You could include all of the possible images in individual note fields in your survey and show/hide them using **relevant** expressions. This way, you can only display the relevant image based on the previous question in your survey.
