### ISSUE TITLE
barcode types

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#333]
Are the new barcode type fields going to handle QR barcodes?

thanks,
--gary

**Comment by survey123** [comment]
Hi Gary,

 yes, although the implementation needs refinement in devices with low-quality cameras. You should be fine in iOS for sure and in Android phones with good cameras. We are improving the implementation to have this work better in low-end devices.

**Comment by survey123** [comment]
Closing issue. 
Have a look at: 
  https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
Please open new issue if you run into any problems.
