### ISSUE TITLE
Name attachments/pictures with some of the entered data instead of just the field name

### ISSUE THREAD

**Issue by dtoy** [Esri/Survey123Community#334]
I would like the picture that I take to use some of the data entered from the survey to name the photo. Is this possible or is there a backend way to accomplish this?

**Comment by survey123** [comment]
Check out version 1.4.288 of the Survey123 mobile app (available now in the app stores). You should now be able to change the name of the photo right from the app. Thanks a lot for your feedback. @dtoy
