### ISSUE TITLE
External Choices do not work with Version 1.2.77

### ISSUE THREAD

**Issue by Thadius** [Esri/Survey123Community#339]
Downloaded latest version to IPAD/IPHONE.  External choices appear to be no longer working.
From desktop the external choices are working. 

[Maintenance.xlsx](https://github.com/Esri/Survey123Community/files/146812/Maintenance.xlsx)

**Comment by survey123** [comment]
@Thadius 
Hi Steven. Working on this. We had a glitch in the last update. We are aiming to submit the fix to the Apple store before the end of the week.

**Comment by survey123** [comment]
The 1.2.82 update of the Survey123 app is available in the Google Play and iTunes store. This update should take care of this issue. Thanks a lot for reporting this!

Closing issue.
