### ISSUE TITLE
Is there a way to allow another user to view my surveys in survey123.esri.com so that they can also track the results? It looks like only the owner can see the surveys...

### ISSUE THREAD

**Issue by cdarti** [Esri/Survey123Community#340]

**Comment by zhif7782** [comment]
Thanks you for the feedback. It is great to see that you find good uses to it.
Currently only the survey owner has the ability to view the survey results, to share the survey results to other users in organization is on our radar, but are simply not there yet.
Please stay tuned to Survey123.

**Comment by lefcgis** [comment]
I'm wonder ir you make up tour mind about adding new users without AGOL accounts!!!     #fsociety

**Comment by survey123** [comment]
Hi @lefcgis , thanks for showing interests on this feature. Do you mean to share the survey results, such as the Data and Analyze tab, to someone that without AGOL account? If yes, could you provide some description on your use case for us to better understanding on this?

**Comment by phil-wilson** [comment]
Any update on this enhancement? It would be great to share the Analyze and Data tab with other ArcGIS Online user with our organisation. At present only the creator of the survey can see this data. More importantly now that we can print to PDF or paper via Survey123 website Data tab, would be great to share with others that need that access to print out surveys.

**Comment by survey123** [comment]
Hi @phil-wilson , this feature is definitely on our radar, we'll let you know as soon as we have a clear plan on it.

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The ability to share your survey results with stakeholder was added in December (1.10 release). See http://doc.arcgis.com/en/survey123/browser/analyze-results/sharesurveyresults.htm for more information.

**Comment by lefcgis** [comment]
Hi @survey123 ,

Thank you so much for your answer. I was on the lands catched data. This is a great notice! I'm cooking a project with Survey123 and I hope show results this year with Esri Perú Conference 2017.

#staytuned
