### ISSUE TITLE
Changing Title for Survey Doesn't Work

### ISSUE THREAD

**Issue by ochotona** [Esri/Survey123Community#342]
After you have created a survey, if you click on "Settings" > "General" and then type in a new title for the survey, it doesn't update the survey to this new title. 

Note in the screen capture below that even though a new title has been entered, the survey itself is still called "Form 1." If you exit from the settings tab, this does not cause the survey title to update to the new name.

This is version 1.2.18.

![title_change](https://cloud.githubusercontent.com/assets/15622956/13377321/afe2b3e2-dd8a-11e5-9385-60b61e530046.jpg)

**Comment by sealjack** [comment]
we have the same issue here though on 1.4.30.  Also the form title keep shown as Form x on iPad despite it's been changed to something more meaningful.

**Comment by survey123** [comment]
@sealjack @ochotona 
This issue is now fixed.
Please [download the latest version (1.6) of Survey123 Connect for ArcGIS](http://doc.arcgis.com/en/survey123/download/)

To stay tuned on the latest releases please join our [GeoNet Group](https://geonet.esri.com/groups/survey123)
