### ISSUE TITLE
Constraint: 2 digits necessary (neither more nor less)

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#343]
Hi all, 
I managed to constraint the data input to only numbers and maximum 2 digits with `regex(., '^[0-9]{2}$')` but the number has to be exactly 2 digits. How can achieve this?

**Comment by GISSupport** [comment]
Just two numbers on a line should be matched by (^[0-9]{2}$)

**Comment by nicsi76** [comment]
so just without `., `?

**Comment by spatialdude** [comment]
Hi Nicole

You will find in the next update we've introduced support for input masks. Which make such constraints very simple and you won't need to use regex expressions.

**Comment by nicsi76** [comment]
Thanks, that will be really helpful!

**Comment by GISSupport** [comment]
Try it and see what happens :)

**Comment by nicsi76** [comment]
Only putting `regex('^[0-9]{2}$')` doesn't help :(
Additionally I need to make sure that the first number is not a 0. So 10 is allowed but not 1 or 01.

**Comment by nicsi76** [comment]
Sorry, it's working in the app, in connect it wasn't validating correctly. 
Thanks!

**Comment by GISSupport** [comment]
(^[1-9][0-9]$) will match 10-99

**Comment by GISSupport** [comment]
==-0987654
