### ISSUE TITLE
adjusting layout

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#346]
Is there a way to adjust the layout besides font color and background color? My client is asking for bigger text fields and bigger fonts in the select. In fact I also find it hard to click the correct choice.

**Comment by Thadius** [comment]
+1.. My client is also asking for the ability to increase font size.

**Comment by survey123** [comment]
Thanks!
Will try to get this done in our next update in April.

**Comment by survey123** [comment]
#151

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
