### ISSUE TITLE
define name of stored surveys

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#348]
When a survey is saved as draft or for sending it later or when it was sent it shows as a "name" the attributes with the values ordered by the name of the attributes (in my case agr_season: 1, bf_list: 2, ...).
In case of a survey needs to be edited it would be easier to find the right survey if a name could be specified that is drawn from the entered fields. In my case e.g. the name of the operator would be more helpful to identify the correct survey.

**Comment by nicsi76** [comment]
Update: on the tablet (Android) the attributes were shown in alphabetic order, on my phone (Android as well) they start with the first field but continue with an irregular order, seems to skip certain fields. On iPad (iOS 9.2.1) it shows the attributes in alphabetic order, too. 

I thought I could trick survey123 by giving my operator field the name a_operator but when the saving behaves differently on different devices that's not the best way to do it...

**Comment by survey123** [comment]
Closing.
Check this: https://geonet.esri.com/groups/survey123/blog/2015/08/23/understanding-the-instancename-setting

**Comment by nicsi76** [comment]
Thanks!
