### ISSUE TITLE
Survey questions are not used in the Feature Service as aliases and are not available via AGOL

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#35]
When a survey form is created and uploaded to ArcGIS Online it does not save the Field names in the Feature services as field aliases any other format.  When reviewing the data it will be hard to know what question is being reviewed with out understanding of the data schema by reviewers.
Also we have to build a review application and we need to display the questions in same format as were presented in the survey application and there is no way for the applicaiton to pull that information with out code to read in xml files of survey forms.

**Comment by survey123** [comment]
Hi Deepti. Just to be clear: do you want us to store the 'label' in your XLSForm as the 'alias' for the field?

**Comment by deepti10** [comment]
Yes, that would be ideal.

Thanks
Deepti

**Comment by jmirmelstein** [comment]
@survey123 We have experienced the same issue.  It is important that we also consider Localization on this one.  In our case, we have two labels defined: label::English and label::Dutch.  The user should be able to choose which of these localized labels get used by the resulting Feature Service.

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Let us know if this works now you and we will close issue.
We will use the 'label' in your Survey to define the aliases. We will not let you decide what language you want, but you can always use the language you want in the label...

**Comment by survey123** [comment]
Closing. Fixed.
@deepti10

**Comment by jmirmelstein** [comment]
@survey123 We have two label fields specified in our form and the aliases do not honor the XLSForm spec's 'default_language' property.  For example, my default language is English, but the aliases always show in Dutch.  How can I get English aliases in this case?  Shouldn't it honor the default language?  What is being used to determine which of the label fields are used as the alias?

**Comment by mhogeweg** [comment]
have you tried setting the default language in the [settings](http://xlsform.org/#settings) tab of the spreadsheet?

**Comment by jmirmelstein** [comment]
@mhogeweg - yes, the default language is honored by Survey123Connect and the Mobile App for field display, but not for the hosted Feature Service aliases.  So even if my default language is English, the aliases show up in Dutch #whatsupwiththat
