### ISSUE TITLE
Select One Display in Android

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#351]
I just updated Connect to 1.2.50 and Android app to 1.2.77. When I have a select_one list that is greater than 6 items, after selecting an item from the list, it does not display in the data box after the drop down window closes. Pressing the Show Data Values button shows that the data is selected, it just will not display on screen. If my select_one list is less than 6 items, then the selected data value displays properly.
Thanks,
--gary

**Comment by nicsi76** [comment]
I experienced the same, didn't relate it to the number of choices though.

**Comment by survey123** [comment]
Adding to backlog.
Problem is understood.
Thanks for reporting.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
