### ISSUE TITLE
ParentRowID not populated in Repeats Related features/objects

### ISSUE THREAD

**Issue by jeff3780** [Esri/Survey123Community#353]
![capture](https://cloud.githubusercontent.com/assets/5103483/13412295/3cb878f2-df10-11e5-9450-3eac32143ed7.PNG)
I am using repeats with an image field in each repeat section so that I can have multiple images all related to the same parent form.  I have another use case with an image and a geopoint in the repeats block so that I can create related features to the feature created for my parent form.  In other words I have two different test environments.  SurveyConnect correctly creates the feature service in either case, in one situation with two feature layers, the other with a feature layer and a table.  If I drill into the RESTAPI, I can see the relationship class is properly created in each situation.  However, when I execute the form, it properly uploads the records to the parent and the related layer or table, but I can't navigate the relationship class.  It appears to me the ParentRowID is the foreign key in the related layer/table, and it is not being populated.  I have attached a screen shot of a query using the REST API that shows this.  The screen shows the empty ParentRowID, but it is the same for all records in the related table.  I guess my bottom line question is: should ParentRowID get populated?

**Comment by survey123** [comment]
Hi Jeff. We are investigating this. Stay tuned. Thanks for reporting.

**Comment by survey123** [comment]
@jeff3780 
Hi Jeff. This issue has been fixed. The app build number is 1.2.89. Currently it is available in the Google Play store. We have submitted the fix to the iTunes store as well. We estimate it may take between 4 to 5 business days for the update to be approved by Apple.

Closing issue.

**Comment by jeff3780** [comment]
Tested out on Android on my end and it is working as expected now.  Related records created from Repeats block are navigable in the attribute popups and dialogs.  Nicely done!  Thanks!

**Comment by survey123** [comment]
Awesome! Thanks for confirming.
