### ISSUE TITLE
fix viewport for scrolling only up and down

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#354]
To improve the user experience with the Survey123 App I would prefer the viewport of the form to be fixed for scrolling up and down only, not moving the form left and right while dragging it down. 
![image](https://cloud.githubusercontent.com/assets/11991954/13421581/e49fd934-df97-11e5-9d15-3a43fab23663.png)

**Comment by survey123** [comment]
Closing.
Fixed.
https://geonet.esri.com/groups/survey123/blog/2016/03/09/1289-critical-update-to-the-survey123-mobile-app

**Comment by nicsi76** [comment]
Thanks, well done!
