### ISSUE TITLE
relevant group/fields toggle when double clicking radio

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#357]
I have a select_one yes/no field used for a group's relevant reference: ```selected(${yes_no_field},'yes')```
This works initially. When yes is chosen, the group appears.  However, subsequent clicking of yes causes the group to hide and show. 'yes' remains selected the entire time.

Android Samsung Tab A and Galaxy S5

**Comment by survey123** [comment]
Can you please share your Form?

**Comment by survey123** [comment]
@DShokes 
Never mind. I see it. Good catch.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
