### ISSUE TITLE
Minor changes should be possible in Survey123

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#358]
At the moment I have to go through AGOL if I want to change the description of my already published survey. (Or doing the changes in Connect and publish it again.) It would be nice to be able to do some minor changes also in Survey123, like adding a picture for the survey or editing the description.

**Comment by RKnepper3** [comment]
Triple like this, After collecting a days worth of data it is common to get minor feedback items which require an update and republishing cause existing data to be blanked.  I know we can download first but is there an easy way to add back in the data?

**Comment by survey123** [comment]
Thanks @RKnepper3 @nicsi76 for your feedback.
Check out the latest version of Connect (1.4.30) and the App (1.4.28). You will now be able to change lots of things without having your Feature Service replaced: the title, description, summary, thumbnail, image size threshold, style, map properties as well as any label, grouping, media, calculations, constraints, defaults etc  Only your changes to the survey require a feature service schema change, we will replace the feature service.
