### ISSUE TITLE
Update description in survey

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#359]
I updated the description of the survey in AGOL, also did some minor changes on the feature services. But it seems like they are not taken back to the survey package. Although my list of available surveys shows me that the survey was updated (with the according time) when I open the survey it still shows the old description. 

As said in issue #358 it would be nice to do these changes also in Survey123. At least it would be nice to have the description available in Survey123...

**Comment by survey123** [comment]
Thanks @nicsi76 for your feedback.
Check out the latest version of Connect (1.4.30) and the App (1.4.28). You will now be able to change lots of things without having your Feature Service replaced: the title, description, summary, thumbnail, image size threshold, style, map properties as well as any label, grouping, media, calculations, constraints, defaults etc Only your changes to the survey require a feature service schema change, we will replace the feature service.
