### ISSUE TITLE
Can't create new Surveys in Connect 0.0.41 (Windows)

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#36]
Hi,

 When I click on create new survey in connect, I get the following error.

![untitled](https://cloud.githubusercontent.com/assets/1273440/6812018/5ab192f2-d229-11e4-9fcb-b678a6f0c450.png)

 any ideas?

**Comment by survey123** [comment]
Thanks. Will get this fixed in the next update (expected March 27, 2015)

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Let us know if this works now you and we will close issue.

**Comment by Cintruenigo** [comment]
Fixed! Thanks!
