### ISSUE TITLE
Integer Fields Required on Device but not in xlsx Form

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#360]
Since upgrading my Survey123 App to 1.2.77 (Android) and Survey123 Connect to 1.2.50, integer fields are acting as required fields in the app, when they are not set this way in Connect.
Thanks,
--gary

**Comment by billingsmc** [comment]
I've noticed the same thing on my Android device today. All integer fields are coming up as required even though the XLS form does not have that field populated. Also, minimal (drop down) menus are not showing some choices when selected. One of my select_one questions has a default value but it doesn't show up in the form.

**Comment by survey123** [comment]
Thank you for letting us know about this one - yes - this was recently unexpectedly introduced. We will fix asap.

**Comment by survey123** [comment]
The fix is available in the Android store. Check 1.2.89.
We submitted the fix to the iTunes store as well. We expect it to be available in the next few days.
Closing issue.
