### ISSUE TITLE
Several geopoint fields in the form

### ISSUE THREAD

**Issue by anaymushina** [Esri/Survey123Community#361]
I've encountered an issue of adding two geopoint fields on the form. It's possible to create such a survey in Survey123 Connect - no warnings or errors. But, when you try to send a survey from devise  - you get an error - it can't be synchronized.

Do you plan to support a workflow with several maps in the survey? 
We have a case - in the survey we need to select two locations - home area of a person and work area of the person. Now we can provide this only using a list of districts to select. It would be cool to select a district of person's homeplace using a map, not a list of districts.

**Comment by travisbutcher** [comment]
Within one area it is not possible to have more than one geopoint.  
What you can do though, is to create a repeat and put a geopoint in there.  This would allow the user to enter several different geopoints as part of the survey.
