### ISSUE TITLE
Automatic formatting of text

### ISSUE THREAD

**Issue by nicsi76** [Esri/Survey123Community#362]
My client wants to write the name of the operator all in capital letters to have it uniform in the database. Is there a way to force the device to use only capital letters for a certain text field? I know I can use the constraints to check for the entered data but it would be easier to make the user use only capitals. Thanks for hints!

**Comment by survey123** [comment]
Input masks are in experimental mode at the moment, but you may want to try:
* A mask like this AAAAAAAAAA>  will force a string to be no more than 10 A-Z characters in length and all in upper case letters.
* The above will NOT automatically make what you type uppercase, but you will not be able to submit anything that is not uppercase
* For more info on input masks see: 

 https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
