### ISSUE TITLE
Calculation + is concatenating numbers instead of adding them

### ISSUE THREAD

**Issue by tgregorius** [Esri/Survey123Community#364]
I've successfully used the calculation column for other things but I'm now working on a particular example where the survey is asking to rate a number of items on a scale of "frequent", "occasional" and "never" (labels column in Choices), to which the values 3, 2 and 1 are assigned respectively via the names column.

I now want to perform basic calculations on these scores i.e. sums.

But when I add up the variables up in the calculation column, rather than adding them up as say 2 + 3 + 1 = 6, it concatenates them into the value "231".

I can't see anything wrong with my syntax, which is basically ${var1} + ${var2} + ${var3}

The variable for the calculation is defined as integer type, but it looks like Survey123 treats the calculation as text rather than numbers, appending the strings instead of adding up the numbers?
 
Anyone had the same issue? Suggestions?

Many thanks

**Comment by survey123** [comment]
Easy!  Cast your values to integer as follows:   int({var1} + int(${var2})

**Comment by tgregorius** [comment]
Duh - thanks!!
