### ISSUE TITLE
ETA Production release date

### ISSUE THREAD

**Issue by sunyu0530** [Esri/Survey123Community#366]
Hello,

Do you have an ETA for survey123 production version release date?
we are very interested in using the survey123 App to on our production but unfortunately our IT policy doesn't allows any beta product to be used in production work environment. 

Thanks

**Comment by survey123** [comment]
Our plan is to release on mid-June 2016.

**Comment by sunyu0530** [comment]
@survey123 

Hello,
In addition to this question, how will the App being released?
will it be a update version from the current App or it will be a new App that we need to search from Google Play/App Store, download and install, and uninstall the old App?

Thanks

**Comment by survey123** [comment]
Same app, just an update. To end users, there will be no noticeable difference between the app they are using today (in beta) and the General Release.  You will see the app improving in quality and features, but overall no changes are planned in terms of workflows.

**Comment by sunyu0530** [comment]
@survey123 

Thanks, that answers my question, look forward to the production release.
