### ISSUE TITLE
calculate field fails inside a repeat block

### ISSUE THREAD

**Issue by kengorton** [Esri/Survey123Community#368]
I have a calculate field that I want to show the sum of two previous fields. It works until I nest the three fields inside a repeat block at which point the sum field does not calculate anymore. I removed the repeat block and the calculate field functioned correctly again. I restored the repeat block and it failed again. 
Thanks,
Ken

**Comment by survey123** [comment]
Duplicate of #233 
Thanks for reporting Ken.
