### ISSUE TITLE
How do I delete a Survey?

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#37]
At some times you may want to delete a Survey, particularly if you are going through some trial and error trying to get it right, or simply when something went South and a survey was left orphaned in your account. If that is the case, you may see an error like this one while attempting to publish:

![untitled](https://cloud.githubusercontent.com/assets/1273440/7879173/e458fa98-05a2-11e5-9522-2a0fe5eb2a56.png)

  The process for deleting Surveys is not automated at the moment, so here are some tips to get things cleaned up well:

**Survey123 items in ArcGIS Online**: As you probably guessed already, when you upload your XLSForms to ArcGIS we create a Feature Service, a Web Map and a Source Code item which holds your xForm, assets and other metadata.  We keep all of these items in a folder named after your survey.  You can clean up these items manually from your own account in ArcGIS.com (Contents tab). Alternatively, you can use the Survey123 Web Site. In the Survey Gallery, simply hover your mouse over the Survey and click on the trash can icon.

![delete1](https://cloud.githubusercontent.com/assets/1273440/6861784/482808ce-d3f9-11e4-9fe1-6a29da1b8d8d.png)

Sometimes, if the process for creating a new Survey from Connect fails, you may get the folder created but not all items in it. If that is the case you will not get to see the Survey in the gallery, and hence there will be no way to delete other than going straight into your Contents tab in ArcGIS and deleting the folder manually.

**Survey in your App**:  Surveys downloaded to your Survey123 App will become orphaned once you delete their corresponding ArcGIS Online items.  To get rid of orphan Surveys, simply select the survey and use the Delete option in the menu.

If you are running the Survey123 App in your desktop (Mac or Windows), navigate to C:/users/YourUser/ArcGIS/MySurveys (in Windows), or your home/ArcGIS/MySurveys in Mac and delete the directory holding the Survey you want to delete. The name of the folder is cryptic, but if look inside you will see files with your Survey name... 

**Surveys in Survey123 Connect**: In Survey123 Connect click on the survey you want to delete, and then use the browse dialog to navigate to the files on disk. Go up one level and delete the folder holding all your Survey files. Done!

![delete2](https://cloud.githubusercontent.com/assets/1273440/6861831/5731e276-d3fa-11e4-9f63-3ea44cccba11.png)

All of this will get easier, but at the moment this will get you through.

**Comment by dmypubmail** [comment]
I tried logging into ArcGIS.com to delete my "orphaned" survey.  I do not see any content
for my survey.  Yet when I try to publish from survey123 connect, I get that "user folder not
found error".  What am I doing wrong ?  Thank you for any feedbacck !

**Comment by JohnHasthorpe** [comment]
You will need to go to www.arcgis.com and sign in. In MyContent, delete the directory containing the survey (and its contents). Once deleted you can republish the survey from connect.

**Comment by JohnHasthorpe** [comment]
If the above does not work.
1- Make sure the iteminfo file is gone in the local Survey directory (access it via the yellow folder button in Connect). If it is still there. Delete it.
3- Then re-publish

If the above still does not work:
1- Make a copy of your XLSfile (and media folder if you use images)
2- Delete the entire Survey folder in both ArcGIS.com as well as your local machine
3- Import your XLSfile as a new survey and copy again media files if needed
4- Publish

Please let me know how you get on

**Comment by dmypubmail** [comment]
thank you - this worked for me.

looking for an example of an xlsform that uses repeat groups.
I don't see a tutorial anywhere on how repeat groups are set up.

thank you,  Doug

**Comment by JohnHasthorpe** [comment]
In connect, create a new survey from the community Arrest Form sample. 
This provides a good example of repeats.
