### ISSUE TITLE
Contraint setting does not work for Dates.

### ISSUE THREAD

**Issue by delfavero** [Esri/Survey123Community#370]
**constraint**
.<= today()

This has no effect on data validation. Possibly due to use of epoch dates? Is there a workaround?

**Comment by survey123** [comment]
Hi. This is a known limitation. 
Please vote here: #55

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
