### ISSUE TITLE
repeat group photos - where to the export too?

### ISSUE THREAD

**Issue by Emma-PV** [Esri/Survey123Community#371]
Hello!
I am having issues accessing my photos that are captured in my repeat groups when accessing the data on AGOL and even when I use FME to download the data to a file GDB.
Is anyone able to give me a few pointers?
Do I need to allow attachments?
I have also noticed that the photos that are captured in the form are only accessible through AGOL and not when I download it to a GDB.
Thanks in advance.

**Comment by survey123** [comment]
Hi @Emma-PV 
When you add a repeat to a Survey, we create a related table to persist questions in that repeat. If you add an image question within the repeat, the attachments are added to that related table.
ArcGIS Online does not support displaying attachments within a related table.
If you download the data to ArcGIS for Desktop, as a file geodatabase, you should be able to see your attachments. Simply identify the point, then access the related table and click on the attachment.

If it does not work as described with your existing surveys, please publish a new test survey with the latest version of connect and try again. 
The latest connect is 1.4.30 and it includes some enhancements to how attachments are handled. http://doc.arcgis.com/en/survey123/download/
