### ISSUE TITLE
Long Descriptions causing Collect Data button to be hidden

### ISSUE THREAD

**Issue by travisbutcher** [Esri/Survey123Community#372]
We have published a form with a large description this is causing the box to resize to be to large to fit on an iPhone properly.  
![image](https://cloud.githubusercontent.com/assets/1291442/13787635/f04b7c22-ea99-11e5-8cd3-348652e5ca01.png)
This is hiding the Collect Data button and there is no way to scroll beyond this.

**Comment by survey123** [comment]
Thanks Travis.

**Comment by survey123** [comment]
![142276](https://cloud.githubusercontent.com/assets/10968332/13926462/ad54a484-ef49-11e5-8788-ad9a8d0af687.png)

**Comment by survey123** [comment]
Fixed in 1.4.x
Closing.
