### ISSUE TITLE
Date and Time Bug (When using =today() or =now() in the default field)

### ISSUE THREAD

**Issue by teachcalds** [Esri/Survey123Community#373]
We used the =today() for date and =now() for time (Also trying =now()-today() too) and although they appear to work in the form by displaying the date and time, they actually don't. If I build a form with Date and Time set this way on March 1, 2016 at 7:50 AM (for example), when I open that same form the next day (March 2, 2016 at 10:30 AM) or two weeks later (March 15, 2016 at 2:00 PM) ... The original date and time of March 1, 2016 at 7:50 AM will be displayed (It becomes hard coded). From our testing of the bug, the date and time are set in stone the moment we save the spreadsheet. It will never change after that in the form unless you manually click the date and time to select the accurate ones (But that defeats the purpose). 

For now we have not used the =today() or the =now() commands in our forms we are building for our field personnel. We have made it so that the user will be forced to select the current date and time until this issue can be resolved.

**Comment by survey123** [comment]
Hi! Thanks for your post!
The correct syntax is today() and now()
When the expressions are applied to the default column, the current date or time as of when the Survey instance is open will be used. If you edit the Survey from your Draft, Outbox or Sent folders, the value will not be recalculated. Default expressions do not overwrite values that the user may have entered or left alone.
You should always get the current date and time when the Survey is open for the first time. That is, when you tap on Collect.  Below is an example of the syntax. Hope it helps.

![untitled](https://cloud.githubusercontent.com/assets/10968332/13787798/9d33ca70-ea9a-11e5-954e-23c30db068d1.png)

**Comment by teachcalds** [comment]
For some reason we were using the =today() and =now() just like in Excel. Obviously it didn't work properly. Thanks for showing us the correct way, it works properly now!!!!
