### ISSUE TITLE
Enable Others to See Survey Results Dashboards

### ISSUE THREAD

**Issue by terryiffland** [Esri/Survey123Community#376]
I have created and published a survey for another person, but they are not able to see the survey results from the Survey123 site.  I've contacted Esri support and was told only the person who has published the survey can see the results and results dashboard at survey123.arcgis.com. 

If this is true, I'd like to suggest an enhancement to Survey123.arcgis.com that will allow users to be designated as survey result viewers. Implementing this capability provides a couple benefits:
•Eliminates the need to grant publisher privileges to many users. With lots of publishers things can get disorganized and inefficient.  Instead, I'd prefer to have a select group of people permitted to publish surveys.
•Avoids the need to develop dashboards when a survey is created. Using the general view may be sufficient for a lot of cases. We can see the data in a webmap, but currently the statistical display will need to be built for each survey.

**Comment by cconnolly91** [comment]
+1

**Comment by lmwinton** [comment]
+1

**Comment by sunyu0530** [comment]
+1

**Comment by yrebois** [comment]
+ 1 if the survey is used to a group, the group should access to the survey123 corresponding dashboard

**Comment by survey123** [comment]
@yrebois 
@sunyu0530 
@lmwinton 
@cconnolly91 
@terryiffland 

What if?
* We let you share, as usual, the Survey with a Group, so people can use the Survey in the field to capture data (field users).
* We also let you share the Survey with another Group (could be the same, but we assume in some cases you will not want field users to see the results of the Survey) so folks in that group can see the results of the Survey.

With the above, we would expand the Survey123 web site so as the author of a Survey you can share with Field Users, and also with Stakeholders.

Would that cut it for you?

**Comment by cconnolly91** [comment]
That sounds good to me!

**Comment by sunyu0530** [comment]
That will definitely meet our needs.

**Comment by ksadrakPWC** [comment]
+1 Would love to see this.

**Comment by anaymushina** [comment]
+1

**Comment by lmwinton** [comment]
Yes, that would be great.

**Comment by terryiffland** [comment]
This would be even better than I originally envisioned.  

Sorry - I've been away from work for a while. Is this being worked on?

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. The ability to share your survey results with stakeholders was added in the December (1.10) release. See http://doc.arcgis.com/en/survey123/browser/analyze-results/sharesurveyresults.htm for more details.
