### ISSUE TITLE
Set the max size of images submitted in Survey

### ISSUE THREAD

**Issue by Thadius** [Esri/Survey123Community#379]
Is there a way to change the default camera app when using Survey123 on IPAD?  Our project requires pictures, but the resolution only needs to be 800x600.

**Comment by survey123** [comment]
Thanks Thadius. I changed the title of this issue after our email exchange to reflect the requirement more explicitly. We are aiming at resolving this in our International Children's Book release in early April. 

Our intent is to provide an option so Survey authors can limit the size of images sent to the Feature Service.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
