### ISSUE TITLE
Tiny Forward Button in Repats (Android Only)

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#380]
inside of a repeat, once you have more than one item, if you hit the go back button, the forward button is very, very, very, small and takes many attempts to tap it. This is similar to the delete button in the repeat issue that was recently closed.

thanks,

--gary

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
