### ISSUE TITLE
Conditional Form not showing up on the iphone also with poor performance loading time

### ISSUE THREAD

**Issue by sunyu0530** [Esri/Survey123Community#381]
Good morning,

I am trying to make some enhancement with my current ASB FQA  (Field Quality Assessment) form with some conditional questions.
The conditional questions are working fine on the survey123 connect preview.
However it doesn't show up on the phone after you select the answer.

E.g When you choose the answer of question "What kind of FQA are you going to perform?)
if you choose "FQA and Leak FQA", on the preview both FQA and Leak FQA gouped questions showed up. 
however on my iPhone 5 after selection the form never shows up. 
![fqapreview](https://cloud.githubusercontent.com/assets/17747985/13879562/799f9304-ecee-11e5-8707-f8f19783a4bd.png)

Also it takes about 2 min 30 seconds average to load the survey.
I hope to get some tips from you.

Thanks

![img_2385 1](https://cloud.githubusercontent.com/assets/17747985/13879506/2ef8b4a2-ecee-11e5-93fe-874a87a601d7.PNG)

[ASB FQA Redesign - Copy.xlsx](https://github.com/Esri/Survey123Community/files/179724/ASB.FQA.Redesign.-.Copy.xlsx)

**Comment by survey123** [comment]
@sunyu0530 
Hi. Thanks a lot for your feedback.
* Relevant expressions not working on iOS: This is an issue that we need to investigate further.  Indeed, your Form works in Connect, but does not in iOS. Stay tuned.
* Performance: The performance hit is a combination of Calculations and Relevant expressions. 
    * Your Survey took 36 seconds to render in Connect in my Windows machine
    * If removing all Relevant expressions, loading time went into 11.6
    * If removing all Calculations, loading time was 6.1
    * If removing both Relevant and Calculations, loading time was 3.2
Obviously, you want Relevant and Calculations so I had a closer look at your expressions:
    * Tip on Relevant expressions: Relevant Expressions used at the Group level automatically apply to all questions within the Group. After eliminating all duplicated Relevant expressions, I was able to get the Survey to load in 20.7 seconds. Still too much time, but it is a step. I am including below the modified Survey.
    * Issue with Calculations: Turns out that Survey123 computes all calculations, even if they apply to non-relevant questions. This is a software defect that we need to look at. 

 We will try to address the two software defects that are affecting you. Stay tuned and thanks for your feedback.

[ASB_NoRel2.xlsx](https://github.com/Esri/Survey123Community/files/182679/ASB_NoRel2.xlsx)

**Comment by sunyu0530** [comment]
Thanks,

That was very helpful.

**Comment by survey123** [comment]
@sunyu0530 
We finally found the problem to your issue with relevant statements not working on iOS. 
Will provide a fix in the September release.

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
