### ISSUE TITLE
Connecting to my Portal for Arcgis error

### ISSUE THREAD

**Issue by micheletrentini** [Esri/Survey123Community#382]
Hello,
I'm currently trying to connect to my Portal:
Ver. 10.4
Hosted server configured
No Data Store as we have our geodatabase though SQLServer managed by ArcGis Server.
see (http://server.arcgis.com/en/server/latest/administer/windows/configure-hosting-server-for-portal.htm)

When I try to add to the portals list for the signin settings I recieve The error you see in the png attached. (portal url deleted for privacy)
Is it compulsory using Data Store?
![immagine](https://cloud.githubusercontent.com/assets/17930136/13881396/121d024c-ed21-11e5-8a6b-2e2bbb64da91.png)

Thanks in advance

**Comment by survey123** [comment]
Hi Michael. Using the ArcGIS Data Store is required at the moment.
