### ISSUE TITLE
Export FGDB from Portal

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#384]
I cannot export the results from our surveys to a fgbc from My Content on Portal anymore. Is this something that has been eliminated?

Thanks,

--gary

**Comment by survey123** [comment]
Hi Gary, are you sure you are trying to export from the Feature Service item? Nothing has changed.

**Comment by bowlesgsrcx** [comment]
Yes. But as we dig into this it might be something with our upgrade to Portal 10.4

Good to know nothing has changed on the Survey123 side.

Thanks,

--gary

Gary H. Bowles
GIS Database Administrator II | Seneca Resources
Office : 412-548-2544 | Cell Phone: 412-334-5273

**Comment by bowlesgsrcx** [comment]
This has been fixed. it was an issue on our end. We have recently migrated our server environment and on Friday we migrated the hosted server. This caused the existing feature service links to break. We were able to recover all of our data from our previously published surveys, re-publish all of the surveys and we are back in business.
--gary
