### ISSUE TITLE
iPhone 5 media images and mp3 files 

### ISSUE THREAD

**Issue by icenole** [Esri/Survey123Community#387]
I have media images in

**Comment by icenole** [comment]
I have media images and mp3 files in my Choices tab.
list_name	               name	         label	         image	          label::language1	media::audio

stop_type	                Sign	         sign only	          sign.jpg		                                 vehicle117
stop_type	                Shelter	 shelter	          shelter.jpg		
stop_type          	Hub	         transit Hub	  hub.jpg		
stop_type	                Center	 transit center	  center.jpg	

Works fine in test mode, but when I publish the fields do not show up on my iPhone 5 Survey123 but do in androids.  Ideas?

**Comment by survey123** [comment]
Hi. iOS is case sensitive. Windows and Android are not. Double check the capitalization.  As you make changes to your Survey in Connect and Publish again, make sure you delete the Survey from your device first to avoid getting the different versions confused in your phone.

**Comment by icenole** [comment]
All of the names in the choices tab are small letters.  I deleted the previous surveys on my phone and upgraded to iOS 9.3.  Still no image or media files displayed.  Here is my choices tab:

[choices.docx](https://github.com/Esri/Survey123Community/files/186336/choices.docx)

**Comment by survey123** [comment]
are the files in your media folder also all lowercase?

**Comment by icenole** [comment]
yes

**Comment by survey123** [comment]
Try with png files instead.

**Comment by icenole** [comment]
Not only did the png file not work, they don't show up on my Survey123 Connect either.  The one caveat is that I only changed one file to .png, all the others are still jpg.

**Comment by survey123** [comment]
Thanks. Lets get on a screen-sharing session. I am sure we are missing something obvious. Please email survey123@esri.com so we can start a skype session.

**Comment by icenole** [comment]
Works great now - thank you!  Now to figure out the mp3 files
