### ISSUE TITLE
Consume Feature Hosted Service from enterprise GDB through AGOL

### ISSUE THREAD

**Issue by sunyu0530** [Esri/Survey123Community#392]
Related to issue #390 

I want to store the survey data directly to our enterprise database.
Is it possible to use a feature hosted service from AGOL to do that?
We are currently upgrading our ArcGIS Server Manager into 10.3 and we do have 10.3.1 ArcMap
Although our database is still on 10.1
 
My concern is how the schema settings should be from the enterprise database?
I knew that if you publish the service from Survey123 connect, and extract the data to a FGDB, every question will have it's own domain after export the data into a FGDB. 
Also there are relationship class and table come along with it. (e.g Image below)
![image](https://cloud.githubusercontent.com/assets/17747985/14025323/e95b8d2c-f1c3-11e5-9e17-bc622b9f5e9f.png)

Here is my imagined steps:
1. mimic and create all the feature class/table/domain schema the same from exported FGDB (feature layer created through survey123 connect) into the enterprise database.

2. Publish the feature class on AGOL as hosted feature service. 
3.on Survey123 Connect, create the form in excel using same schema from the feature class that was created in enterprise geodatabase and add the Feature Service Url for the hosted feature service under Settings-Data tab.
4. Hit Publish (will it overwrite the hosted feature service?)

Thanks

**Comment by survey123** [comment]
Hi @sunyu0530 

Try the latest version of Connect and these steps:
1) Create your Survey and Publish
2) Log into http://survey123.arcgis.com, click on your Survey, then go to Data and Download your Survey as a FileGDB
3) Add the FileGDB (empty) into ArcGIS for Desktop and create a new Feature Service in your own Server
4) Change the submission_URL of your Survey  http://doc.arcgis.com/en/survey123/create-surveys/xlsformsubmissionurl.htm and publish Survey again

If you have an existing Feature Service, the process would be the same in step 4, but you will need to make sure your Survey is compatible with your Feature Service schema.

**Comment by bnadler** [comment]
The above link is not valid. Please update as I would love to get these instructions

"Change the submission_URL of your Survey http://doc.arcgis.com/en/survey123/create-surveys/xlsformsubmissionurl.htm and publish Survey again"

**Comment by tedrick** [comment]
In the December release our help was restructured.  Information on publishing a survey to work with existing ArcGIS Server services is at http://doc.arcgis.com/en/survey123/desktop/create-surveys/survey123witharcgisserver.htm

**Comment by henry296** [comment]
this link is also no longer valid.   http://doc.arcgis.com/en/survey123/desktop/create-surveys/survey123witharcgisserver.htm

**Comment by tedrick** [comment]
It was renamed to better reflect the topic: http://doc.arcgis.com/en/survey123/desktop/create-surveys/survey123withexistingfeatureservices.htm
