### ISSUE TITLE
Sum calculation on fields sometimes adds, sometimes concatenates

### ISSUE THREAD

**Issue by bizzy1971** [Esri/Survey123Community#394]
I have several fields in a form, let's call them A, B, and C.    Below them i have a total field which should be the result of adding the 3 previous fields. In the total field, i have set this formulate under calculation: ${A}+${B}+${C}.    

The issue is that sometimes 1 + 1 + 1 in A, B, and C equals 3, sometimes it'll be 111.   Often when when you enter a new value, it just appends it next to the ones already in the total field.

**Comment by survey123** [comment]
Hi!
Try casting the values to a number. For example:
 Dont do this: ${A} + ${B}
 Do this: int(${A}) + int(${B})

**Comment by bizzy1971** [comment]
Sweet, had to cast the integers!
