### ISSUE TITLE
Unable to download fgdb

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#395]
So this might have something to do with issues I also had on survey size.  I have a survey with 75 surveys collected and about 300 photos.  When I try to export via Survey123 it just spins and spins.  It takes forver and never actually completes.  I then tried to go into AGO and export it, when I do that it ends up saying Error exporting data to filegdb format.  How can I get this data out?

**Comment by RKnepper3** [comment]
I am able to download the csv via survery123

**Comment by RKnepper3** [comment]
I also went into AGO and looked at the feature service, I am unable to edit features.  The edits do not save

**Comment by survey123** [comment]
Ron. We are going to assign an ArcGIS Online Tech Support analyst to this particular issue. You will hear from Esri shortly.

**Comment by RKnepper3** [comment]
Just fyi for anyone else here, it seems if you have a failed upload issue with Survey123 the data that is sent up likely has some corruption.  ESRI had no way to pull an actual FGDB out with the attachments.  We were able to create a replica without attachments then I had to manually pull down the attachments and reattached them to my records one at a time.  If you have ArcGIS Pro, its not too bad to do manual.

**Comment by deanmostad** [comment]
I have been able to download a FGDB with attachments ...

Check out the YouTube Video called: Downloading All Image Attachments from ArcGIS Online Feature Services.

https://www.youtube.com/watch?v=Fw1K8rmV8O4

**Comment by RKnepper3** [comment]
I know you can, I have done it many times either via AGO or Survey123 website.  The issue is if you have a corruption of your data being uploaded you can not download the fgdb.  It's something ESRI is aware of but there isn't much you can do other than manually recreate

**Comment by RKnepper3** [comment]
The updates to Survey123 look like this will be a non issue anyway.  Thanks everyone

**Comment by deanmostad** [comment]
Got you, I misunderstood your point. Have a good day.

**Comment by survey123** [comment]
Thanks to all. Closing issue.
