### ISSUE TITLE
select_multiple type fields do not display drop down menu when creating geoform survey using Survey123Connect with ArcGIS Online.

### ISSUE THREAD

**Issue by WeASeL-Antigua** [Esri/Survey123Community#396]
[Here's the Geoform](http://arcg.is/1UsHjmS) that I tried to author with ArcGIS Online using the [feature layer](http://arlan.maps.arcgis.com/home/item.html?id=f04c0e9a02f64d548520e586c4a0e2c1) and Xform created with Survey123ConnectBeta software.
 
My issue:
 
Fields of the "select_multiple" type are reverted to"text" fields in my ArcGIS Online Geoform.

![geoform builder](https://cloud.githubusercontent.com/assets/18103637/14067678/045ede5a-f438-11e5-9a66-d78c65f297c4.PNG)

The "select menu" option is not applicable to these fields. I suspect ArcGIS Online may not have the capabilities to host those field types as yet but are there any workarounds since the Survey123Connect surveys can't be shared publicly yet?

![survey123connect stuff](https://cloud.githubusercontent.com/assets/18103637/14067683/16a6e0d0-f438-11e5-9da0-7549ee77eb82.PNG)

**Comment by survey123** [comment]
Hi!
You are correct. Unfortunately, much of the Smart Form capabilities supported in Survey123 for ArcGIS are not supported by other apps in ArcGIS. GeoForms are quite limited in terms of Smart Form capabilities. We are working on a web-flavor of Survey123 Forms. Think of it like a GeoForm on steroids, but this is still a work in progress. We are aiming at Web Forms in the second half of 2016.

**Comment by WeASeL-Antigua** [comment]
Looking forward to that.
