### ISSUE TITLE
Unable to share created survey with my organization.

### ISSUE THREAD

**Issue by WeASeL-Antigua** [Esri/Survey123Community#397]
I have successfully created a survey with the survey123 Connect Beta app and uploaded it to my content in ArcGIS. I can successfully share the survey with my groups but I am unable to share with my organization. Selecting my organization and clicking OK, shows me a green checkmark indicating that the change was successfully applied. A simple refresh of the page shows me that the app was NOT shared with my organization.

**Comment by WeASeL-Antigua** [comment]
I think because of this issue, I cannot view my survey when I sign in on the Survey123 windows phone app.

![wp_ss_20160327_0003](https://cloud.githubusercontent.com/assets/18103637/14068073/eff886ce-f445-11e5-8665-b7fb82d4903b.png)

**Comment by survey123** [comment]
Hi. Thanks for the screenshot.
When you go to http://survey123.arcgis.com
Can you tell if the Organization check box is chedked as in the image below?

![untitled](https://cloud.githubusercontent.com/assets/10968332/14068097/30500d00-f42d-11e5-9a36-fcc5e81c5afb.png)

Please be aware that the App in your phone will NOT list Surveys that have been shared with Everyone. From http://survey123.arcgis.com you cannot share with Everyone, but you may have accidentally shared the Survey with Everyone from ArcGIS.com.

**Comment by WeASeL-Antigua** [comment]
I should have gave proper illustration initially.

Forgive me.

The survey is shared with all the groups that I am a member of but not with my organization through [Survey123.arcgis.com](http://survey123.arcgis.com). Trying to share with everyone is fruitless because as soon as I close the window shown below or refresh the page...

![share survey123](https://cloud.githubusercontent.com/assets/18103637/14070391/f0fe415c-f473-11e5-9b55-34233aaf2d87.PNG)


...I'm left with this.

![fruitless](https://cloud.githubusercontent.com/assets/18103637/14070475/f540835a-f474-11e5-8823-817a9830819f.PNG)


Yes, I am aware that I currently can't share with everyone through [Survey123.arcgis.com](http://survey123.arcgis.com) but the created Feature Service and subsequent web maps and web applications in ArcGIS online are all shared with everybody.

I was just worried that when using the official Survey123 app for Windows phone I still can't see my created survey even though it is successfully shared with groups that I am a member of through [Survey123.arcgis.com](http://survey123.arcgis.com)

![survey](https://cloud.githubusercontent.com/assets/18103637/14070585/565a1b5a-f476-11e5-863a-2a566c2030e0.PNG)


I just assumed that I would be able to view my survey using the official windows phone app.

**Comment by marikavertzonis** [comment]
when you unselect 'members of these groups' and only have 'members of my organization' selected, is your survey then visible on your device?

**Comment by WeASeL-Antigua** [comment]
That's the problem. I cannot select members of my organization as illustrated above.

**Comment by GeoJtaylor** [comment]
I am having the same problem.  When I check share with my organization, it unchecks itself as described above.  I can see my survey as an administrator, but no one else can.  I shared my form with everyone and with my organization via ArcGIS online, but this has no effect. Has anyone found a work around?

**Comment by survey123** [comment]
@WeASeL-Antigua  @GeoJtaylor @zhif7782 
We have updated the web site with many fixes. Please **clear the cache of your browser and load again http://survey123.arcgis.com** to share your Survey. If the problem persists, please add your comments again so we can track this down.
