### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by gzuknick** [Esri/Survey123Community#398]
I am having a few issues, three that are most likely related:

First the related issues:

When I try to upload my Survey to ArcGIS online the sign in screen goes grey and all I see is the spinning circle and it then becomes stuck.

I manually transferred the Survey to the Samsung tablet, created a few test surveys and then tried to upload them. I didn't get an error, however there is a red exclamation point next to the cloud, and they are not online so I assume they didn't get uploaded. 

I can't get the data from the tablet manually as it is in a SQlite database but is not able to be opened by the viewer that I have (SQLite browser)

Any help on any of these issues would be appreciated. as for version I just downloaded everything in the last 2 days Version 1.2.62 for the desktop app and 1.2.89 for the tablet app

A separate issue is the notes field. I entered a few notes to help guide the users, but don't see where they are displayed once the survey is being taken? Should they popup or is there a button to access them?

Thanks,

Greg

**Comment by nicsi76** [comment]
Hi gzuknick, 
The note field is displayed as a text between the fields you defined for the questionnaire like in this example:  
![screenshot_2016-03-23-13-01-48](https://cloud.githubusercontent.com/assets/11991954/14172695/a7e14d8e-f739-11e5-9520-b90f796fa01a.png)

For the upload problem: I faced the issue of the spinning circle before and not being able to upload the data. Did you try to login before uploading (and downloading surveys)? Unfortunately until now you are not prompted to the login page automatically. 

Good luck!

**Comment by gzuknick** [comment]
Thanks for the note, I realized it was completely user error, in the XLSForm I had it as a note and not a hint, so the column wasn't recognized. As for the sign in there is another thread doing on I may not have publisher right on AGOL so I will see if that fixes it.

Thanks again

Greg
