### ISSUE TITLE
Review workflkow shows empty survey

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#4]
Steps to repro:
1) Collect data for your Survey and either complete or save as a draft
2) Use the Review option to go back to your draft or completed survey
Issue: Your survey will show empty. The values entered in step 1 will be missing.
Expected behavior: Review workflow will honor values previously entered in step 1

**Comment by survey123** [comment]
Status changed to fixed in 1.0.59. Closing.
