### ISSUE TITLE
Browse button is nonfunctional

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#40]
Choosing the 'Browse' button in the 'New Survey' dialog does nothing in Survey123Connect 1.0.59.  

No 'browse' dialog is ever presented to the user.

**Comment by survey123** [comment]
When you click on New Survey, you get the Browse button in the dialog. Did you see that? Are you saying that when you click on Browse the Windows browse dialog is not showing up?

![untitled](https://cloud.githubusercontent.com/assets/10968332/6876695/5aa3cf68-d487-11e4-9e91-d2abe889a2ee.png)

@jmirmelstein

**Comment by marikavertzonis** [comment]
When I choose the 'Browse' button in the 'New Survey' dialog in Survey123Connect 1.0.59 - I do see the file dialog open. I'm using a Surface 2. Do the other options (Blank, Personal Details, Simple) work for you? I notice that when I single click on the Browse button the OK button (that is visible for the other choices), go's away. Does it do that for you?
Does the drag and drop of an Excel file, onto the New Survey, still work for you? (This functionality was there before - and hasn't gone away).

**Comment by jmirmelstein** [comment]
@marikavertzonis Strange. I am actually unable to reproduce this again today. 

Now it seem to be working as I'd expect!  Many thanks for the follow-up.  Drag and drop also still works...although not 100% of the time.  I find that I sometimes must close Survey123Connect and reopen it before it will continue to allow me to drag and drop more surveys onto the 'New Survey' button.

**Comment by Cintruenigo** [comment]
Inconsistent behavior, but I run into the behavior Jeremy describes too.

**Comment by jmirmelstein** [comment]
I'm still seeing this inconsistent behavior in 1.0.65.  When the browse button does not function, I am also unable to drag & drop an existing survey into the 'New Survey' button.

**Comment by Cintruenigo** [comment]
Here is how I was able to repro with Connect 65:
 1) Open Connect and import this [XLS](https://esri.box.com/s/omlhwxnn7l7gwixg3yhgnx1glhv5m24g) (using the Browse button or drag and drop)
 2) Go back to the general gallery in Connect
 3) Click on the imported Survey to open the preview.. and go back to the gallery
 4) Repeat step 3
 5) Try to create a new form using the Browse dialog (will not work). Drag and drop will not work either.

Pretty consistent for me on Windows.

**Comment by survey123** [comment]
Reopening now that we have a repro case.

**Comment by survey123** [comment]
This is not fixed in 1.0.81. Thanks. Closing.
