### ISSUE TITLE
Configuration for Launching Survey123 from AppStudio (invalid client_id)

### ISSUE THREAD

**Issue by sam-berg** [Esri/Survey123Community#401]
Hello, when logging into AGOL from Survey123 after launching in AppStudio standard player, an invalid client_id error is raised. 

![image](https://cloud.githubusercontent.com/assets/6096906/14153307/5416a00a-f685-11e5-91fb-c6228706797f.png)

![image](https://cloud.githubusercontent.com/assets/6096906/14153316/5e5ca0e6-f685-11e5-9d87-35bd27426188.png)

Can anyone advise on how to set this up correctly?  I have registered this custom Survey123 code as an application on AGOL and have noted the clientid.  I tried to insert it into the AuthorizationUrl in the Qt source code but although that gets by the authorization screen, it then hangs the app.

![image](https://cloud.githubusercontent.com/assets/6096906/14153419/ba4a4494-f685-11e5-895c-59e245ce55d9.png)

Thanks for any info on this one.
Sam

**Comment by HannahFerrier** [comment]
You need to set the Client ID for your app in the **Advanced Settings** dialog in AppStudio:

![clientidsettings](https://cloud.githubusercontent.com/assets/8053189/14159909/945a1f30-f724-11e5-95fb-f47ec74c6c52.PNG)

**Comment by sam-berg** [comment]
Hannah, thanks for coming through on that one.  That was it.
Thanks!
Sam

**Comment by RoPB** [comment]
Hi, im having the same issue, and i could not get it solved setting the client id in the advanced settings dialog of Survey123 application.

I followed the steps detailed here: http://doc.arcgis.com/es/appstudio/extend-apps/licenceyourapp.htm 
at the section License your app at the Standard level (Use ArcGIS Online or Portal for ArcGIS to license your app). It says that i have to do what HannahFerrier said but also says that i have to do some other stuff that i am not understanding well.

Could you solve it?

Thank you.

**Comment by tedrick** [comment]
Hi RoPB,

This is more of an AppStudio question, you may want to try posting over in [https://geonet.esri.com/groups/appstudio](https://geonet.esri.com/groups/appstudio) .  Also, take a look at the [Mobile/Native authentication process](https://developers.arcgis.com/authentication/mobile-and-native-user-logins/#add-the-hosted-redirect-page) in the Developer documentation - you need to register an appropriate redirect_URI with the item that you are getting the clientId from

**Comment by RoPB** [comment]
Tedrick,

I will take a look on those links. My apologize for asking this question here.

Thank you very much.
