### ISSUE TITLE
Android Back Button Lost Data

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#404]
One item of feedback I received from field staff (and myself) is that one major pain is if a user is on Android they have a back button.  Us Android users are very accustomed to using this to go back a screen out of habit.  If you are in a survey and hit back it exits Survey123 and you lose all data then have to reenter it (and capture).  It would be a great help if this one brought you back a screen like selecting the back arrow in Survey123 or at the very least gave you a warning that you were going to exit the app so you could select cancel.

**Comment by survey123** [comment]
Thanks for your feedback Ron. Flagging as Planned.
We are aiming for this at the International Children's Book release.
Keep feedback coming!

**Comment by JosephKinyon** [comment]
That is great news. 
Currently this is a required part of training for user because of the abrupt dump of work.

**Comment by sunyu0530** [comment]
We have similar feedback from the techs in field who's using android devices.

+1 for this. 

keep the good work.

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
