### ISSUE TITLE
cannot view results

### ISSUE THREAD

**Issue by zjsxxujin** [Esri/Survey123Community#407]
After I created a survey via Survey123 Conncet, I can publish it online. But after I collected some answers by Iphone 6, I cannot see the results or delete, share the survey on website http://survey123.arcgis.com/#/surveys. 

It says that 'unable to find the related feature service. Please try to upgrade your survey by using the latest Survey 123 Connect.'
![1](https://cloud.githubusercontent.com/assets/18227362/14225234/ad23d504-f8ed-11e5-8f52-a3a296b91bb1.png)

Thanks for the help.

**Comment by survey123** [comment]
Hi! You are using an old version of Survey123 Connect for ArcGIS. While in the Survey Gallery at survey123.arcgis.com ( just like in the screenshot you provide ), scroll down to the very bottom and look at the Quick Link section on the left side. Download and install the latest version of Connect.

We update both the apps and connect around once a month and announce new updates in twitter and our GeoNet Group.

- https://geonet.esri.com/groups/survey123/
- #esriSurvey123

Once you have the latest version, delete your old Survey and publish it again. If you have important data already in your feature service, you can also upgrade your old Survey using the newest version of Connect.

**Comment by survey123** [comment]
Closing issue.
