### ISSUE TITLE
Different times. Need some sort of explanation.

### ISSUE THREAD

**Issue by deanmostad** [Esri/Survey123Community#409]
I have created a Survey with the following date fields (I have other fields of course, but that's not  the issue). And I re-post this because an additional item was closed without being answered correctly in my mind.

I have...
Type=Date
Type=Start
Type=End

for date fields. Respectively I get... From the same records
Type=Date... 3/22/2016 5:00:00 AM (ALWAYS CURRENT DATE AND 5:00 AM.)
Type=Start... 3/22/2016 7:15:05 PM
Type=End...3/22/2016 7:19:38 PM
Notes for this record from the person collecting the data showed 2:16 PM 

Can you see my concern here? Where are the times coming from. Granted the hand entered 2:16 pm may either be central time or mountain time as we work in both zones, but again that is not the main point. Where are these times coming from, the Arc GIS online Server? Somewhere in England?   The variance in my dataset between the DATE and the START and END times is consistently 5 OR 6 hours off. I'm OK with that point but How can I change it. Our standard since we commonly work in both time zones is to collect all of our data in CENTRAL STANDARD TIME, is there any way I can set Survey123 to collect data in that specific time?  Again, I really just want to know WHERE the Start and END times come from?

Suggestion to my fellow Survey123 users is to use a START time for the survey along with Date and then do some sort of conversion as I have yet to see DATE give anything but the date and an hourly time.
 
Any Help would be appreciated. and also this is consistent with several different tablets in the field and all tablets are set to the current local time.

Any Ideas?

Dean

**Comment by survey123** [comment]
Added response here: https://geonet.esri.com/thread/175212 
Closing issue.
