### ISSUE TITLE
Publishing Error

### ISSUE THREAD

**Issue by Marie-Lou** [Esri/Survey123Community#410]
I've made some changes to 2 existing surveys, and I deleted the "Survey-...." folder in ArcGIS Online, under My Content.  I also removed the entire folder  on C:\Users\......\ArcGIS\My Survey Designs\, and started a new survey by importing the updated XLS form.  I've even changed the name on the XLS form to Version1.

When I try to publish this survey, I get a Publishing error, and when I look on AGOL's My Content, the Feature Layer has been created, but not the Code Sample..... 

I'm in a slight panic, as users are waiting for this - and I don't know how to fix this....

**Comment by deanmostad** [comment]
Short answer is to remake a totally different survey, with a different name and have your users download the new survey. You might just call it "MySurvey_V02". From my experience and from the other notes on this site, a Survey really can't be updated. You need to make a completely new one.

Dean

**Comment by survey123** [comment]
@Marie-Lou 
Hi Marie-Lou, would you mind describing the Survey123 Connect for ArcGIS version number as well as the error you are getting?

**Comment by Marie-Lou** [comment]
Survey123 Connect version 1.2.53

It just say "Publishing error".   When I look on My Content, the Survey- folder is there, but this only has a Feature Layer, where a successfully published survey also has a Code Sample.   If I try to re-publish it, and OK the Warning that all data will be lost, it says Code:400 ["Folder Title 'Survey-EMO_EarthquakeAssessments' not available" Unable to create folder.

**Comment by HannahFerrier** [comment]
Hi Marie-Lou,

If publishing fails, you may need to use ArcGIS Online to delete the folder from your content before you attempt to publish the survey again. This is what your Code 400 is reporting.

I'm glad you were able to successfully publish your survey! From you explanation, I would suggest that your publishing error is definitely related to your proxy settings.

- Hannah
