### ISSUE TITLE
Media::image files not included in Survey download

### ISSUE THREAD

**Issue by ksditt** [Esri/Survey123Community#412]
I set up a question to use images and labels for 6 of the 8 answers. I have the images in the media folder and the file path to the image in the media::image column in the choices sheet. 
The desktop app on MY machine (windows) shows the pictures in that question, but my co-workers desktop (windows) does not. We downloaded the survey on his andriod and my iOS phones and no pictures are showing for that question. 
Am I setting up the media folder wrong? Does there need to be an image folder within the media folder?
Is there a special step I am missing to get the pictures to download with the survey? 
Any help or suggestions would be greatly appreciated. Thanks!

**Comment by bowlesgsrcx** [comment]
iOS is case sensitive. Check to be sure the image names are spelled exactly as they are in the media folder. Also, I believe you only need the image name in the media::image field, no path.
--gary

**Comment by ksditt** [comment]
What you're saying makes sense, but we've had issues on both iOS and Andriod phones as well as through the desktop app. The only place I've been able to see the images in the question as I set them up is on the same machine that I created + uploaded the survey, I have NO IDEA what difference that could make, if any. 
I just double-checked all the names of the images in the choices sheet, all good. Left half as the full file path and half only the image name and file extension, still no luck. 
Thanks again, Gary, for the suggestions :smile:

**Comment by survey123** [comment]
Hi. I am guessing you may be copying the media files in the wrong folder. In Connect, open your Survey and click on the yellow folder button to open the survey's directory. Please make sure the images are in the media folder. If they are, zip the contents of that folder and send to survey123@esri.com so we can have a look. Thanks! Also let us know what is the Connect version you are using.
