### ISSUE TITLE
Duplicate Surveys

### ISSUE THREAD

**Issue by chelwest** [Esri/Survey123Community#413]
Every time we push out an update to a survey, it duplicates the survey on the device and there is no way for the user to know which version to use. They end up having to delete both versions and download the survey fresh. Before the update in March, the surveys would overwrite each other. Is this going to be fixed in a subsequent release?

**Comment by survey123** [comment]
Hi!   This is a known issue but we appreciate your note.  As a workaround, for now, you will need to delete the old Form before downloading the new to avoid confusion.

**Comment by sunyu0530** [comment]
+1

wonder if the we can have notification on the App to tell end user that form need to be update.

**Comment by GISGURU001** [comment]
I have a serious issue with my sent responses from the field they get duplicated easily, please is there any bog or fix for this anomaly? Thanks

**Comment by IsmaelInRedlands** [comment]
@GISGURU001 What version of the Survey123 app are you running? Issues with duplicate submits were identified in previous versions of the mobile app, but were addressed.  Latest version is 2.0. Please contact Esri Tech Support at: http://support.esri.com/ if the problems with duplicate submits persist in version 2.0. We will want to know the details. 

Please also note that we have moved our Community Forum from this repo to GeoNet at: https://geonet.esri.com/groups/survey123

**Comment by GISGURU001** [comment]
Thanks we have the latest version now, and it is ok
