### ISSUE TITLE
Survey123 location icons disappear

### ISSUE THREAD

**Issue by icenole** [Esri/Survey123Community#418]
Everything was going along nicely until this morning when I tried editing survey123 results over in ArcGIS Online.  I updated attributes for a dozen or so survey sites in our enterprise ArcGIS Online account (appears to be a very useful function).  After completing the updates, signing off, and signing back in to our ArcGIS Online enterprise account, none of the location icons were viewable.  We have verified the data is still there by by exporting in a shapefile and viewing in ArcMap.  Also can see the same over in Survey123.arcgis.com.  What in the world has happened to cause this; seems reasonable to expect this issue is tied to the survey attribute update.

**Comment by survey123** [comment]
Hi. Any chance you can reproduce this behavior so we can look at it? We need to reproduce before we can understand the root of the problem.

**Comment by icenole** [comment]
Certainly cannot reproduce the final issue as all the icons are gone.  Also cannot provide screen prints here.  Here is what I did:

1) Sign in to our enterprise arcgis online account using my credentials
https://akdot.maps.arcgis.com/home/signin.html

2) Select My Content

3) Select Survey-Form 9 from My Folders

4) Select Form 9 Feature Layer

5) Click on Form 9

6) Select Add Layer to Map (clip board icon with survey name

7) This produces the map where the icons used to appear.  I do note that the date range scale at the bottom of the map is a very narrow range (12 hours) that was very earlier in the survey period.  I adjusted the date range to cover the period of all surveys but didn't change anything.

8) I can click on the table option under Contents and view the survey results.  I can log on to survey123.arcgis.com and see the survey results and mapping component.  However, the arcgis online offers more capabilities, e.g, viewing the images.

So either the editing of the attributes has introduced the problem or I did something I was not supposed to.  The date range limitation noted in #7 is interesting.  Even though I changed the date range to cover the entire period of the survey, perhaps there is an additional step to engage the new selection.

Any ideas?

**Comment by deanmostad** [comment]
I have had a similar issue. It seems like the time slider works off of the modified date!??? I'd try removing the time sliders by disabling it. I think your points will show up if you do this.

**Comment by icenole** [comment]
Bingo - solved the problem!  Thank you so much - I have no idea on why this changed during attribute update process.

**Comment by rrichman** [comment]
Hi Icenole,

I am with Esri Technical Support. The Survey123 for ArcGIS team wants to confirm the workflow that was causing the issue, and I have not been able to reproduce it with my own data. I was wondering if you would be willing to share the survey form you were working with or give us some more information about it so we can further investigate the issue.
