### ISSUE TITLE
How to delete/revise a record when geoLocation was not set.

### ISSUE THREAD

**Issue by sunyu0530** [Esri/Survey123Community#419]
I have a situation where when I created a survey through Survey123 App, the location service on the phone was disabled. 
As a result the data was successfully uploaded but there is no geolocation of the point.
When I try to search for the record through ArcGIS Online Map, I can only view the data from the attribute table.
I cannot zoom in to the record b/c it doesn't have a valid geolocation. and thus I didn't find a way to  revise or delete that record.

I was able to reproduced a same scenario while using the Survey 123 App on the PC (windows 7). 
Any help and hint is appreciated.

Thanks

**Comment by RKnepper3** [comment]
Do you have ArcGIS Pro by chance?  If so you can edit live data, connect to your feature service and delete that one from the table.  I'm not sure of a way around on AGO.

**Comment by sunyu0530** [comment]
@RKnepper3  
That worked. Thank you very much.

**Comment by RKnepper3** [comment]
Yeah that is one thing I love about pro, editing AGO data is such a pain online but Pro makes it so easy.  If no pro you could probably edit on Arcmap then republish but not sure how Survey123 would like that.
