### ISSUE TITLE
Support for signatures in forms

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#42]
I have worked with a number of customers who would like to be able to "sign" their surveys.  This is an example that would work for them in Survey123:
https://github.com/kobotoolbox/kobocat/wiki/How-to-include-signatures-in-forms

**Comment by umikal** [comment]
The signature functionality is also especially useful when interviewing assisted beneficiaries in the field to verify that they were indeed interviewed and provided that information.

**Comment by martinGIS** [comment]
this functionality would be great

**Comment by CPolley7** [comment]
When selecting required field as yes the form does not recognize the image or signature is true; keeps saying signature is required.

**Comment by survey123** [comment]
@CPolley7 Thanks for your feedback.This has been raised as a bug with the development team.

**Comment by survey123** [comment]
This feature can now be found in the latest version of Survey123.
