### ISSUE TITLE
can attachments relate to Global ID rather than object ID

### ISSUE THREAD

**Issue by sunyu0530** [Esri/Survey123Community#420]
Morning,

attachments in survey123 currently is using object ID for the relationship.

I want to @ #302 that if we can add a global ID field in future, can we use that field for the relationship?

object ID to attachment relationship can easily break if we try to transfer/manipulate data in the back end.

just a thought for enhancement.

Thanks

**Comment by bowlesgsrcx** [comment]
+1 for attachments using Global ID in relationship instead of Object ID.

**Comment by deepti10** [comment]
+1 for Global ID for attachments

**Comment by survey123** [comment]
Thanks for your feedback. @bowlesgsrcx  @deepti10 @sunyu0530 
This has now been implemented in Survey123 Connect for ArcGIS 1.4.30. You can download the latest version from: http://doc.arcgis.com/en/survey123/download/
