### ISSUE TITLE
Survey123 - missing data fields

### ISSUE THREAD

**Issue by karlkeough** [Esri/Survey123Community#421]
I am just starting out with Survey123. I have created a survey with contingent fields (ie, using the 'relevant' field in the form design spreadsheet). The survey downloads as expected and works fine within the mobile app. However, when I look at my data in Survey123 or ArcGIS Online, many of the fields are missing. It seems that only the non-contingent fields are showing up, even though I entered data in the other fields. Does anyone know why this might be happening?

**Comment by survey123** [comment]
Hi @karlkeough 
If I understand correctly, questions in your Survey that are not relevant are showing empty values in your Feature Service. This is expected. Non-relevant questions always persists a value of NULL in Survey123 for ArcGIS.
Closing issue.
If you would like to ask general questions, I would recommend you use our Survey123 GeoNet Group: https://geonet.esri.com/groups/survey123   This forum in GeoNet is monitored for questions by the Survey123 team as well as the user community.  Thanks a lot!
