### ISSUE TITLE
External Select

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#422]
Hi,

I have created a survey with external Select as per the instructions in the xls help it should translate into an xml file and itemsets.csv file http://survey123.esri.com/resources/XLSFormSupport/#external. I do not see it in my design folder. I would like to change the external select separately so that i can change them. 
Also the live sample http://survey123.maps.arcgis.com/sharing/rest/content/items/68b8e40bdc594d0b800c8fe6e46863b5/data is broken so I don't know if I am doing something wrong.

**Comment by survey123** [comment]
A tech support analyst will contact you. Closing issue.
