### ISSUE TITLE
Survey123 and Operations Dashboard

### ISSUE THREAD

**Issue by kc-lee** [Esri/Survey123Community#423]
In my xls form, I have created a question under select_one type. Then I assigned it to esriFieldTypeInteger. 

type	name	label
select_one choice	Installation	Installation 
select_one choice	Editing	Editing 
select_one choice	Spatial Analysis	Spatial analysis

Within the choices spreadsheet, I used integers for the name I.e. :
list_name	name	label
choice	0	Don't Know
choice	1	Learning

When I published and sent 1 survey, the attribute table in the webmap shows "Don't Know", "Learning" and empty values in some columns. However when I query the REST services, it returns results (in 0 and 1).

The reason for this is to showcase this webmap in Operations Dashboard with the widgets. 

Would it be issues in my workflow which caused this error?

**Comment by kc-lee** [comment]
Do choices support integer?

**Comment by survey123** [comment]
What you describe above is expected: When you add a Select_One type of question in Survey123, we create a corresponding coded value domain in the feature service. In this domain, we use the values in the NAME for the Codes and the values in the LABEL for the descriptions.

Operations Dashboard and Web Maps will always translate Codes into Descriptions. Queries through the REST API will always return the Code, not the description. Closing issue.
