### ISSUE TITLE
Entering time of day

### ISSUE THREAD

**Issue by karmstro77** [Esri/Survey123Community#424]
Is there a way to change the option for entering time of day from hh:mm:ss to a clock or scroll list? I am trying to have users enter open and close times for farmers markets but cant think of a good way to do this. I could use a select_one with a pull down but that would require separating hours, minutes, and AM/PM into 3 different fields. Ideally, I would have all 3 fields side-by-side. Right now, they are one on top of the other.

![image](https://cloud.githubusercontent.com/assets/6819070/14465384/d071202e-00a0-11e6-8586-282a0d66fe6d.png)

**Comment by colgateg** [comment]
The current version of Survey123 (1.3.38) defaults to a scroll list for fields set as DATETIME or TIME types...

![image](https://cloud.githubusercontent.com/assets/17730847/14468695/b4bf25e8-0095-11e6-8342-a0a2574ddc9e.png)

I believe they are planning on supporting more advanced methods for organizing the forms (multiple pages, page columns, etc) at some point, but I wouldn't expect to set three fields side-by-side soon.

**Comment by karmstro77** [comment]
OK, I was running an older release. Looks like there may be a bug on Android in the new release for displaying time. It only displays a single digit for minutes 0-9. 

![image](https://cloud.githubusercontent.com/assets/6819070/14496497/4d5bb886-0161-11e6-8b27-5167b438e10b.png)

**Comment by colgateg** [comment]
FYI.. iOS also shows minutes 0-9 as single digit... The data field does show the correct value when selected. Not sure if it really counts as a bug or just a development choice by the control creator.

![image](https://cloud.githubusercontent.com/assets/17730847/14539236/7235cb8c-0234-11e6-9646-f146f40c32b2.png)

**Comment by survey123** [comment]
Thanks @karmstro77   
Working on this. Stay tuned.

**Comment by survey123** [comment]
Fix now available in version 1.4.28. Please download latest app from the store to validate fix. Reopen issue if needed. Thanks for your feedback. @karmstro77 @colgateg
