### ISSUE TITLE
Nested relevant option

### ISSUE THREAD

**Issue by karmstro77** [Esri/Survey123Community#425]
Is there a way to nest relevant statements within a relevant statement? Here is my use case. I want users to answer a Yes/No question whether they use social media. If they answer yes, it would expose a new set of yes/no questions about which sites they use. If they choose yes to a site (facebook), a new field would open asking for the url to the facebook site. I know i can use relevant to ask an additional question but didnt see anything in the doc about using it to ask multiple questions that each have a relevant statement.

So if a user answers yes to being on social media, this list would appear. Each answer would also contain a relevant statement to allow them to enter url info.
![image](https://cloud.githubusercontent.com/assets/6819070/14465849/780ca8b6-00a2-11e6-9087-d2c62bc19bdd.png)

**Comment by colgateg** [comment]
I may not be understanding the question... You seem to have answered it for yourself. To nest relevant fields, you first test the group, then test each individual item. So the first relevant would expose the GROUP row, and each url TEXT row in the group would be exposed by a relevant for its associated social media question, like this...

![image](https://cloud.githubusercontent.com/assets/17730847/14468180/6942fb0a-0093-11e6-87f5-245eaa4492c4.png)

Did I miss something?

**Comment by karmstro77** [comment]
Ahh, I need to use relevant on a group, not just each question. That is what I was missing. Many thanks!
