### ISSUE TITLE
Survey123 Reporting

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#426]
The Survey123 website provides some nice summary chart data for Select One, Select Multiple, Integer and Decimal type questions. However you cannot store this in any format other than HTML. If this could be exported to a .pdf or .docx file it would be very useful.

The Survey123 website also display any responses in table view. This is useful but doesn't include related table data or images. A facility where you could get a printable report for each individual report which includes any associated data - i.e. related tables/associated images/etc. of each individual survey would be quite useful.

**Comment by zhif7782** [comment]
Hi @MKellyEsri , thanks a lot for the feedback. 
The good news are:
1. Showing images (attachments) and related records in the table feature is almost finished, if there's no suprise, you'll see the new features the May release
2. Persist the view of "Summary" page is also on our radar, we're trying to figure out some way to implement this

Please stay tuned with Survey123 :)

**Comment by MKellyEsri** [comment]
@zhif7782 Brilliant thanks a lot for the update!

**Comment by phil-wilson** [comment]
Any update on this? Will we be able to print individual reports for individual surveys (records) with related tables and photos included, from either AGOL or survery123 website?

**Comment by RKnepper3** [comment]
Anything, I just saw this planned update and it looks very interesting.

**Comment by survey123** [comment]
Sorry for the delay in updating this issue. Printing of individual records (with pictures and related records was added in August 2016). Try it out in survey123.arcgis.com.

**Comment by geospatialology** [comment]
This is useful, but users really need the ability to print their records in batch; not one record at a time. There should be a button that allows users to "Get Reports as PDF" and either get them as individual files (one PDF per record) or a combined PDF. This functionality meets a lot of user requirements for sharing/disseminating data collected with the survey. Also, allowing users to select a subset of their data and get these PDFs as individual or combined would be helpful - instead of one at a time or all at once.

**Comment by survey123** [comment]
@geospatialology thanks a lot for your feedback and batch printing is a feature request in our backlog currently.

Please note you're encouraged to post further issues to [the Survey123 GeoNet group](https://geonet.esri.com/groups/survey123/content), it's the main place to discuss any issue with Survey123 and also let other users know if they have the same request, and [this repo is going to be closed soon](https://github.com/Esri/Survey123Community/issues/620).
