### ISSUE TITLE
Support for barcode readers

### ISSUE THREAD

**Issue by sirws** [Esri/Survey123Community#43]
Barcode support would work well in conjunction with issue 41 (looking up previous inspections) and for allowing people to tag samples and scan them to avoid fat-fingering input.

https://opendatakit.org/help/form-design/examples/#barcode_prompts

**Comment by spatialdude** [comment]
@sirws Do you have particular devices in mind that support bar code readers?

**Comment by sirws** [comment]
@spatialdude My thinking would be leveraging the built in camera on the devices.  For example, on iOS, maybe we could use wrap a library like this:

http://zbar.sourceforge.net/iphone/sdkdoc/camera.html
or
http://zbar.sourceforge.net/.

Android:
https://github.com/ZBar/ZBar/tree/master/android

**Comment by spatialdude** [comment]
@sirws Good suggestion. We'll look into it. Do you think QR codes are also of practical value?

**Comment by sirws** [comment]
Definitely!  That's why I like that library.  Supports a lot including qr.  it could be that people just use it when collecting samples (soil, etc) and they place a ore printed barcode or QR on a sample then use the camera to scan it to avoid typos etc.  One customer interacts with customers and gives them a "passport" which has a QR on it and when they interact with them again in the future, they want to be able to scan the passport to start the next interview.

**Comment by sirws** [comment]
Pre-printed

**Comment by Cintruenigo** [comment]
Another barcode library: http://sourceforge.net/p/qzxing/wiki/Home/   This one is for Qt

**Comment by esri4591** [comment]
Strongly agreed with @sirws . @survey123 This is a very wonderful app that I wait for a long time. Thank you very much for making the great app for us.
 
I will try to use it in Asia Pacific User Conference 2015 (Hosted by Esri Thailand in November 2015) such as:
-          Demo Request Survey
-          Session Evaluation Survey
 
It would be great if in the future Survey123 app can scan QR/Bar codes then manual entry to multiple field in the survey form. (I will use this feature to scan QR/bar codes in APUC attendance badge it reduce an entry data process.

**Comment by martinGIS** [comment]
having the ability to support bar code scan in iOS would be awesome, is there a timeline for that?

**Comment by jakc** [comment]
Support for QR would be useful for asset management use-cases.  Each asset (which might not be fixed to a location) has a QR Code on it, 
Survey allows you to scan code to perhaps populate other fields or edit a related record?

**Comment by survey123** [comment]
Initial implementation included in the last update. 
Details here:
* https://geonet.esri.com/groups/survey123/blog/2016/03/04/international-women-s-day-release
Please submit any problems you find as new issues. When using barcodes, tell us what type of barcode you are using (EAN13 for example) and the device you are using.
