### ISSUE TITLE
Automatically Place Input Cursor at Beginning of Input Mask

### ISSUE THREAD

**Issue by kmsternhagen** [Esri/Survey123Community#430]
If no input mask is used, and you tap/click anywhere in an input box, the cursor automatically jumps you to the very beginning of the box to input data. Whenever an input mask is introduced, wherever you tap/click in an input box is where you cursor starts, so you have to backspace to the beginning if you want to start a phone number, or have the first letter of a first name be capitalized which is not very intuitive for most staff. We have a lot of data entry errors stemming from ill-formatted data and the introduction of the input masks was a great start, but the cursor problem is still proving to be a limitation.

**Comment by chelwest** [comment]
I agree! This is a huge issue for the surveys we are putting together. The user doesn't' necessarily know which field has a mask and might not notice in the field if the cursor started in the wrong place. It would be great if it automatically started the data entry at the beginning regardless if a mask was used or not.

**Comment by survey123** [comment]
@kmsternhagen   @chelwest 
Thanks for your input. We are working on fixing this. Adding to the Star Wars milestone (mid-May).

**Comment by HeatherMcW** [comment]
+1

**Comment by survey123** [comment]
Fixed in the 1.4.28 version of the mobile app. Closing issue. Thanks to @HeatherMcW @chelwest  and @kmsternhagen for your feedback.
