### ISSUE TITLE
Deleting Images/Photos in Survey123

### ISSUE THREAD

**Issue by potterg** [Esri/Survey123Community#433]
Is there any way to delete a photo after it has been added to the Survey.  I know I can replace it but was hoping I could also just delete the image.

**Comment by sunyu0530** [comment]
the only way I know is submit the survey and then removed it from ArcGIS Online or ArcGIS Pro Environment.

**Comment by survey123** [comment]
What a coincidence! We are just working on this feature!
As you can see in the screenshot below, we are working on a 'delete' button, so you can clear out your photos before you submit them.  We are experimenting as well with the idea of allowing you to change the name of the photo, so it is easier to identify once submitted.

![img_0290](https://cloud.githubusercontent.com/assets/10968332/14652229/46ca92f0-0628-11e6-9360-3eec95dda6be.PNG)

Once submitted, photos will be stored as geodatabase attachments, which can be deleted from the ArcGIS Map Viewer and ArcGIS Pro as described by @sunyu0530 

Flagging as Working on it and tentatively assigning to our Start Wars release.

**Comment by survey123** [comment]
@potterg 
Enhancement now available in the 1.4.28 version of the Survey123 field app, which is available in the app stores. Thanks for your feedback!
