### ISSUE TITLE
Answers in Draft form not getting saved.

### ISSUE THREAD

**Issue by ksditt** [Esri/Survey123Community#439]
I have a survey where the user picks from a list of PA counties, but if the user exits the survey and saves as a draft, the county selection is removed (and not saved in the draft).
This does NOT happen when you choose a county from the top of the list, the initial counties shown in the selection list. If you pick a county not shown in the first 5 records, the selection doesn't get saved.

**Comment by HannahFerrier** [comment]
Please make sure you are using the latest version of Survey123. This issue was supposed to be fixed in the last release.

If you are still able to reproduce this issue using the latest version of Survey123, please let me know.

- Hannah

**Comment by ksditt** [comment]
This is working now that I've upgraded! Thanks for the response!
-Kristin

**Comment by survey123** [comment]
Closing issue.
