### ISSUE TITLE
Date fields are not formatted correctly in Survey123 web site results page

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#44]
Date fields from Editor Tracking show OK, but date fields collected as part of the Survey are not formatted correctly. See below:

![untitled](https://cloud.githubusercontent.com/assets/1273440/6880053/90a00792-d4d9-11e4-9309-c66084268ccc.png)

**Comment by Cintruenigo** [comment]
Much better now! Thanks!
![untitled](https://cloud.githubusercontent.com/assets/1273440/7016008/04b1e244-dc92-11e4-9616-05c243b44478.png)

**Comment by survey123** [comment]
Closing
