### ISSUE TITLE
Save to Draft Should Ignore Required Fields

### ISSUE THREAD

**Issue by colgateg** [Esri/Survey123Community#440]
Required fields are currently stopping a user from saving their incomplete work to draft. This is forcing the user to enter information that may not be correct as a placeholder until such time as they can come back and complete the survey.

We think that required field check should not be tested when saving locally using "Send Later". Or at least allow to save with known required field error. This will allow greater flexibility to record information as it is available and still enforce data constraints before the record is finally sent to the database.

**Comment by travisbutcher** [comment]
👍 
There should be no validation when saving the draft, this would allow users to come back later and fill in the required pieces

**Comment by spatialdude** [comment]
The current implementation does save the Survey to draft without validating required field.

@colgateg Can you explain further what your scenario is where it is not allowing you to save to draft with required fields?

**Comment by travisbutcher** [comment]
This is a common scenario where the survey may time to complete, days maybe.  During that time it is best to save as a draft then come back to it later.  In some of these scenarios you may not have hit or needed to fill out all these fields, the required fields should really only be of concern when submitting the final.

**Comment by colgateg** [comment]
I stand corrected. Turns out this is nothing more than a training issue.

I was thinking that clicking the checkmark would give me the option to save to draft. I should have clicked the X which does indeed give me an option to close/lose changes, continue editing, or **Save in Drafts**. Required fields do not stop a form from being saved in drafts using this method.

Works for me... Thanks.
