### ISSUE TITLE
Issue Importing a GeoEvent Definition, or Polling an ArcGIS server, from a Registered ArcGIS Server created via Survey123

### ISSUE THREAD

**Issue by sjblitz** [Esri/Survey123Community#441]
In ArcGIS GeoEvent Manager, after I have successfully registered my ArcGIS Server via AGOL, I am having an issue IMPORTING the GeoEvent Definition from my registered ArcGIS Server created **via Survey123**. In the Import window I am able to see the Registered ArcGIS Server, the Folder, and the Service, however, the Layer drop-down field doesn’t contain a layer for me to select. I have been successfully in getting this to work with GeoEvent Manager 10.2 but not currently with 10.3.   

![pastedimage_2](https://cloud.githubusercontent.com/assets/16241979/14825916/6043f748-0ba1-11e6-807f-de19e82b052e.png)

 
The same issue occurs when I go to setup an Input, I am able to connect to my ArcGIS Server but the Layer drop-down field isn’t displaying a layer for me to select.  
 
![pastedimage_3](https://cloud.githubusercontent.com/assets/16241979/14825894/5299bfba-0ba1-11e6-93f1-f8dd2a6947f7.png)

Thanks,  Steven

**Comment by survey123** [comment]
Hi @sjblitz  I suggest you post your question here: https://geonet.esri.com/community/gis/enterprise-gis/geoevent   Closing issue.

**Comment by sjblitz** [comment]
Doesn't work with GeoEvent 10.3 but does work in 10.4.
