### ISSUE TITLE
"There are no surveys shared" even though it is shared.

### ISSUE THREAD

**Issue by GeoJtaylor** [Esri/Survey123Community#444]
I published a survey.  I can see it on ArcGIS online and in Survey123 for ArcGIS ,  I can even see it on my iPad.  I am able to successfully send a survey using my iPad.  However when I go to download the survey to another device it says there "There are no surveys shared" with my user name.  This doesn't really make sense because 1) I am the owner of my survey. 2) I am using the same username and password as my iPad, 3) I am still able to send my data through my iPad and see the new test points on AGOL (even after signing in and out.)  The reason is this is a big problem is because I am setting up the account for someone else and only downloaded to my device to check it.  Since sharing surveys is not reliable right now I am not really sure what next steps are.  Anybody have any thoughts?

**Comment by spatialdude** [comment]
If you are sharing via the item page in ArcGIS.com, make sure your survey is not shared to **Everyone (public)**

![image](https://cloud.githubusercontent.com/assets/7235583/14871521/4af5a4c8-0d26-11e6-82cd-2ce008ef8edd.png)

**Comment by GeoJtaylor** [comment]
Yep that totally worked.
