### ISSUE TITLE
Sharing surveys

### ISSUE THREAD

**Issue by kc-lee** [Esri/Survey123Community#445]
I have shared the feature layer with my organisation in ArcGIS online. In survey123, I have also shared it with my organisation.

However, there are some users whom are able to view the survey and some can't. Issue occurs in both android and iOS.

Ideas?

**Comment by survey123** [comment]
Please ensure that users are using the latest version of the app.
A potential explanation to this is as follows:
* Prior to 1.3.x, Survey123 Connect published Surveys using a Code Sample type in ArcGIS. Starting at 1.3, Connect publishes Surveys to ArcGIS using a new Form item called Form.  Survey123 field apps prior to 1.3 will not be able to see Form items.  There is a possibility that some of your colleagues have an old version of the app.
