### ISSUE TITLE
Testing Previous Answers for Field Calculation

### ISSUE THREAD

**Issue by colgateg** [Esri/Survey123Community#446]
We would like to populate a field based on a IF-THEN test of a previous response (or responses) in the survey. We think that the logic belongs in the calculation column... so our best guess was...

if(${METER_STATUS}='FAIL' or ${METER_BOX_STATUS}='FAIL', 'FAIL', 'PASS')

![image](https://cloud.githubusercontent.com/assets/17730847/14893812/ac914972-0d25-11e6-91d9-55cf414080be.png)

Anyone have a similar test that they have had success with?

**Comment by HannahFerrier** [comment]
I have put together a quick sample here: [ifstatement.xlsx](https://github.com/Esri/Survey123Community/files/241569/ifstatement.xlsx)

Hopefully this can help :)

**Comment by colgateg** [comment]
Interesting... If I change my field type to "note" as you have in your example, the calculation formula works fine... if its set to a select_one, it does not work (and as a side note the defaults stop working in the previous questions).

Bug?

**Comment by survey123** [comment]
More an enhancement request. At the moment we do not support Calculations on Select_One.
Please vote here: https://github.com/Esri/Survey123Community/issues/157
