### ISSUE TITLE
Offline map preview not available

### ISSUE THREAD

**Issue by SJevons** [Esri/Survey123Community#447]
Many of our Survey123 app (1.3.38) users use cached map data to view maps in offline mode. This works perfectly for iPhone 5 and 6 but not Samsung with Android 5.1.1. These devices have location settings enabled and the Clear Map Cache is greater than 25Mb. The error message is 'Offline map preview is not available'. Has anyone had this issue or know of a fix?

**Comment by talllguy** [comment]
@SJevons are you using TPK offline tiles or relying on those that are downloaded and cached whenever the device is online?

**Comment by SJevons** [comment]
Hello,

I'm not using TPK files, just relying on those downloaded and cached when the device is online.
