### ISSUE TITLE
Naming Conventions for FGDB tables/relationship classes/etc.

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#449]
Is there any chance that we can get the naming of the related tables, relationship classes, etc cleaned up so that when we look at the fgdb, we can easily see which related tables are actually related? We have a survey that has 3 repeat sections. I have attached a screencap of the fgdb from the survey. When looking at this in catalog, it is almost impossible to determine what is related to what. The survey is called AboveGround_PipelineInspection and the three repeat sections in the survey are dpi_repeat1, dpi_repeat2 & dpi_repeat3.
 
Typically when a relationship class for attachments is created in a FGDB, the related table name and relationship class name all use the feature class name with the suffix of _ATTACH or _ATTACHREL. It is easy to know which table is related to which feature class.
 
Thanks,
--gary

![fgdb_repeats](https://cloud.githubusercontent.com/assets/14822701/14965616/5da35b52-107c-11e6-9c9a-fcb0bf4f7919.JPG)

**Comment by survey123** [comment]
Hi. When you create your own Featureclasses and related tables and attachments in ArcGIS for Desktop, you have more control over the name of tables in the database, but when publishing Hosted Feature Services ArcGIS takes control over the naming.  We are going to be limited on what we can do from Survey123 to let you control the name of these tables, at least when publishing the Feature Service from Connect.
In the 1.4.30 version of Connect, which we just published, you can associate your Survey with a Feature Service that you may have created with ArcGIS for Desktop. Have a look at this [help topic](http://doc.arcgis.com/en/survey123/create-surveys/xlsformsubmissionurl.htm) for details
