### ISSUE TITLE
Make the Survey123 Connect installer easier to find

### ISSUE THREAD

**Issue by swingley** [Esri/Survey123Community#45]
To get Survey123Connect, I have to:

1. go to http://survey123.esri.com/
2. sign in
3. click "Go To My Surveys" (even though I don't have any yet)
4. click "Create New"
5. click "Survey123Connect"
6. click "here" to download the installer

Is there a simpler way to get Survey123Connect? If not, there should be. Please make it easier to get to the Survey123Connect installer.

**Comment by mhogeweg** [comment]
:+1: I already have surveys and still need to create a new one to get the app? not intuitive.

**Comment by sathyaprasad** [comment]
Website footer contains all the links now
