### ISSUE TITLE
Combo_Box

### ISSUE THREAD

**Issue by pacoGIS** [Esri/Survey123Community#452]
Hi everybody, I go to the point,... I have to do an Survey but, I need a combo-box with a list o values,...
¿is this posible to do in survey123?,..thank's for advance

**Comment by HannahFerrier** [comment]
Yes, combo-boxes are easy in Survey123! 
Please see here: http://doc.arcgis.com/en/survey123/create-surveys/xlsformessentials.htm for an overview of the question types...
...and here: http://doc.arcgis.com/en/survey123/create-surveys/createfirstsurvey.htm for a tutorial that includes creating combo-boxes :)

**Comment by pacoGIS** [comment]
thank´s a lot

**Comment by pacoGIS** [comment]
Hummm¡¡,..sorry but, in those link's not responde my question,... may be the attachment image can helpa little bit.

![image](https://cloud.githubusercontent.com/assets/19214759/15060495/a8ed55b0-12f0-11e6-8eb0-b6da8582496c.png)

thank's again

**Comment by pacoGIS** [comment]
Hi Hannah, I send you a great hug from Aguascalientes México, ¿do you see
the new question about Combo-box in the github,.... see you and I hope you
can help me....

2016-05-05 17:42 GMT-05:00 Hannah Ferrier <notifications@github.com>:

**Comment by travisbutcher** [comment]
Can you post the XLS you are using to create this form?

**Comment by pacoGIS** [comment]
I dont finish it, but my problem is ¿what I do to when I have to select one value from 90 in my list of Values?,....

**Comment by survey123** [comment]
Hi @pacoGIS   Once you have your Select_one question in place, change the appearance to minimal, and the look of your list will transform into a combo box just like the one you show in the screenshot above.

**Comment by pacoGIS** [comment]
ok, thank's, I try it,...

**Comment by pacoGIS** [comment]
Great¡¡¡ it's worked,.... thanks again,.... ja ja,...now I have another question,... supose I have a  composite value of two words, how a do to put these in the column "name" in the choices tab whit the space between both words?

**Comment by pacoGIS** [comment]
thank you very much..... :+1:
