### ISSUE TITLE
Survey123_WorkForce Integratiokn

### ISSUE THREAD

**Issue by Mas3oude** [Esri/Survey123Community#453]
how ti integrate between workforce and survey123 to force the user to finish the task using the survey123 and send data from workforce to survey123

**Comment by survey123** [comment]
Hi. You can launch the Survey123 mobile app from Workforce as shown in the screenshot below. We are working to expand Workforce and Survey123 so you the Workforce Project Owner can also define the specific Survey that will be automatically open.

![img_0577](https://cloud.githubusercontent.com/assets/10968332/15098235/3d460af6-1538-11e6-9585-d5c5eadca10c.PNG)
