### ISSUE TITLE
Copy saved drafts or favorite answers from one survey to another in the Survey123 app?

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#454]
When a new version of a survey is published to ArcGIS Online, it wipes the feature service and creates a new service, as well as a new survey to be downloaded on the mobile device. If the user has not submitted their current surveys or has drafts or favorite answers saved, is it possible to copy these over to the new survey?

The reason being is that if they try to submit the current surveys, they will get a code 400 error saying invalid url, as the old feature service no longer exists. So if it is possible to copy the saved drafts and favorite answers to the newly downloaded survey, that would save a lot of time to have to enter all the answers and uploaded all the photos again.

Hope there is a solution to this, as we have a lot of surveys on different devices that can not be uploaded now.

Thanks,
Phil.

**Comment by survey123** [comment]
Hi @phil-wilson , version 1.4.30 of Survey123 Connect for ArcGIS has been released with fixes to address your concern. With this new version, Connect will only replace your feature service when absolutely necessary. That is, when you add or remove questions that will require a change in the schema of your feature service.  But even, if you were forced to replace the feature service, your Surveys in the mobile app will be able to find the new service.  Make sure you download the new version of Connect from: http://doc.arcgis.com/en/survey123/download/   You will also need the latest version of the mobile app (1.4.28), which is available from the app stores.   You will also notice that from the app, you no longer need to delete a survey before you download a new version. Thanks for your feedback!

Closing issue.
