### ISSUE TITLE
Any potential updates?

### ISSUE THREAD

**Issue by Jwynn3** [Esri/Survey123Community#455]
Are there any planned updates to be pushed out for Survey123 on or before the 17th May this year?

**Comment by survey123** [comment]
We are about to submit the Star Wars update to the Apple store.  We think this update will be available around May 15th, but it is difficult to predict exactly the date. It may move or two days before or after the 15th.  Along with the update to the app, we will refresh Connect and the web site.

**Comment by Jwynn3** [comment]
Will the update affect any pre-existing surveys? We are demoing it at the Esri UK User Conference on the 17th May and so are concerned it may disrupt anything we have already created.
(Very excited to see the update though!!)

**Comment by survey123** [comment]
Hi. Nothing dramatic will change. All surveys you may have will continue to work and no data will be lost.    The only exception is that data you may have not submitted in your device will be erased when you update the app. It is always bests to submit all data from your device, and then proceed with the update of the field app. Closing issue.
