### ISSUE TITLE
Need Field Precision & Scale (Followup to Issue #306)

### ISSUE THREAD

**Issue by colgateg** [Esri/Survey123Community#457]
![image](https://cloud.githubusercontent.com/assets/17730847/15221984/915c106c-1822-11e6-90fc-4aac6a3e30d9.png)

Masks are not going to cut it when dealing with decimal values. A mask is great when you are trying to force adherence to syntax like a serial number or phone number. Data where the user must enter all of the digits to make a valid entry. But decimals are a bit different, we need to restrict the user to a specific place value but allow for multiple acceptable variants...

For example: Using a mask of 999.9 to try and get a double(4,1)...123.4 (Pass), 12.3 (Fail), 1.2 (Fail)

**Comment by colgateg** [comment]
Plus masks are still just ugly to deal with. Users complain of mask blocking their entry of data (unless user specifically moves cursor to start of field), delete is impossible unless using the delete button at end of field (backspace & delete keys are ignored).

**Comment by survey123** [comment]
@colgateg  Thanks for your feedback.
Input masks may not be the best to control decimal values.  You may want to try a decimal type of question instead. If you do not want decimal values over a particular figure, you may want to use a constraint on your decimal type of question.

We are working to fix the issue with the cursor not appearing by default at the start of the input. This will be addressed shortly. Stay tuned for upcoming updates.

**Comment by survey123** [comment]
Version 1.4.28 has been released and fixes the issue where the input cursor was not being positioned at the beginning Closing issue..
