### ISSUE TITLE
Enterprise Logins 

### ISSUE THREAD

**Issue by colgateg** [Esri/Survey123Community#458]
Relocating question from geonet... https://geonet.esri.com/thread/175008

We are still trying to connect Survey123 using enterprise account. After entering the organization URL, and selecting the "using your <org name> account" button, the app will not popup a login to enter username and password. **I have verified that the organization account does work in Collector and Workforce (so its unlikely that its a device setting)**. I thought enterprise logins were enabled back in January, any guesses what might be the problem?

**Comment by survey123** [comment]
Hi. I will ask our Tech Support team to contact you. Thanks.

**Comment by survey123** [comment]
@colgateg 
Version 1.4.28 has been released. Please try again with this new version. Closing this issue. If the problem still persists, please re-open this issue.

**Comment by colgateg** [comment]
Our problem persists... I tried to trap some of the traffic to help illustrate what Survey123 is doing as compared to Collector or Workforce. The other two gave some decent certificate error messages and then let the user decide to connect anyway... but Survey123 wouldn't even connect with Fiddler in the way.

Collector:
![image](https://cloud.githubusercontent.com/assets/17730847/15516054/daaf98ec-21a5-11e6-9fa3-f183bd428b95.png)

Workforce:
![image](https://cloud.githubusercontent.com/assets/17730847/15516059/df3ea39e-21a5-11e6-8383-8a7fd2e77579.png)

Survey123:
![image](https://cloud.githubusercontent.com/assets/17730847/15516048/d19332d2-21a5-11e6-876e-dd1f8e83428d.png)


Help!?!

**Comment by survey123** [comment]
Issue reopened. An Esri Tech Support analyst will contact with you. Please email us at survey123@esri.com and reference this issue so we can create an incident. Thanks, Ismael.

**Comment by colgateg** [comment]
Response from ESRI support...

Hi Glen,

It was a pleasure speaking with you just now. I'm sorry the enterprise logins are not quite yet available at the this time for Android and iOS.

Hopefully the next release of Survey123 will have the Enterprise login functionality working on Android and iOS! If you still have problems at that time, please do not hesitate to contact me. We can easily reopen this case and see what is going on!

As always, you can reach me by either responding to this email or calling (888) 377-4575 and referencing your case number, 01784101.

Cheers,
Andy
Esri Support Services

**Comment by justingreco** [comment]
I do see the option to sign in with Enterprise logins.  I enter my organization's URL, but when I tap on the Using Your Organizational Account button, nothing happens, I am not directed to our ADFS sign in page.  I do notice that the word Account on the button is wrapped outside of the actual button, not sure if that is part of the issue.

**Comment by colgateg** [comment]
Our problem persists in 1.6.11... If anyone could give me heads up on the status of BUG-000097678 that would be awesome. :)

Thanks.

**Comment by survey123** [comment]
Sorry Glenn. Proving a difficult one. We continue working on this one and will update you when we make some progress.

**Comment by survey123** [comment]
Planned for Nov 7,2016

**Comment by survey123** [comment]
This did actually make it into the November release, so closing this issue.
