### ISSUE TITLE
sign in and cancel buttons only half visible in sign in form in survey 123 connect app

### ISSUE THREAD

**Issue by mhogeweg** [Esri/Survey123Community#46]
installed the survey 123 connect app 1.0.59 and tried logging in. the sign in and cancel buttons are only half visible and overall the font seems a bit BIG.

![survey123connect_signin_dialog](https://cloud.githubusercontent.com/assets/394890/6899114/2f9b5a6a-d6b3-11e4-9725-b4a3612197f2.png)

**Comment by survey123** [comment]
Could you please give us the details of your machine / screen? 
We have put in a lot of work in ensuring that the Survey123 UI scales correctly on different devices / screen resolutions. We have not seen this particular scaling issue on any machines we have tested so far, so we would love to be able to reproduce (and fix) this issue. Thanks :)

**Comment by mhogeweg** [comment]
sure: dell precision M6700 with 16GB RAM, windows 7 64-bit, and 2 1920x1080 monitors

**Comment by survey123** [comment]
Thank you for the extra information. This issue has been raised with the development team.

**Comment by survey123** [comment]
Please download the latest version of Survey123 and let me know if the scaling on the Sign In dialog has improved :)

**Comment by survey123** [comment]
@mhogeweg 
Closing this issue. Fixed in 1.0.79. Thanks for the feedback.

**Comment by mhogeweg** [comment]
confirmed fixed!
