### ISSUE TITLE
URL Schemes for iOS

### ISSUE THREAD

**Issue by Robert-W** [Esri/Survey123Community#464]
I am relatively new to iOS development and would like to be able to link my mapping application using the iOS Runtime SDK to Survey123.  Does Survey123 have any support for using URL schemes in iOS (something like survey123://<params>)?  And if so is there documentation on what the syntax is?

**Comment by survey123** [comment]
You almost had it!  Try: arcgis-survey123://
We plan to support parameters such as the Form item id to be launched. Stay tuned.

**Comment by Robert-W** [comment]
Great thanks, I will definitely stay tuned.
