### ISSUE TITLE
survey123.arcgis.com download csv file - error with formatting and carriage returns

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#466]
When downloading survey data in CSV format via the Data tab on the survey123.arcgis.com website, there is an issue with the formatting of the data when the CSV files are opened.

If a survey text field contains a carriage return the data exported in CSV will be separated for that record and displayed on the line below which then miss aligns all data fields with their headings. See images below. Can the export CSV format be changed to allow carriage returns to exists in a cell, or if not possible, an other option is to remove the ability to enter carriage returns in a text input box in the Survey123 app?

![image1](https://cloud.githubusercontent.com/assets/19141448/15382133/0d12f912-1dca-11e6-99c1-c41c7a20499f.PNG)
![capture](https://cloud.githubusercontent.com/assets/19141448/15382134/12124918-1dca-11e6-8226-207b6eda0e26.PNG)

**Comment by survey123** [comment]
Hi Phil. Thanks a lot for your feedback! The ArcGIS Online team is working on this as we speak. We are planning to have this fixed in the next ArcGIS Online update (June). If the fix does not make it for June, we will try to make it into the next update of ArcGIS Online.
In the meantime, I suggest you download as FileGeodatabase or Shapefile. If in Shapefile, you can load the dbf in Excel directly.

**Comment by phil-wilson** [comment]
Thanks for your reply. I have been using a FGDB which is working fine, it was only because I was demonstrating the survery123 portal to someone else and showing them how to download to CSV that came across the issue. Thanks again, look forward to the update.

**Comment by sunyu0530** [comment]
+1

**Comment by survey123** [comment]
Quick follow-up: This issue is expected to be resolved with the next update to ArcGIS Online, which is expected to be made available before the end  of this week. Thanks all for your feedback.

**Comment by sunyu0530** [comment]
Cheers!

**Comment by survey123** [comment]
Closing. This has been fixed. Thanks!
