### ISSUE TITLE
Using Multiple images or other media per select_one?

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#468]
I'm using the [Birdwatcher](https://www.arcgis.com/home/item.html?id=777cc3369c704773bdb6544b12eba3fb) as an example. Would it be possible to have multiple images per radio button, such as egg, hatchling, nest, and adult images?

Also, does the media folder works with subfolders? In this example, could an image within a subfolder be referenced with something like "\\media\eagle\egg.jpg"? 

Thanks

**Comment by survey123** [comment]
Hi!
Unfortunately not. Only one image per choice.
Subfolders are fine. Simply make sure you get the path spelled perfectly when referencing images.
Closing issue.

**Comment by DShokes** [comment]
Thanks @Survey123. I ended up tiling the images into one with the montage
command line function in ImageMagick.  Would you happen to know the syntax
for the relative path with sub folders? Otherwise I can just do trial and
error.
