### ISSUE TITLE
typo in survey 123 connect dialog

### ISSUE THREAD

**Issue by mhogeweg** [Esri/Survey123Community#47]
version 1.0.59. the third sentence in the left panel in the Survey 123 Connect app reads 'Survey 123 forms may authored by creating XLSForm spreadsheets'. This should read something like: 'Survey 123 forms may *be* authored by creating XLSForm spreadsheets'

**Comment by survey123** [comment]
Thank you. This issue has been raised with the development team.

**Comment by survey123** [comment]
@mhogeweg 
Fixed in 1.0.61 
Thanks a lot.
Closing issue.
