### ISSUE TITLE
Hidden Barcode with substr calc error

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#470]
I am trying to create a survey containing the following:
Barcode field (hidden) with three substr calculations from the scanned text. I am getting the following error when i try to save my spreadsheet and preview the form (BarcodeError.jpg).
I have attached the spreadsheet as well for review.
Thanks,
--gary
[Up
![barcodeerror](https://cloud.githubusercontent.com/assets/14822701/15433214/67ef616c-1e7f-11e6-8257-a55dd5d1441b.JPG)
loading AGP_Barcode.xlsx…]()

**Comment by survey123** [comment]
Closing. Addressed in GeoNet Group. 
 https://geonet.esri.com/thread/177431
