### ISSUE TITLE
Error Code 403 - Request not made over ssl - since upgrade to 1.4.30

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#472]
After upgrading Connect to 1.4.30 and publishing a new survey update with minor changes, and updating the iPad app to 1.4.28, I am unable to Send surveys. The error is Code 403 - Request not made over ssl (see error screenshot below).

Sending surveys was working fine previously and no other settings have been changed, internet connection is the same. I also tested the previous version of the survey (different feature service) and this is able to send successfully from same device using same version of the app 1.4.28 (just a different version of the survey which was publish using 1.3.18).

Any ideas?

![image1](https://cloud.githubusercontent.com/assets/19141448/15459248/ad3dafc6-20e6-11e6-95da-ddb74862dfb3.PNG)

**Comment by phil-wilson** [comment]
Any update on this, I am getting the error on either Wifi or 4G? Still unable to upload surveys using new version of app and newly published feature service using latest version of connect?

**Comment by phil-wilson** [comment]
I have resolved this issue. After deleting all downloaded surveys, signing out of the app, signing back in and downloading the new updated survey again, appears to be working fine, no 403 errors anymore and surveys are able to be successfully sent.

**Comment by survey123** [comment]
Thanks @phil-wilson 
Closing this until we get a case that we can repro.
Sorry we could not help earlier as we did not have a lead to put you in the right track.
