### ISSUE TITLE
Linking QR code to Survey

### ISSUE THREAD

**Issue by kc-lee** [Esri/Survey123Community#474]
Was thinking if we could scan a QR code to invoke a particular survey?

The rationale is going to different locations and accessing different surveys.

Thanks.

**Comment by survey123** [comment]
Thanks for your feedback. Tagging as an enhancement.

**Comment by survey123** [comment]
Sorry we missed updating this issue.
QR Codes are available for your surveys in survey123.arcgis.com
See http://doc.arcgis.com/en/survey123/browser/create-surveys/sharesurvey.htm for more information on this.
