### ISSUE TITLE
Different Survey123 publishing error 400

### ISSUE THREAD

**Issue by gis-Wilco** [Esri/Survey123Community#486]
When publishing a survey, I get a publishing error code: 400. "Invalid tenant Id. Unable to find tenant in database. Invalid tenant login."  Any ideas on how to correct this issue?  
![survey123](https://cloud.githubusercontent.com/assets/19711063/15747701/953a998a-28a1-11e6-97da-7a9f05eef20b.png)

**Comment by bowlesgsrcx** [comment]
Check this out, maybe it can help:
https://geonet.esri.com/thread/76796

--gary
