### ISSUE TITLE
Survey123 Web Site not working against ArcGIS Online SSL-only orgs

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#49]
Survey123 web site fails to log users in if the user belongs to an org set as SSL only.  The web site should work on https only.  

How to repro:
- Make your ArcGIS Online organization accept only https request (in Settings)
-In the Survey123 web site, attempt to log in
-No error or warning is displayed, but you will not be able to open the Survey Gallery.

**Comment by sathyaprasad** [comment]
@Cintruenigo Can you please test this issue and let me know

**Comment by Cintruenigo** [comment]
Magical! Thanks!

**Comment by survey123** [comment]
Closing issue.
