### ISSUE TITLE
ArcGIS Online Items/Sync

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Survey123Community#492]
When you publish a survey from Survey123 Connect, a feature service and form item get created in your ArcGIS Online account within a new folder. If you delete the original survey created in Survey123 Connect, you have no way to reference the survey that you created and published.

If the content of this folder stored within Survey123 Connect (i.e. C:\Users\<username>\ArcGIS\My Survey Designs\<surveyname>) could be published within a zipped file as an item in ArcGIS Online it would be very useful.

Furthermore, an option to sync with your ArcGIS Online account would be beneficial. So if you have any surveys within your ArcGIS Online account, you are given the option to download them to edit/update the survey as necessary in Survey123 Connect.

**Comment by survey123** [comment]
Hi,

 This are great suggestions. Here is  our plan to accommodate them.

 * In our June 20th release we will be added a New Survey Dialog which you will be able to use to create new Surveys from existing Surveys in your ArcGIS Online organization. This will allow you to create a NEW survey from an existing one that may have already been published and shared with you.

![newsurvey](https://cloud.githubusercontent.com/assets/10968332/16049610/d239a076-3204-11e6-82d7-3e3f86382460.png)

* We will also add an option to duplicate Surveys you already have locally as shown in the screenshot below. Again, this option is only useful, like the previous one, to create a NEW survey from an existing one.

![copysurvevy](https://cloud.githubusercontent.com/assets/10968332/16049685/251e5476-3205-11e6-9346-d54dac6289b1.png)

* For an upcoming release, we want to implement an option where you can work on already published Surveys and edit them (change their questions, etc), even if  you do not have the Survey locally in Connect. In the meantime, here is what you can do to download a Survey and edit it in Connect:
    * Download the Desktop version of the app
    * Use it to download the Survey you want to edit
    * Then go into the MySurveys folder. For example: C:\Users\Ismael\ArcGIS\My Surveys
    * Copy your Survey into the My Survey Designs C:\Users\Ismael\ArcGIS\My Survey Designs folder
    * Now open Connect and you will see your Survey ready for editing and publishing again. 
This manual technique described will not create a NEW copy of your Survey in ArcGIS. It will let you overwrite it.

**Comment by MKellyEsri** [comment]
Thanks for the quick reply. That's absolutely perfect - looking forward to the release next week!
