### ISSUE TITLE
Wildcards?

### ISSUE THREAD

**Issue by icecapfunko** [Esri/Survey123Community#493]
The standard excel wildcards don't seem to work with survey. I'm trying to use a multi choice list, and some of the choices cascade down. So I'm trying to use $(list)= "Other" and "*". 
Am I just doing this wrong or are there different wildcards here?

**Comment by icecapfunko** [comment]
After testing this more, it seems to be a problem with the multi choice feature. The and function just does not work when multi list is used.

**Comment by survey123** [comment]
Hi. Apologies for the belated response.
I am not clear what exactly you would like to do:
* Evaluate if Other was selected: selected(${question},'other'). This function will return true even if other options in the list, in addition to 'other' were selected.
* Evaluate if Other and ALL the other choices where selected: count-selected(${question},5)  (assumes you have 5 choices including 'other;).

There is absolutely no wrong place for questions, and we appreciate you reaching  out of help with  Survey123. I would like to suggest you post your Survey123 question in our GeoNet group at: https://geonet.esri.com/groups/survey123   You will need to join the group before you can add your questions, but you  will most likely get more  timely responses there.

 Thanks a lot!
