### ISSUE TITLE
Ability to pre-load data from a CSV file into the Survey123 App to pre-populate fields

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#495]
Need the ability to pre-load data from a CSV file or similar into the Survey123 App on the device, to be able to pre-populate text fields and large data entry boxes to save time typing into device. Can an import function be added to the app, provided that a template for the csv file is used that matches the form design?

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
