### ISSUE TITLE
Orphaned Survey

### ISSUE THREAD

**Issue by SkeenP-NGSC** [Esri/Survey123Community#497]
I've got a survey with a broken link to a feature class that i cannot open to fix or delete.
![untitled](https://cloud.githubusercontent.com/assets/17419564/16069749/2f0aa6aa-3314-11e6-9a06-55bb17cb1d3c.png)

**Comment by survey123** [comment]
Hi Paul. You can delete the survey as follows:
1) Log in to arcgis.com
2) Go to your contents
3) Look for the survey123 folder for  this specific survey and delete it

**Comment by SkeenP-NGSC** [comment]
Thanks, didn't realise it was also managed in contents. Handy to know.

Regards
Paul



*Paul  SkeenGIS OFFICER**------------------------------------------*
Email: paul.skeen@ngshire.vic.gov.au (Preferred Contact)
<http://www.ngshire.vic.gov.au/Home> <http://www.ngshire.vic.gov.au/Home>
<http://www.ngshire.vic.gov.au/Home>
PO Box 580, Stawell, Vic 3380 (Email Preferred)
Phone: 03 5358 8700
www.ngshire.vic.gov.au

<https://northerngrampians.formsport.com.au/default.aspx>
<https://northerngrampians.formsport.com.au/default.aspx>
<https://northerngrampians.formsport.com.au/default.aspx>
<https://northerngrampians.formsport.com.au/default.aspx>
<https://northerngrampians.formsport.com.au/default.aspx>[image: Electronic
Rates Enrollment] <https://northerngrampians.formsport.com.au/default.aspx>
