### ISSUE TITLE
EXIF metadata is lost when using the camera widget in Survey123 field app

### ISSUE THREAD

**Issue by anthonyrandell** [Esri/Survey123Community#498]
Possibly related to #450 ?

I am using an Android 5.1.1 Vodafone Smart Ultra 6 phone.

When I use the built in phone camera I can set it up to record location information in the photo exif.  (Select settings gear icon in top left - turn location tag on - turn location settings on and wait for GPS fix).

When I use the camera widget from within Survey123 (with camera and location settings set as above); there is no option to access the camera settings and any photos taken do not record location information in the photo exif.

![phone - geotagged](https://cloud.githubusercontent.com/assets/19570388/16077182/2c33c4a4-32ef-11e6-8adb-1456564ac574.jpg)

![survey123 - not geotagged](https://cloud.githubusercontent.com/assets/19570388/16077189/3f115e1a-32ef-11e6-8fb3-87de140e0b71.jpg)

This may get confusing as you can use the map widget to select a different location than your current position and your geotagged photo would then be tagged with a different location than where it appears on the map.  Probably this should be a setting  as I can imagine different use cases.

Many thanks,
Anthony

**Comment by survey123** [comment]
Hi Anthony. Thanks so much for reporting this. This is a known limitation at the moment. The Survey123 app will drop your  exif information. We are trying to fix this.

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17

**Comment by anthonyrandell** [comment]
Thanks - quick note to say I have retested and this works fine.  All EXIF information including location preserved for stored photos on device.

Many thanks for fixing this.
