### ISSUE TITLE
Edit and Creation Date values in Results Table not legible

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#5]
Steps to repro:
1) Publish a Survey and add a couple of entries using the Survey123App
2) In the Survey123 web site, go to results for the survey and look at the Creation and Edit date values for your entry. You will something like: 2015-02-14T03:49:44.763Z

**Comment by spatialdude** [comment]
The web site should be able to use the feature service's info to determine which fields in a layer/table are being used for editor tracking.

**Comment by Cintruenigo** [comment]
editFieldsInfo discloses the names of fields used by editor tracking.  If editFieldsInfo is null, no editor tracking is enabled. 
To get editFiedsInfo on a feature service layer call <URL to feature service>/layerID&f=json
Below is an example of the json you get back with the editFieldsInfo 


{
  "currentVersion" : 10.3, 
  "id" : 0, 
  "name" : "Test", 
  "type" : "Feature Layer", 
  "displayField" : "name", 
  "description" : "", 
  "copyrightText" : "", 
  "defaultVisibility" : true, 
  "editFieldsInfo" : {
    "creationDateField" : "CreationDate", 
    "creatorField" : "Creator", 
    "editDateField" : "EditDate", 
    "editorField" : "Editor"
  },
....
}

**Comment by Cintruenigo** [comment]
Looks like the date formatting issues apply to all fields in general. In the image below for example, the LastCheckIn column is for a date.

![untitled](https://cloud.githubusercontent.com/assets/1273440/6241279/34033202-b6cf-11e4-99b6-1162d11b863f.png)

**Comment by survey123** [comment]
Thanks. Fixed. Closing.
