### ISSUE TITLE
Page jump when filling out survey

### ISSUE THREAD

**Issue by mefong** [Esri/Survey123Community#506]
When filling out a survey, the page often jumps back up to the top of the survey despite having just filled out a question near the bottom of the survey. Is there a way to bring it to where the user left it or to the last selected question without having to scroll back down?

**Comment by phil-wilson** [comment]
I have noticed this same behaviour, it often happens after adding an attachment (photo) and return back to the survey from the select file or take photo box, and the survey jumps back up  to an earlier point in the survey (previous questions).

**Comment by cconnolly91** [comment]
What OS and device are you using? This used to be an issue on a previous version of Survey123 on iOS, but was resolve in recent updates, make sure to check you're using the most up to date version :)

**Comment by mefong** [comment]
Resolved! The page jump used to occur with the beta version; glad it's fixed. Tested on android and apple devices.

**Comment by marikavertzonis** [comment]
it appears this is fixed in some cases only. super long survey still demonstrates the problem.
