### ISSUE TITLE
Cannot update existing installation of Survey123 on Android via HockeyApp - uninstall first

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Survey123Community#51]
With the release of Survey123 1.0.64, I attempted to update it via the link in the email on my devices (Samsung S4 Mini and Lenovo Tab) which both already had the previous version. In both cases, the .apk downloaded successfully, and when I launched it recognized that a previous version was installed and asked if I wanted to update. It then looked like it was installing but finished with an error message
_"App not installed. An existing package by the same name with a conflicting signature is already installed"._
When i uninstall the exisiting app first, and then install - it completes as expected.

**Comment by sathyaprasad** [comment]
This will happen if you have side loaded the previous version of app via a URL and then used Hockey app to update the app.

**Comment by marikavertzonis** [comment]
I used Hockey app to install both versions and the error still happened.
