### ISSUE TITLE
DateTime Field Issue

### ISSUE THREAD

**Issue by matthysjake** [Esri/Survey123Community#512]
When using a dateTime field, the user is unable to select today's date when the calendar picker opens.  The calendar picker will close without populating a date or time in the dateTime controls.  To pick today's date, the user must select a different date, then open the calendar picker again and pick today's date.  I have experienced this issue in iOS devices and in Survey123 Connect.

**Comment by survey123** [comment]
Use the expression today() in the default column to automatically set the date to today. In this manner users will not even need to touch the widget, if the intent is to set the date to today

**Comment by matthysjake** [comment]
Thank you for the quick feedback.  The intent is to allow the user to choose the date and time to schedule an event.  Lets say that 50% of the time they will want to populate the dateTime field with today's date, and in the other occurrences, they will want to choose a dateTime in the future.  For this reason, the today() function won't work.  In experimenting with 123Connect, I noticed that Date (only) question types do not have this issue.  In other words, you can open the date picker and choose today's date when testing your survey in 123Connect.  But when using a dateTime question, you cannot immediately select today's date.
Thanks,
  -Jake

**Comment by colgateg** [comment]
Using a default value in this case could place a cloud over the survey record. The result would be unclear if the user wanted the date selected, or just passed over the question and the date is erroneous. Its better to allow the control to explicitly select today's date.
