### ISSUE TITLE
Survey123Connect only Publishes Hosted Feature Services in WGS84

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/Survey123Community#52]
Hosted Feature Services created from the Survey123Connect app are created in WGS84 (4326).  

Is it possible to publish a hosted feature service in other projections?

**Comment by sathyaprasad** [comment]
@jmirmelstein  When you consume feature service using ArcGIS server either hosted or on premise it can return back features in any supported projection. I am not sure what exactly are you asking for here.

Example: Feature service  can be in WGS 84, you can add this feature service to a webmap which is in Web Mercator or to a different Web Map which is in Stateplane.
