### ISSUE TITLE
Downloading XLS Form from existing Web Survey online.

### ISSUE THREAD

**Issue by WeASeL-Antigua** [Esri/Survey123Community#520]
I used the Survey123 Connect to create and publish a survey in the past. My system crashed and I had to do a clean install of my operating system which successfully wiped my existing local save of the XLS form.

The survey still exists on Survey123 [here](http://survey123.arcgis.com/surveys/31734c8e94ee4c659f75c29c070da72f) but I would really like to download the XLS form so that I can edit it using Survey123 Connect.

How can I do that?

**Comment by survey123** [comment]
Hi @WeASeL-Antigua ,
Currently, we don't have an option to download the survey or the XLS form directly from survey123.arcgis.com. 

The workaround is to use the [updated Survey123 Connect](http://doc.arcgis.com/en/survey123/download/), after installation, open it, select New Survey, click the Sign In button in the bottom left, sign in with your AGOL account, then you will find your previous survey in the "My Surveys" category. You're now ready to create an exact same survey with your previous one.

**Comment by WeASeL-Antigua** [comment]
![image](https://cloud.githubusercontent.com/assets/18103637/16905530/37a7758e-4c75-11e6-9e61-804630cb1aa9.png)


![image](https://cloud.githubusercontent.com/assets/18103637/16905551/9f2111d4-4c75-11e6-810b-5b420830d758.png)


No Bueno.

**Comment by survey123** [comment]
OK. Here are some steps to manually recover your survey:
1) Download the Survey123 field app into your Desktop: http://doc.arcgis.com/en/survey123/download/ 
2) Login into the Survey123 field app in your Desktop and download your surveys
3) Navigate to the ArcGIS/My Surveys folder using a file explorer:
* On Windows: C:\Users\<your username>\ArcGIS\My Surveys
4) The directories with the cryptic names contain your surveys, including their thumbnail and XLSFiles. You can now recover your XLSFile and create a new survey with it.
