### ISSUE TITLE
Survey123 Connect Application Error

### ISSUE THREAD

**Issue by abrazell** [Esri/Survey123Community#521]
Event Viewer Application Error ID 1000 Task Category 100 

Details
Faulting application name: Survey123ConnectforArcGIS.exe, version: 1.5.35.0, time stamp: 0x57638239
Faulting module name: Qt5Qml.dll, version: 5.6.0.0, time stamp: 0x56d8645a
Exception code: 0xc0000005
Fault offset: 0x000c85ed
Faulting process id: 0x2774
Faulting application start time: 0x01d1e1dd1f193d6f
Faulting application path: C:\Users\abrazell\Applications\ArcGIS\Survey123ConnectforArcGIS\Survey123ConnectforArcGIS.exe
# **Faulting module path: C:\Users\abrazell\Applications\ArcGIS\Survey123ConnectforArcGIS\Qt5Qml.dll**
Report Id: 9322328d-4dd0-11e6-b867-104a7de9c4eb

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
