### ISSUE TITLE
Calculated Location doesn't Overwrite

### ISSUE THREAD

**Issue by kmsternhagen** [Esri/Survey123Community#522]
Whenever I tap to open the map and move the coordinates to a different location on the Calculate Location template, it does not overwrite the preset location. It's great for setting multiple default locations, but our users need the option to either accept the preset coordinates or choose an alternative  location.

**Comment by survey123** [comment]
Thanks. This is not the expected behavior and have added this  to our backlog.

**Comment by survey123** [comment]
Adding to our September 2016 release.

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
