### ISSUE TITLE
Having an issue using 123 connect with Microsoft Excel 2007. 

### ISSUE THREAD

**Issue by chrisbycreme25** [Esri/Survey123Community#523]
When I open a new survey and want to choose a different type field there is no drop down menu for the cell to choose from the list of options. This is not a major issue as the type options are available online but for other members of my organization whom are not as familiar with survey123 or excel this poses quite a problem. Is this due to the fact that the drop down menu is not compatible with this version of Excel?

**Comment by survey123** [comment]
Hi. Unfortunately, the data validation and drop-downs are designed to work on Microsoft Office 213.
