### ISSUE TITLE
Hiding geoPoint ?

### ISSUE THREAD

**Issue by LuisCRUY** [Esri/Survey123Community#526]
I'm experimenting with Survey123. I want to hide the geoPoint field. Is this possible?
That is because i want to collect the GPS location **without the manual user input**.
Thanks.

**Comment by survey123** [comment]
Hi. Create a Survey with no geopoint question. :) Voila! Now you got it!

**Comment by LuisCRUY** [comment]
Thanks for your answer. Perhaps I explained wrong my issue: I need to use the geoPoint but I don't want to give the user the option of picking the location. I want to capture the location but without the user interaction...

**Comment by survey123** [comment]
Ah! Then add a geopoint question and flag it as readonly.
