### ISSUE TITLE
Downloading forms but they appear blank on devices.

### ISSUE THREAD

**Issue by gavfc** [Esri/Survey123Community#527]
So I've created a few test forms using the drag and drop widget on survey123.arcgis.com. When I preview them on my desktop they look great, exactly what I want to see. I then publish them to my group. I've used three devices; Samsung Galaxy S4, Ipad mini 2 and a Blackberry Z30 using a workaround. All give the same response, I log in, I can see the forms, I'm able to download the forms but when I open them I get a blank form with the green top and bottom bars.

Has anyone else come across this issue, or know what I'm doing wrong?

Thank you.

**Comment by survey123** [comment]
Are you using a web browser in your device to open the Forms, or are you using the Survey123 mobile app?

**Comment by gavfc** [comment]
on all devices the app was downloaded

**Comment by survey123** [comment]
Hi @gavfc ,
Can your please confirm is this what your problem? https://geonet.esri.com/thread/179801
If not, would you mind to share some details about your form? Such as the form title, or the question details?

**Comment by gavfc** [comment]
I can confirm this is the issue. I didn't have any ampersands in the title but I removed them from the questions and answers and my forms appeared. Thanks

**Comment by survey123** [comment]
Hi @gavfc , thank for the confirmation, the good news is this bug has already been fixed, and will be delivered in the Sep. release.

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
