### ISSUE TITLE
Save as Favorites - Specify Questions?

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#528]
Is it possible to have the ability to exclude certain questions from being saved as favorites? We are using Survey123 to collect data at a set location approximately 6-10 in a day. There is certain data that can be saved as favorite and will not change but there is some like pH, TDS, conductivity that is measured each time that we do not want to have anything saved as a favorite. Doable?
Thanks,
--gary

**Comment by survey123** [comment]
https://geonet.esri.com/thread/180740

**Comment by bowlesgsrcx** [comment]
That is what we instructed the field staff to do. Unfortunately, some of the workers saved some of the attributes that they shouldn't have as favorites, and that led to many re-sends of the data with corrections. This in turn led to more time needed to manage the data on the back end. That is why we are hoping that at some point in the future, there can be a way possibly with a field in the xlsx file that can specify "Save As Favorite" as a Yes/No field and that would be honored in the form when published. Not sure if this is doable but wanted to throw it out for people to chew on. This way, we can make the forms even more "error-proof".
Thanks,
--gary
