### ISSUE TITLE
Code 500 - Inconsistency in the Field Definitions

### ISSUE THREAD

**Issue by jamietill** [Esri/Survey123Community#531]
I have a survey which uploads and works as expected in ArcGIS Online, however i get a Publishing Error - Inconsistency in the Field Definitions found when publishing to my ArcGIS Portal. I have Portal 10.4.1 and  Connect version 1.6.11.  Data Store is all configured and is the Managed Database, when i publish it creates the folder and feature service in My Content, the Form doesn't show and the feature service appears to be corrupt. 

The survey itself is quite complex, it has cascading selects which i believe use to be an issue but should now work. Could someone please take a look at my survey and see if there is anything obvious that i have missed? 
[Engineering Site Inspection.xlsx](https://github.com/Esri/Survey123Community/files/400656/Engineering.Site.Inspection.xlsx)

**Comment by tedrick** [comment]
Hi there,

In looking at your form, you have a question that creates a field named 'entity'- that's a reserved word in the ArcGIS Data Store's database.  I was able to publish successfully by renaming it to 'entity2' and updating the choice filters.

Please join us over at the [Survey123 GeoNet community](https://geonet.esri.com/groups/survey123)- it's a bit more active than GitHub

**Comment by jamietill** [comment]
Many thanks James, this solved it. Thanks for the prompt response, much apreciated
