### ISSUE TITLE
can't submit survey

### ISSUE THREAD

**Issue by kevintheflesh** [Esri/Survey123Community#532]
I published a couple of new surveys recently but during testing we have been unable to submit the data. We click on the submit button and nothing happens. If we choose to close the survey it gives us the option to save in Drafts but that button doesn't do anything either. We can only close survey and lose changes or continue survey. We have tested this on iphone, ipad, and windows pc apps.

**Comment by survey123** [comment]
Are you by any chance  using the Instance_Name column in the Settings tab?
I have seen this behavior happening when the Instance_Name expression is not syntactically correct

**Comment by kevintheflesh** [comment]
Yes, I added instance name on the settings tab. I've tried to remove it but I have frustrating inconsistent ability to publish a survey in order to properly test to see if that solved my problem.

**Comment by insect1285** [comment]
@kevintheflesh We had similar issues if:
1) We were on the wrong version of Survey123.  If a survey was published in an old version, you will need to update; or
2) We had one of several bugs noted in this repository - which we've had to work around.

Do you get any errors?  Have you tried to enable logging in your apps and then submitting the error logs to Esri Customer Support?

**Comment by survey123** [comment]
Please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
Suggest that you install the latest  version and try again. Problem with Instance_Name should be addressed now.
