### ISSUE TITLE
Analyze Tab in Survey 123 Not Loading

### ISSUE THREAD

**Issue by CaseBudds** [Esri/Survey123Community#536]
Hello,

I am having trouble with one of my surveys not showing up when I hit "analyze". It acts as if it is continuing to load but never displays.  I have tried in different browsers. I know that some data types are not supported for analyze, but shouldn't the acceptable ones show up? It is a rather long survey too. I did not know if this was a known issue or not.

Best,

Casey

**Comment by survey123** [comment]
Hi @CaseBudds , 
Would you mind to post this issue on [GeoNet Survey123 group](https://geonet.esri.com/groups/survey123), so it can be shared with others with the same problem?

**Comment by CaseBudds** [comment]
I have posted in GeoNet Survey123 group as well.

Best,

Casey

**Comment by survey123** [comment]
Hi @CaseBudds , thanks! We'll take over from there. Closing this issue now.
