### ISSUE TITLE
How to delete/revise a record when geoLocation was not set.

### ISSUE THREAD

**Issue by soggypickle** [Esri/Survey123Community#540]
I was testing one of my surveys and uploaded the information without a geopoint set. I want to delete this test data. I normally would open the data in map viewer and click on the points and then delete them. However, I have no location information. I saw a similar issue posted here https://github.com/Esri/Survey123Community/issues/419. In that post they suggest using Pro, but I do not have pro. How can I delete these records!?

**Comment by tedrick** [comment]
There are a couple of methods I can think of, one retail editing, one through a script:
1) I was able to set up a Web AppBuilder with the survey question in the map and both the table and editing widgets.  You can go through the survey list and select the ones without geometry (you won't see a highlight on the map; you can also identify them by the fact they disappear when you use 'Filter by Map Extent' at an extent that encompasses all of the responses)  Select the records and use the Edit Widget's 'Delete' button to delete the selected
2) You can create a script to find those without geometries and then delete (or update with a geometry):
-- Query the Feature Layer endpoint for all objectIDs (where would be 1=1 and the returnObjectIds parameter is true)
-- Query for all those objectIDs with valid geometry (where: 1=1, returnObjectIds: true, an extent sufficiently large to encompass the survey (For example, an envelope of -180,-90,180,90 with spatialReference 4326 (i.e., WGS 1984))
-- Compare the results; remove the results of the second query from the first.  The remaining results are the points without geometry
-- From here, you could pass the resulting objectIds into the either the Delete or ApplyEdits operation of the Layer in the Feature Service; you could also create a point for them and Update.

**Comment by phil-wilson** [comment]
As you suggest the best way is using ArcGIS Pro 1.3.

If you have an ArcGIS Online account and valid ArcGIS licences then you can download and use Pro.

Open the feature service in Pro and you can create/delete features, assign coordinates using the reclassify feature tool, delete/update related records etc.

**Comment by insect1285** [comment]
You can also use a REST Query to delete features or a edit the feature to have a proper XY coordinate. 

Visit the service layer URL, scroll to the bottom and select the query option you would like.

For Delete See: http://help.arcgis.com/en/arcgisserver/10.0/apis/rest/fsdelete.html
For Update See: http://help.arcgis.com/en/arcgisserver/10.0/apis/rest/fsupdate.html

**Comment by sunyu0530** [comment]
@soggypickle 
If you wish to update a geolocation for the record in future.

I have a case number with esri related to issue hope can help anyone.
#01809855

you can do the following:

through REST, go to the service URL for my service, then in the layer level, clicked on "Update Features" at the bottom of the page (http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Update_Features/02r3000000zt000000/).
 Another way to get there is to use the following syntax: http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/SanFrancisco/311Incidents/FeatureServer/0/updateFeatures

I then copied and pasted into the text box the following array:

[
    {
      "attributes" : {
      "OBJECTID": 1
      },
      "geometry" : {
        "x" : -90.5,
        "y" : 45.5
      }
    }

Note: survey123 create objectid field as lowercase. the syntax in the update feature window is case sensitive.
