### ISSUE TITLE
Unable to publish to ArcGIS Portal Survey123

### ISSUE THREAD

**Issue by jplunkett1** [Esri/Survey123Community#544]
Hi there 
I am trying to publish a survey to ArcGIS Portal 10.3.1
I am getting this error

However from the same machine I can publish to the Portal from ArcGIS Pro on the same instance

![image](https://cloud.githubusercontent.com/assets/7854161/17914398/d3bd2d22-69f5-11e6-9cb1-4efb163d41a6.png)

Survey123 Connect 1.6.11

Does anyone have any tips on what I can do to resolve this?

**Comment by bowlesgsrcx** [comment]
Go into Portal and delete Survey-Form 1 folder. Then re-publish.
--gary

**Comment by jplunkett1** [comment]
HI Gary/Esri
http://screencast.com/t/DuB6edrI
This is what is happening on my Portal, - have you seen this?

**Comment by tedrick** [comment]
Can you share your form?  It looks like while the feature service is being created, the Survey123 form is not (these are separate items created because there may be potentially additional logic stored in the form than we can place in the feature service).  Also, does the form feature service you created add to a map in Portal successfully?

**Comment by jplunkett1** [comment]
HI James
The Form is the Arrest Form Template
Survey123 > Community > Arrest Form

I can invite you to portal as well if you would like.
Thanks
john P

**Comment by jplunkett1** [comment]
Also the feature that shows in the Portal does not load correctly. 
![image](https://cloud.githubusercontent.com/assets/7854161/17953000/a1da185a-6ac3-11e6-885c-f8cf424e8cd3.png)

**Comment by tedrick** [comment]
Okay, that looks like it may be more of an issue with your Portal as publishing of the feature service failed.  Can you call Esri Support, who can further diagnose what is the problem?

**Comment by jplunkett1** [comment]
Sure I can do that. However from the same machine I can successfully publish to my Portal from ArcGIS Pro.
