### ISSUE TITLE
Survey123 Connect Version 1.6.11 Freezing when too many Surveys

### ISSUE THREAD

**Issue by anthonyrandell** [Esri/Survey123Community#545]
Possibly related to #509 ?

**Symptom**
Survey123 Connect freezes when trying to open a survey in Windows 7. 

**Resolution**
Went into "My Survey Designs" folder and removed all Survey designs bar 2 (moved the rest into a different folder structure).

Survey123 Connect then worked normally.  

I had 13 surveys in the  "My Survey Designs" folder when Survey123 Connect was freezing.

**Comment by insect1285** [comment]
This bug occurred in v1.5 also on Windows 10.

**Comment by survey123** [comment]
Thanks folks. We have a fix for  this issue which we plan to make available in the next few days.
We will announce the new release on:
*  Twitter: https://twitter.com/esriSurvey123
* GeoNet: http://geonet.esri.com/groups/survey123

**Comment by survey123** [comment]
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17
