### ISSUE TITLE
Suggestion:  Patch Notes or Commit Comments for New Releases; Update Notice to Desktop Applications

### ISSUE THREAD

**Issue by insect1285** [Esri/Survey123Community#546]
Hi,

I just saw that version 1.6 is out, but I could not find patch notes, commit comments, or an update function in any of the applications. I would appreciate seeing those notes to know which bugs have been squashed and which features have changed.  This may impact how I develop forms as I have several work-arounds I currently use.

Thank you!

**Comment by insect1285** [comment]
Update: Noticed that you do use the Milestones to note which issues have been closed, but I think a lot of users don't know about this or check Github regularly.  Something more up-front would be nice.

**Comment by tedrick** [comment]
For what's new information, please refer to the official documentation for Survey123 for ArcGIS, at [http://doc.arcgis.com/en/survey123/desktop/create-surveys/whatsnewsurvey123.htm](http://doc.arcgis.com/en/survey123/desktop/create-surveys/whatsnewsurvey123.htm)

We also announce new versions at the ArcGIS blog: [https://blogs.esri.com/esri/arcgis/2016/07/25/whats-new-in-survey123-for-arcgis-1-6/](https://blogs.esri.com/esri/arcgis/2016/07/25/whats-new-in-survey123-for-arcgis-1-6/)

and dive deeper into new functionality via blog posts in the [Survey123 GeoNet Community](
https://geonet.esri.com/groups/survey123/content?filterID=contentstatus[published]~objecttype~objecttype[blogpost]&start=0)
