### ISSUE TITLE
Calculations based on dates

### ISSUE THREAD

**Issue by kengorton** [Esri/Survey123Community#55]
According to http://survey123.esri.com/resources/XLSFormSupport/#calculation Survey123 will support calculations, but will that be limited to numeric calculations? Will date calculations be enabled, for example, to calculate current age from a date of birth?  

So far I am not able to do so and XLSForms.org only indicates mathematical functions. 
If this is or will be possible it will enable relevant conditions based on the age of the respondent.

**Comment by ctoledo-img-com-br** [comment]
+1

**Comment by bowlesgsrcx** [comment]
+1

**Comment by survey123** [comment]
@kengorton 
@ctoledo-img-com-br 
@bowlesgsrcx 

Calculations are supported with Dates. For example, if you want to calculate the age (in years) of a person, using the provided Birthdate, you could go with something like this:

int((today() - ${birthdate}) div (1000*60*60*24*365.25))

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)
