### ISSUE TITLE
Unable to access/download Feature Layer from form created with Survey123.

### ISSUE THREAD

**Issue by WeASeL-Antigua** [Esri/Survey123Community#551]
After creating the survey form using Survey123online (rather than the Desktop version), I see the Form listed under "My Content" on AGOL.

![Survey123 FORM](https://cloud.githubusercontent.com/assets/18103637/18189609/7d432640-708a-11e6-91cf-fbfe58b97924.png)

Because of how limited AGOL's Geoform apps are, I'd rather edit the AGOL Feature Layer's JSON with the JSON code of the survey created with Survey123 (making the necessary adjustments for it to work on AGOL of course).

How do I download the Feature layer created with Survey123?

**Comment by survey123** [comment]
Hi.  The easiest way to download your Survey123 Feature Layer data is to:
1) Go to survey123.arcgis.com. Login with the ArcGIS Online credentials you used to publish your Survey.
2) In the Survey Gallery, click on the Survey you want to download
3) Switch to the Data tab and use the Export Data function, located in the bottom-right corner

More  info here: https://geonet.esri.com/groups/survey123/blog/2015/11/10/downloading-data-captured-with-survey123-for-arcgis

**Comment by WeASeL-Antigua** [comment]
![image](https://cloud.githubusercontent.com/assets/18103637/18299913/b0c42198-7492-11e6-8a6d-7bbe51472178.png)

**Comment by zhif7782** [comment]
Hi @WeASeL-Antigua ,
Is that possible for you to share the original .xlsx which created this survey? We can try to reproduce the download issue by republishing and submit answers to the survey, if there's something wrong with the survey itself, we can reproduce by doing this.
