### ISSUE TITLE
'Relevant' field (that relies on a calculate) not appearing in survey in all platforms....

### ISSUE THREAD

**Issue by AlanaCorney** [Esri/Survey123Community#552]
Hey, 

Confusing issue, I have created a survey that has a 'relevant' question based on a calculate (if the previous 6 questions total '0' ask if this is correct).

This works perfectly in Survey123 Connect, Survey123 (desktop) and in Survey123 on my Ipad, but I cannot get the 'relevant' question to appear on my Iphone or Android phone.

I have attached the xls, and any help would be appreciated!
[Survey123Test.xlsx](https://github.com/Esri/Survey123Community/files/454178/Survey123Test.xlsx)

**Comment by tedrick** [comment]
Hi,

When I loaded your survey into Survey123Connect, it didn't display the relevant question when the previous entries were 0.  In looking at your formula:
> ${AdultMale}+${AdultFemale}+${JuvenileMale}+${JuvenileFemale}+${Larvae}+${Unknown} = '0'

You are comparing the results of a numeric calculation with text.  Removing the ' from around the 0:
`${AdultMale}+${AdultFemale}+${JuvenileMale}+${JuvenileFemale}+${Larvae}+${Unknown} = 0`
resulted in displaying the final question if the previous were either 0 or blank.
