### ISSUE TITLE
Print Current Response - Location Map scale/zoom

### ISSUE THREAD

**Issue by phil-wilson** [Esri/Survey123Community#553]
Hi there,

The new functionally from the Survey123 website to Print Current Response is fantastic, great work on this update. So good to be able to print individual survey responses to a PDF or out on paper now.

One thing however is the Location map is zoomed out too far (too small scale), therefore is somewhat useless in the report. See below example, in our case most assets are all in or around Melbourne, in this case we see the entire of Australia. Is there are way to set the default zoom/scale before printing, I had a play around but couldn't find anything.

![capture](https://cloud.githubusercontent.com/assets/19141448/18234954/8f00ff78-7356-11e6-82f8-6e8c8b2d6b1e.PNG)

Thanks,
Phil.

**Comment by phil-wilson** [comment]
Ok, with the help of ESRI Australia support, I now know that we can zoom in on the location map under the Individual Response formatted view, however the marker does not display in the PDF, but shows in the preview window, see below:

![capture_map](https://cloud.githubusercontent.com/assets/19141448/18235714/ae968faa-7361-11e6-9484-3a09096f13e0.PNG)

**Comment by tedrick** [comment]
Hi Phil, our development team has reached out to you as we're having trouble reproducing this issue.

**Comment by phil-wilson** [comment]
Thanks  @tedrick I have just replied.

**Comment by survey123** [comment]
Hi @phil-wilson , we've enhanced the individual response view in Data tab, now the map zoom level will respect the settings in Survey123 Connect's Settings->Map tab or the settings of a GeoPoint question in web designer, and you'll see the enhancement in our next 1.9 release.

Let's keep track the print issue in geonet: https://geonet.esri.com/thread/182511-print-current-response-location-map-scalezoom

**Comment by survey123** [comment]
Follow up from previous response - if you need to change the map scale in Connect (so that you can re-define the map extent in the print window) and re-publish, be sure to exit out of the survey (hit the back button and go back to the gallery) and come back to the survey before re-publishing. in short - you need to be sure your changes are saved before re-publishing.
