### ISSUE TITLE
Basemaps not displaying in Survey123

### ISSUE THREAD

**Issue by jplunkett1** [Esri/Survey123Community#555]
Non WGS84 Basemaps  show blank display 
Steps to replicate
Create a Survey in Webconnect
Add A Geopoint
Click Edit
Select a non WGS84Basemap
(http://services.arcgisonline.co.nz/arcgis/rest/services/Canvas/Light/MapServer)
It displays in the Edit window

Click Publish 
the Geopoint is blank and no map displays

If you chose a WGS84 Map it displays correctly

**Comment by survey123** [comment]
Hi. This is by design. The Survey123 mobile app only supports basemaps in Web Mercator Auxiliary Sphere.

**Comment by jplunkett1** [comment]
Thanks for getting back to me.
I just need to clarify - if users are using the Survey123 on the Web browser is there support for other coordinate systems?

Is there a plan to allow users to use other coordinate systems?

Thanks
John P

**Comment by survey123** [comment]
Hi. We will keep  simple for now, not supporting any other projection.
