### ISSUE TITLE
Code 400 Invalid URL on survey submission

### ISSUE THREAD

**Issue by benwstrauss** [Esri/Survey123Community#558]
I have a survey that has been published and in use for several months. It uses cascading selects from an external choices sheet, published via Surevey123 Connect.

In the past few days I get a Code 400 Invalid URL error trying to submit surveys. When I edit the surveys that did not submit successfully, I can see that the cascading select "stops" at a certain question, which makes me think there is something going on there causing a malformed URL. See in the image, the Inspect What? question is not expanded at all, even those values were selected for that question and the questions after it. Selecting a new choice that would normally expand it does nothing. This only happens on editing a failed survey, not in filling out an initial survey.

I have several hundred surveys submitted with no changes, so I'm not sure what cause this suddenly.

![2016-09-12 16 42 42](https://cloud.githubusercontent.com/assets/17086183/18452308/5846f944-7908-11e6-9441-c77dd3f69753.png)

**Comment by tedrick** [comment]
Is this survey connected to a service in ArcGIS Online or an ArcGIS for Server?  Code 400 would indicate a change in the server or some aspect between the server and the device (like a firewall).

James
