### ISSUE TITLE
Survey123 should support Portal for ArcGIS

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#56]
Many organizations have sensitive data and would prefer to use the feature services hosted in their own environment. So support Portal for ArcGIS is needed.

**Comment by mhogeweg** [comment]
:+1:

**Comment by survey123** [comment]
Thanks. This is certainly something we want to support. We will connect with you when we have something you can test.

**Comment by survey123** [comment]
@mhogeweg   @deepti10  @dfabulic 
Support will be limited to 10.3.1 and will require configuring the Hosted Server of your Portal with the ArcGIS Data Store.  Please also note that at this moment we can only work with token based authentication. IWA, PKI and oAuth are not supported yet.  We are looking at supporting oAuth, but IWA and PKI will be a no go in the foreseeable future.

Closing this for now. Feel free to open more specific issues related to Portal support so we can focus next steps.

**Comment by Tmodurr** [comment]
@survey123 , is there any on-hand documentation on the currently supported authentication measures that are supported?

**Comment by tedrick** [comment]
@Tmodurr , we currently support the built-in authentication of ArcGIS Online / Portal and Enterprise (SAML) logins.  There's a known bug with web-adapter tier authentication on Portal (most frequently implemented as Windows Authentication).

**Comment by Tmodurr** [comment]
Thanks @tedrick, Do you have a bug# so I could track/review?

**Comment by tedrick** [comment]
It's listed as BUG-000100665 in our technical support system.
