### ISSUE TITLE
Random garbled text appearing

### ISSUE THREAD

**Issue by jplunkett1** [Esri/Survey123Community#566]
Hi there
Has issues similar like this been reported before?
I have  a customers reporting issues with the Survey 123 forms appearing with scrambled letters.  Screenshot attached. - The survey language is English and no special characters are used
    iPhone 5s
    iOS - Ver. 10.0.2
    Survey App - Ver 1.8 .21
They are publishing to a Portal 10.3.1
It appears to be isolated to one device and the scrambled text appearing is random. (unable to force a pattern to reproduce)
We have removed the App and re-downloaded it as well as remove the survey and re-download it

I have not been able to replicate this on my test instances

![img_1012](https://cloud.githubusercontent.com/assets/7854161/19364961/f2f991b6-91ec-11e6-9be0-621454eee8b1.PNG)
![img_1224](https://cloud.githubusercontent.com/assets/7854161/19364962/f3163b0e-91ec-11e6-8a5e-7b2c6861e438.png)
![img_1222](https://cloud.githubusercontent.com/assets/7854161/19364959/f2f077a2-91ec-11e6-8f50-894467d27918.png)
![img_1011](https://cloud.githubusercontent.com/assets/7854161/19364960/f2f99756-91ec-11e6-96ca-b8b2b5a3b4e7.png)

**Comment by survey123** [comment]
Sadly this is an issue that arose with the roll out of iOS 10. We are working with the Qt Company to fix this.

**Comment by jplunkett1** [comment]
Thanks for the prompt response - is there an official Esri Bug - would you recommend that I log a call with Esri Support?

Let me know what is the best course of action

Cheers 
John P

**Comment by survey123** [comment]
Yes please. It does not hurt to log  an official bug through Tech Support.

**Comment by jplunkett1** [comment]
Logged with Esri Support Case  01841209.

Thanks and have a good weekend
John P

**Comment by jplunkett1** [comment]
The bug reference number is [#BUG-000099726 : Survey123 mobile app displays jibberish text on iphone devies running iOS version 10.0.2].

**Comment by survey123** [comment]
@jplunkett1 - This is now fixed in 1.10
