### ISSUE TITLE
"Open in Survey123" option not working

### ISSUE THREAD

**Issue by albrown87** [Esri/Survey123Community#569]
When you try to launch or open a survey from the Web using the "Open in Survey123" option it does not work. It is the same concept when you go to a map and say "Open in ArcGIS Online," it will open a new tab with ArcGIS online, but when you click "Open in Survey123," it does nothing. I have tried different accounts, computers, and browsers and get the same results. 
![screen shot 2016-10-19 at 11 39 49 am](https://cloud.githubusercontent.com/assets/22941012/19528228/c856c570-95f0-11e6-82b6-a456e0dbf01a.png)

**Comment by tedrick** [comment]
Thanks for the suggestion- we've incorporated it into our issues list.

**Comment by survey123** [comment]
To be addressed in ArcGIS Online 4.4. Scheduled early December, 2016

**Comment by slibby** [comment]
Verified this works as expected in AGO (now).
