### ISSUE TITLE
Importing existing forms into Survey 123 Connect

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#57]
I had created survey forms using the Survey 123 application in App Studio and published them successfully. I just installed the new Survey 123 Connect and when trying to import the existing survey I get an error message. See attached screen captures.

**Comment by deepti10** [comment]
I am unable to attach screens I will email them to you with reference to this bug

**Comment by survey123** [comment]
Hi @deepti10 . Got your email with screenshots.
If you would like to attach screenshots simply save them as files in your computer, and then drag and drop them into your comment.
This is the same error other folks were getting #54 
It looks like this had to do with a temporary shutdown in our servers.  Please try again.   We just tested your form and it converted OK.

![untitled](https://cloud.githubusercontent.com/assets/10968332/6987776/e0c2961a-d9ff-11e4-9228-e5731da97788.png)

**Comment by sathyaprasad** [comment]
@deepti10 Here is a handy link https://help.github.com/articles/issue-attachments/

**Comment by deepti10** [comment]
Thanks. I was able to import the survey with no spaces in the name of the survey
