### ISSUE TITLE
Survey123 Connect won't connect to our 10.4.1 portal (w/ SAML configured)

### ISSUE THREAD

**Issue by jgustine** [Esri/Survey123Community#572]
We can successfully connect to our current portal (10.4.1/IWA) on our domain. We are working to migrate our portal/server, etc to a new domain in the same forest (10.4.1/SAML-ADFS). Everything is looking good (Portal/Federation/Datastore) but Survey123 connect doesn't like something: 
![image](https://cloud.githubusercontent.com/assets/9340794/19940688/265b45b2-a0f3-11e6-8414-b8528aa43d53.png)

Any special config for cross domain(same forest)/saml?

**Comment by tedrick** [comment]
The current Survey123 release does not fully support enterprise logins (i.e., ADFS), our next release will support it.

**Comment by jgustine** [comment]
Thanks @tedrick . When is the release expected?

**Comment by slibby** [comment]
@jgustine the latest release (1.9) should support Enterprise Logins properly: https://doc.arcgis.com/en/survey123/desktop/create-surveys/whatsnewsurvey123.htm

**Comment by jgustine** [comment]
So this is working great in our dev environment (not HA). But we are seeing the issue now in our new production environment (which is HA). 
![image](https://cloud.githubusercontent.com/assets/9340794/21459116/df10dd9c-c8f8-11e6-8f84-8314f9c7df55.png)

Here are our specs:

10.4.1 Portal (HA setup)
10.4.1 Server (Single cluster multiple machine) Federated 
10.4.1 Datastore (Primary and standby)
SAML/ADFS Auth

Any known issues connecting via SAML with and HA portal?

**Comment by jgustine** [comment]
s123 logs are telling me much when I try to connect

  },
  "homePageFeaturedContent": "",
  "homePageFeaturedContentCount": 12,
  "hostedServerHostedFolder": "Hosted",
  "httpPort": 80,
  "httpsPort": 443,
  "isPortal": true,
  "layerTemplatesGroupQuery": "title:\"Esri Layer Templates\" AND owner:esri_en",
  "livingAtlasGroupQuery": "title:\"Featured Maps And Apps\" AND owner:esri",
  "name": null,
  "portalHostname": "geo.southernute.com/arcgis",
  "portalMode": "singletenant",
  "portalName": "Portal for ArcGIS",
  "portalThumbnail": null,
  "rotatorPanels": [
    {
      "id": "banner-2",
      "innerHTML": "<img src='images/banner-2.jpg' style='-webkit-border-radius:0 0 10px 10px; -moz-border-radius:0 0 10px 10px; -o-border-radius:0 0 10px 10px; border-radius:0 0 10px 10px; margin-top:0; width:960px; height:180px;'/><div style='position:absolute; bottom:80px; left:80px; max-height:65px; width:660px; margin:0;'><span style='position:absolute; bottom:0; margin-bottom:0; line-height:normal; font-family:HelveticaNeue,Verdana; font-weight:600; font-size:32px; color:#369;'>Portal for ArcGIS</span></div>"
    }
  ],
  "samlEnabled": true,
  "showHomePageDescription": false,
  "staticImagesUrl": "/arcgis/portalimages",
  "stylesGroupQuery": "title:\"Esri Styles\" AND owner:esri_en",
  "supportsHostedServices": true,
  "supportsOAuth": true,
  "symbolSetsGroupQuery": "title:\"Esri Symbols\" AND owner:esri_en",
  "templatesGroupQuery": "title:\"Web Application Templates\" AND owner:esri_en",
  "thumbnail": null
}

**Comment by jgustine** [comment]
It does show it...https://geodev.southernute.com/arcgis/sharing/rest/portals/self
How do we enable this? We didn't do anything special in dev to set it up?

Thanks for the help!

**Comment by jgustine** [comment]
Also, should PortalMode by singletenant for and HA portal?

**Comment by slibby** [comment]
@jgustine `singletenant` is correct, for the `supportsSceneServices` I'd recommend opening a ticket with Esri technical support as it's a Portal/Server question beyond Survey123.

**Comment by jgustine** [comment]
This is fixed. Needed a valid wildcard certificate for the load balanced ArcGIS Server Admin URL installed in each machine in the server cluster. Thanks again.
