### ISSUE TITLE
Survey123 Connect does not work against ArcGIS Organizations setup as "https only"

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#58]
Configure your org as https only (first screenshot), then try to publish a new survey in Connect. You will get the error below (second screenshot)

![untitled](https://cloud.githubusercontent.com/assets/1273440/7056055/74ca4456-ddfd-11e4-8f2f-d61a4785e160.png)

![untitled2](https://cloud.githubusercontent.com/assets/1273440/7056074/a82c89d0-ddfd-11e4-9605-7d995dae1ed5.png)

**Comment by survey123** [comment]
Thanks for the feedback. This is now fixed in 1.0.65.
Closing.

**Comment by survey123** [comment]
Reopening issue. Broken as of version 118 of Connect.
See #131

**Comment by survey123** [comment]
Fixed in Survey123 Build 1.0.1.143
