### ISSUE TITLE
Related Table ParentGlobalID Error

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#582]
Testing a new survey that contains a repeat. The ParentGlobalID field in the relate table contains all zeroes instead of the actual ParentGlobalID (see attached jpg). I have attached the survey file as well.
Survey123 Connect 1.10.10, Portal 10.4, Pro 1.2

Thanks,
--gary
![tot_parentgid_error](https://cloud.githubusercontent.com/assets/14822701/20941647/1a76ed90-bbc5-11e6-9c68-eb120c53c715.JPG)
[Time_On_Tool.xlsx](https://github.com/Esri/Survey123Community/files/634908/Time_On_Tool.xlsx)

**Comment by bowlesgsrcx** [comment]
I updated my Survey123 app for Android to 1.10.19 and received the following error when trying to upload a new survey.
--gary
![screenshot_20161206-153440](https://cloud.githubusercontent.com/assets/14822701/20942572/e347c75e-bbc9-11e6-9af9-4021cdd679ce.png)

**Comment by spatialdude** [comment]
@bowlesgsrcx Current Connect changes all the names to lower case on publishing. This is probably what is casing the problem as the match is case sensitive and it appears they key field in your table is upper and lower case. We need to figure out what the best approach is to solve this.

cc @tedrick @IsmaelInRedlands

**Comment by survey123** [comment]
From 2.2 all survey question names will need to be made lowercase before you are able to publish. This means that the fields in the form and the underlying portal feature service will always match and you wont get the error above.
