### ISSUE TITLE
select_one_external in repeat holds on to value

### ISSUE THREAD

**Issue by slibby** [Esri/Survey123Community#585]
With a select_one_external question in a repeat as the final item in a cascading select (select A, Select B, Select C external), once the first entry is selected, the resulting final value is "stuck" in that field, even though other values can be seen. This appears to be a bug with the mobile UI, as it works about 95% correct on Windows Survey123.

Issue produced in Survey123 1.9.24 on iOS.

Sample form attached.
[Form 7.xlsx](https://github.com/Esri/Survey123Community/files/650881/Form.7.xlsx)

Steps to reproduce:

1. Open the form after publishing from the sample
2. Enter a GeoPoint and State in the parent form
3. Enter an Observed Location in the subform/repeat
4. Enter Class of Animal _Agnatha_ and Category of Animal _Lampreys_
5. Select _Alaskan Brook Lamprey_ from the Species List
6. enter "1" for number observed.
7. press "+" button to add new subform entry.
8. Note that "Alaskan Brook Lamprey" remains selected in the Species question and cannot be overwritten by any other value.

**Comment by tedrick** [comment]
@slibby .  I can confirm the visual experience you are noting in 1.9. I cannot replicate it in 1.10, which will be coming out soon. I also will note that even though the appearance is locked, the data submitted shows the new value if you select an alternate entry.

**Comment by slibby** [comment]
@tedrick glad to hear it, will test on 1.10 when it's out.

**Comment by slibby** [comment]
@tedrick can confirm that this is fixed and can be closed.
