### ISSUE TITLE
Inconsistent behavior of 'map to entry' behavior in the Results Panel map

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#6]
Steps to repro:
1) Author a Survey with a geopoint type question. 
2) Add two ore more entries from the Survey123 app making sure that the location of the entries is different (one in the US, one in Europe etc)
2) In the Survey123 Web Site, go to Results and click on the table. As you click on one entry, the map will center on that location
3) Click on a different entry. The map will zoom out and then zoom back into the same location as in 2

**Comment by survey123** [comment]
Got it. Will work on this.

**Comment by survey123** [comment]
Fixed. Thanks. Closing.
