### ISSUE TITLE
Survey123 Connect does not support Enterprise Logins in ArcGIS Online

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#60]
After configuring ArcGIS Online to use Enterprise Logins as described here: 

        http://doc.arcgis.com/en/arcgis-online/administer/enterprise-logins.htm

Survey123 Connect is unable to login to ArcGIS.

**Comment by knu2xs** [comment]
This definitely would prove beneficial as we are investigating using this with an enterprise implementation. However, SAML authentication is a must to facilitate Active Directory integration. Hence, without SAML, Survey123 is a no-go.

**Comment by survey123** [comment]
Closing issue. Implemented.
See: https://geonet.esri.com/groups/survey123/blog/2016/01/06/the-three-king-day-update-january-6-2016 

@knu2xs
