### ISSUE TITLE
Survey123 crashes on iPhone 4S

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#61]
Hi,

  I have an iPhone 4S with iOS 8.1.3 and Any Survey I try to open crashes the application with out any error message. I have downloaded the new Survey123 that was released yesterday night v1.0.83.

Thanks
Deepti

**Comment by survey123** [comment]
Thanks Deepti. I was able to repro your issues in iPhone 4S.
Will communicate with you privately.

**Comment by survey123** [comment]
We plan on having a fix to this in the May 1st update. The reason why your surveys are crashing is the size of the surveys.  Survey 123 app being optimized as we speak so we can handle very long surveys. Our goal is not to have a limit on the number of questions or complexity of the rules in the survey.
@deepti10

**Comment by survey123** [comment]
@deepti10 
We could not get this one done in our May release.
Looking at June release.

**Comment by survey123** [comment]
Finally done @deepti10 !
Working well with 1.2.49
Closing.
