### ISSUE TITLE
Read only fields

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#62]
When creating a form if any fields are marked as read only when publishing the form the read only form is not loaded into the feature service. If the field is then unmarked from readonly to regular the field is created propoerly in the Feature Service.

**Comment by survey123** [comment]
Thanks Deepti. @deepti10 
Working on this.

**Comment by survey123** [comment]
Hi. This behavior is expected:
-When you create Note type of questions or you flag questions as Read Only, then we never persist any data in the database. Both Notes and Read Only questions are meant to show information in the Survey to the end user.  

If you would like to add a new field to a feature service, please do so though ArcGIS tools.
Closing.

**Comment by survey123** [comment]
Reopening this issue. We are going to change the behavior so Read Only questions are read-only in your form, but the corresponding fields in the database are not flagged as read-only.  This allows calculated values in the read-only question to be persisted in the database AND also lets you edit the values in the back-end. Thanks Deepti for your feedback.
@deepti10

**Comment by survey123** [comment]
Fixed in Survey123 Build 1.0.1.143
