### ISSUE TITLE
Use autocomplete within a repeat

### ISSUE THREAD

**Issue by jvr123** [Esri/Survey123Community#621]
I have a long list of plant species that need to be selected within a repeat, so I set appearance to autocomplete.  The repeat does not function properly with this setting (species name is not cleared after hitting the plus button).  The repeat works fine if I set appearance to minimal.

**Comment by JohnHasthorpe** [comment]
Hi jvr123 - yes this is a known issue and we currently working on its resolution. You you have correctly identified the current workaround for the time being.

Thanks for bringing this up and we will keep you notified up any updates through GeoNet (https://geonet.esri.com/groups/survey123).
John

----------------------------
For internal reference: https://devtopia.esri.com/Melbourne/Survey123/issues/1562

**Comment by jvr123** [comment]
John:

Thanks so much for your response.  Is it correct that ESRI is also working on the problem of fields failing to clear when you are working in a nested repeat and use the plus button?

Jon

Jon Regosin, Ph.D.
Chief of Conservation Science
Natural Heritage & Endangered Species Program
Massachusetts Division of Fisheries & Wildlife
1 Rabbit Hill Road, Westborough, MA, 01581
p: (508) 389-6376 | c: (774) 364-2443
mass.gov/masswildlife<http://www.mass.gov/masswildlife> | facebook.com/masswildlife<http://www.facebook.com/masswildlife>​

**Comment by survey123** [comment]
Hi John

Yes that is correct – you can expect a fix in the next release of Survey123 (2.1)

Thanks
John

**Comment by survey123** [comment]
This is addressed in 2.2
