### ISSUE TITLE
autocomplete has stopped working

### ISSUE THREAD

**Issue by bart-richardson** [Esri/Survey123Community#629]
We use autocomplete for searching a long list of plant names. The function has stopped working in version 2.x forms, but it continued to work in 1.x forms.  This is not a repeat question, like the other autocomplete issue.  Just a single 'select_one' filtered choice.

**Comment by tedrick** [comment]
Hi,

We introduced a bug with autocompletes that have a choice_filter in 2.1.  We are working to correct that as quickly as possible.

**Comment by Tmodurr** [comment]
@tedrick any update on this?

**Comment by tedrick** [comment]
We are going through release certification (both internal and external) on the 2.2 version, which corrects this issue.  It is also available from the Esri Early Adopter Program as a public beta.

**Comment by survey123** [comment]
Addressed in 2.2
