### ISSUE TITLE
Support Public Surveys

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#63]
This is an enhancement request to support public surveys. A public survey is one that can be downloaded by anyone with the Survey123 app without the need for an ArcGIS account.   In this manner, Survey123 could be used for **Citizen Science** and **crowd-sourcing** initiatives. 

From a mechanical perspective, the idea is to simply share a survey with 'Everyone' and then share with volunteers in the field the unique identifier (friendly name) of the Survey to be downloaded.  Anyone without having to login should be able to download and contribute to the Survey.

**Comment by sirws** [comment]
Any ETA on this?

**Comment by survey123** [comment]
Hi, we are going to wait until we get social logins in place with ArcGIS Online before we work on this. In practice, we see this as a mid-2016 item.

**Comment by pbond-idfg** [comment]
+1

**Comment by survey123** [comment]
Public surveys were added in the November release of Survey123.
