### ISSUE TITLE
Choice Lists are not translated if using 'Minimal' Appearance

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#64]
As shown in the screenshot below, choice lists will display empty if the 'appearance' column is set as 'minimal' when using multiple language columns.

![untitled](https://cloud.githubusercontent.com/assets/1273440/7208924/e64cc8e0-e4f8-11e4-8086-3c39846e744b.png)

If the appearance is set to null (default), then the choices show OK.

![untitled2](https://cloud.githubusercontent.com/assets/1273440/7208980/41adb334-e4f9-11e4-8216-97bb7028620d.png)

The expectation is that translated choices will show regardless of the appearance selected.
I have uploaded a spreadsheet to repro the problem

https://esri.box.com/s/omlhwxnn7l7gwixg3yhgnx1glhv5m24g

**Comment by survey123** [comment]
Closing. Fixed in Survey123 version 144
