### ISSUE TITLE
Unfortunately, Survey123 has stopped.

### ISSUE THREAD

**Issue by lmbeki** [Esri/Survey123Community#641]
I have a QR code application as part of my survey. The application does work, however, when it fails to scan on the first attempt the error: Unfortunately, survey123 has stopped working occurs.
![image](https://user-images.githubusercontent.com/30829053/29067413-c5d0a658-7c32-11e7-9eed-c902b896fb58.png)
[QR Code.zip](https://github.com/Esri/Survey123Community/files/1208262/QR.Code.zip)

**Comment by tedrick** [comment]
Hi @lmbeki - there are barcode scanning improvements coming in the next version of Survey123; they're available for testing at the Early Adopter Community.
