### ISSUE TITLE
Survey123 App cannot submit if ArcGIS Organization is set as https-only

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#65]
The Survey123 App will show the error below if attempting to submit to an ArcGIS Organization setup to accept only https traffic.

![photo](https://cloud.githubusercontent.com/assets/1273440/7211083/47a8f916-e50c-11e4-82ea-d5b0bbefa1ee.JPG)

**Comment by HannahFerrier** [comment]
Just to confirm, was the survey created when the org was https only, or were the org settings changed between creating the survey and attempting to submit a record? 

Survey123 relies on a connection between the form and the underlying feature service. If you create the feature service with a http address, then Survey123 will always be looking for the http address, even if the org has changed to https.

Please try re-publishing the service and let me know how you go :)

- Hannah

**Comment by Cintruenigo** [comment]
Thanks @HannahFerrier 
I confirm that https works from the app and that the failure was caused by a change in the http to https setting in the org after the survey had been created.

Closing issue.
