### ISSUE TITLE
Unusable Select_Ones in Android (text is not legible, because it is too light)

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#66]
Select ones in Android are not usable. The text is too light. Tested on v83 of the Survey App

![photo2](https://cloud.githubusercontent.com/assets/1273440/7211130/aa568312-e50c-11e4-8341-e7e37375e461.png)

**Comment by survey123** [comment]
Thank you. We have seen this on other Android devices and it is a known issue.

**Comment by Cintruenigo** [comment]
This remains a problem with version 110.
Tested also with Android Nexus 9.

**Comment by jonpedder** [comment]
Same here, I've tested on HTC and Galaxy. It appears that the theme text is white therefore not showing. 

I'm looking to deploy 200 devices in Nepal for damage assessment in the next few days.

**Comment by survey123** [comment]
Thanks. We are hoping to have this fixed very shortly: Friday 8 or Monday 11.

**Comment by survey123** [comment]
Fix pushed to the app in [Google Play](https://play.google.com/store/apps/details?id=com.esri.survey123). Closing.
@jonpedder
