### ISSUE TITLE
Repeats not working

### ISSUE THREAD

**Issue by MarielaPNH** [Esri/Survey123Community#67]
The related table was created in the feature service, but when I am collecting and I add (+) the repeat, Survey create the second item in the form, but copy the data from the first and when update the data to the second item replace the first too. I send the update and the related table is empty.

**Comment by survey123** [comment]
Thanks a lot for your feedback. This is in our radar. 
Duplicate of #21

**Comment by survey123** [comment]
@MarielaPNH 

To better understand what aspects of the XLSForm spec are implemented at the moment in Survey123, please have a look at [this](http://survey123.esri.com/resources/XLSFormSupport/): http://survey123.esri.com/resources/XLSFormSupport/

**Comment by cdarti** [comment]
It would be really great to have the repeat implemented. We have quite a few workflows that require collecting data in many related tables and for which flattening the table for data collection does not work well.

**Comment by smgoldsmith** [comment]
Looking forward to the October release as mentioned by another the repeat element will dramatically change the data workflow. Have a couple of surveys that require this update asap. This addition will make Survey123 an excellent data collection tool.

**Comment by survey123** [comment]
Fixed on build 1.1.18 (Connect) and 1.1.4 (App). Closing.

**Comment by ingridmans** [comment]
I am also having this issue now.  Was this not resolved?

**Comment by JohnHasthorpe** [comment]
Hi ingridmans - can you confirm if you are using autocomplete?
There is a known bug affecting the autocomplete appearance is being applied within a repeat.

----------------------------------
For internal reference: https://devtopia.esri.com/Melbourne/Survey123/issues/1562

**Comment by ingridmans** [comment]
Yes, it was with the autocomplete setting.  I have since changed the field
appearance to 'minimal' and that fixed the problem, but it does slow down
our surveyors in having to scroll through the list.

**Comment by JohnHasthorpe** [comment]
We are working to get this issue resolved as soon as possible. Please keep an eye on Geonet for related announcements https://geonet.esri.com/groups/survey123
