### ISSUE TITLE
Capture location even if the map is not shown in the survey

### ISSUE THREAD

**Issue by santhanagopalakr** [Esri/Survey123Community#68]
It would be great if the location where the data is being collected gets logged by default. I would like to make this possible by either having an option to hide a geopoint question, or alternatively happen by default when a survey does not include any geopoint question.

The location should be defined when the survey is submitted, but when the survey is saved.  Having the map show in the survey can complicate things to users, they can make mistakes. I do not want them to have freedom to move the xy coordinates.  If at some point I want them to move the coordinates, then I would show them the map in the survey.

 Thanks!

 Ravi

**Comment by survey123** [comment]
Thanks for your feedback. This is now implemented in build 97 of the Survey App. Closing
