### ISSUE TITLE
Side Loading/downloading Tile Packages for offline

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#70]
It would be extremely helpful to plot  location with an aerial basemap offline. Additionally, the user should see previous submissions on the map. Tightly clustered points of interest can then be positioned accurately.
Thanks,
Davin

**Comment by survey123** [comment]
Thanks Davin. We plan to do this, we appreciate your feedback.

**Comment by mdayfcnsw** [comment]
+1 for the ability to consume tile packages (tpk) offline outside of mobile reception.

**Comment by survey123** [comment]
Closing this issue.
See more info here: https://geonet.esri.com/groups/survey123/blog/2016/01/06/prepare-basemaps-for-offline-use
