### ISSUE TITLE
Tell us your opinion: What is the oldest version of Android that Survey123 App should support?

### ISSUE THREAD

**Issue by survey123** [Esri/Survey123Community#74]
As of May 2015, the oldest version of Android that the Survey123 app supports is: 
* [Android 4.1 - Jelly Bean (API level 16)](http://en.wikipedia.org/wiki/Android_version_history#Android_4.1_Jelly_Bean_.28API_level_16.29)

Please add your comments if you feel we should support older versions.

**Comment by deepti10** [comment]
I have an ASUS tablet with Android version 4.1.1 and the survey123 applicaiton is not even opening on the device. A tablet with Android version 5.0 it opens.
