### ISSUE TITLE
Support OpenStreetmap Basemaps

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#77]
Requested to support Emergency Response in Nepal after the earthquake. 
The OSM basemap is being updated as we speak and would be awesome to have in Survey123 as reference.

**Comment by survey123** [comment]
Working on this. Planned for our May Day update.
![untitled](https://cloud.githubusercontent.com/assets/10968332/7413129/f725c82e-eefd-11e4-9875-8f73658973a7.png)

**Comment by survey123** [comment]
https://survey123forarcgis.wordpress.com/2015/05/05/openstreetmap-now-supported-in-survey123/ 
Closing.
