### ISSUE TITLE
If ain't 'relevant', don't make it 'required'

### ISSUE THREAD

**Issue by clareprice** [Esri/Survey123Community#78]
Workflow: During manhole inspections, fields in a component defect are required if a defect is present. However, if there is no defect, this section of the inspection is not displayed to the user. Because the field is still required, the user is unable to submit a survey.

Ability to have required fields similar to the relevant. If there is a defect, this field is required if there is no defect it is not required.

**Comment by survey123** [comment]
Thanks Clare. Another way to put this is: 'If a question is not relevant, do not make it required'.
This is a good catch. Will look into this.

**Comment by mmoreno-cart** [comment]
Hello, is there any update on this? Thanks!

**Comment by survey123** [comment]
@mmoreno-cart 
Still working on this. No update yet.

**Comment by mmoreno-cart** [comment]
Thank you! do you have any expected date for its implementation?

**Comment by AkothCarole** [comment]
Quick question, 
I'm trying to add relevant question based on previous relevant.without having to type multiple. is this possible?
Here's the series:
What animal is in the vicinity?
choices:
a: Leopard
b: Gazelle
c: Wildebeest
So Question 1b is only relevant if data collectors choose both Leopard and Gazelle   
For Instance: ${Animal_Sighted}= 'Leopard' and ${Animal_Sighted}='Thompson_Gazelle'

**Comment by survey123** [comment]
@AkothCarole When using a select_multiple field, the values are entered into the feature service as a comma separated list. For example, if you have selected 'Leopard' and 'Thompson_Gazelle' in the Animal_Sighted field, the data would look like this:

"Animal_Sighted" : "Leopard,Thompson_Gazelle"

Use the **Show Feature Object** in Survey123 Connect to see your feature.

This means your relevant expression would need to look like this:

${Animal_Sighted} = ("Leopard,Thompson_Gazelle")

This way, the next question will not be seen unless both Leopard and Gazelle have been selected.

Let me know if this helps :)

**Comment by AkothCarole** [comment]
@survey123 Yes it was very Helpful. Thank you. 
It worked using the expression
${Animal_Sighted} = ('Leopard,Thompson_Gazelle') used apostrophe instead of quotation marks
I also noticed its sequence-dependent. Won't work if say Thompson_Gazelle is selected before Leopard.

**Comment by mmoreno-cart** [comment]
@AkothCarole could this be of help?
selected(${Animal_Sighted},'Leopard') and selected(${Animal_Sighted},'Thompson_Gazelle')
not sequence-dependent
