### ISSUE TITLE
Don't persist (submit) any values from questions that are not relevant

### ISSUE THREAD

**Issue by clareprice** [Esri/Survey123Community#79]
Scenario: I'm in the field collecting data. I select my components, and begin to add data which are relevant to specific components. However, mistakenly (for whatever reason) I select a component in error and had begun to enter information. because the fields are relevant only to the selected component, when I unselect in the component question, any data entered persists. Any data entered is now stored in the feature service. 
![image](https://cloud.githubusercontent.com/assets/5611508/7383107/2255149a-edce-11e4-880e-1ccc7b0a7938.png)

Ideal world: when the selected component was updated, the data entered would be cleared.

**Comment by survey123** [comment]
Awesome feedback Clare. Good catch.
