### ISSUE TITLE
Survey Thumbnail is being cropped at the bottom in the Survey Gallery

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#8]
Compare the thumbnail of the Survey. It shows OK in Connect, but it is cropped at the bottom in the web site.
![untitled](https://cloud.githubusercontent.com/assets/1273440/6198577/5afe786a-b3c0-11e4-93a4-39081cfc8fd2.png)

**Comment by survey123** [comment]
Thanks for your feedback. This could very well be user error. Check to make sure that the image size is exactly 200x133px in size. The Survey Gallery and the Survey123 app are pretty strict and will crop larger images.

**Comment by Cintruenigo** [comment]
Indeed! Thanks!
