### ISSUE TITLE
Read only field view

### ISSUE THREAD

**Issue by clareprice** [Esri/Survey123Community#80]
A read only field appears the same as editable fields. The field should appear different to let the user know the field is read only (as with ArcGIS Online editing pop-ups)

**Comment by survey123** [comment]
Hi Clare.  We could treat **Notes** and **Read Only Questions** the same way. If we do that, will your issue be taken care of?

In other words, we can style Read Only questions like [Note type of questions](http://survey123.esri.com/resources/XLSFormSupport/#question%20types).

**Comment by clareprice** [comment]
For the workflows I have in mind, a read only field would still have an input, a default would be set in the survey, and the field would be "read only" in the survey. As a feature service, the field could still be edited. Utility example: collecting cable attachments on pole, if a cable attachment is illegal, the status (read only) field would be presented and populated with active. The field would be presented to the user but in a way that they would know they can't edit the field. The feature service would be part of additional maps and apps, which would include the ability for the status field to be updated as permits are submitted, work in progress, and ultimately the issue resolved.

**Comment by survey123** [comment]
OK. Will implement.
When you create a Read Only Text Question we will create the corresponding field in the feature service and populate it with whatever the form set for it.
