### ISSUE TITLE
Support overwrites and updates to Surveys

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#82]
Here are situations where been able to overwrite/update a Survey would be handy:

1) Authoring a survey turns to be a trial and error exercise. An option to override a survey would be handy even if that implies losing all data already collected.
2) Once a survey is in place, at some point one may have a need to add new questions, reword existing ones or may be update the choices in select_one and select_multiple questions. 

Ideal workflow:

1) I choose to publish a survey that already exists. If the survey that exists is not owned by me, then don't let me publish.
2) If the survey that exists is owned by me:
    * a) Give me an option to replace it completely (feature service and survey item). If I choose this option warn me that data will be lost (data already submitted as well as most likely data pending to be submitted)
    * b) Give me an option to replace only the survey. Warn me that survey and feature service may now be inconsistent. We need good doc on this: how far can I go updating my survey before I lose data?

Icing on the cake:

In 2a, give me an option to download the data in the feature service.

**Comment by jmirmelstein** [comment]
+1 - @Cintruenigo - similarly, each time we republish the survey we are given a new service URL.  It would be great if we could define a fixed service name and allow overwrites like Ismael suggested.  

All of our scripts an internal references to the service are broken any time the service is updated as a result of an updated field.

**Comment by mhogeweg** [comment]
:+1:

**Comment by survey123** [comment]
The latest version of Survey123 allows you to replace the form definition for an existing project. For example, if you wanted to change the order of the questions, change the color of the form or add notes. When you attempt to re-publish a survey in Survey123 Connect, you will be presented with the following option:

![formpackage](https://cloud.githubusercontent.com/assets/10968332/7467234/4db3c488-f337-11e4-9bbf-470bd9e127ab.PNG)

We cannot change the underlying feature service once it has been created. If you want to add more questions or update coded value domain lists, you will still need to publish a new feature service.

**Comment by cconnolly91** [comment]
Is it still the case that we won't be able to change the underlying feature service once it has been created?

**Comment by survey123** [comment]
@cconnolly91   For now it is the case. We plan on looking at being smarter about this, but it is a problem for which we need some more time.

**Comment by survey123** [comment]
Planned for next update.

**Comment by survey123** [comment]
Thanks to all for your feedback
@mhogeweg  @cconnolly91  @jmirmelstein  

Check out the latest version of Connect (1.4.30) and the App (1.4.28). You will now be able to change lots of things without having your Feature Service replaced: the title, description, summary, thumbnail, image size threshold, style, map properties as well as any label, grouping, media, calculations, constraints, defaults etc Only your changes to the survey require a feature service schema change, we will replace the feature service. 

Connect download available at: http://doc.arcgis.com/en/survey123/download/
