### ISSUE TITLE
Survery123 not opening on a Android tablet

### ISSUE THREAD

**Issue by deepti10** [Esri/Survey123Community#84]
I have an ASUS tablet with Android version 4.1.1 and the survey123 applicaiton is not even opening on the device. A tablet with Android version 5.0 it opens.

**Comment by sathyaprasad** [comment]
Can you let us know the exact version of the OS running on your ASUS tablet?

The minimum supported version of Android is Android 4.1 - Jelly Bean (API level 16). The app is now available on the Google play store and can you please try and install it from the store and let us know if the same problem persists? 

Note: If you are unable to install it from the play tore then your device is not supported.

**Comment by deepti10** [comment]
It is running Android version 4.1.1 Jelly Bean
