### ISSUE TITLE
Creating xlsx from existing featureservice

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#85]
It would be extremely timesaving to build a survey template populated from fields, domains, relationship classes, feature types, symbology, and other details from a service definition. Instead of service definitions, perhaps the user could provide an item Id for a feature layer item. Appearance could then be preset based on popup formatting.
I believe the learning curve for new users would decrease if they start with more familiar content.
Is this on the short term road map? 
Thanks,
Davin

**Comment by survey123** [comment]
Hi Davin. Totally agreed. 

What we are thinking is that in Connect you will be able to create a new Survey by importing from an existing Feature Layer URL. By doing so, we will create an XLS file containing your fields, aliases, types of questions as well as choices.  At that point you should be able to simply enhance your survey with validation and logic (relevants, defaults etc).
Finally, you will also be able to publish your XLS file as a new feature service or choose to use your existing feature service for your survey.

We are not sure when we will get this done, but it is in our roadmap. We will wait for more comments to this issue from other users. Thanks for your idea!

**Comment by knu2xs** [comment]
For more than one use case with clients right now, this would be huge. In fact, I already tried to force Survey123 to use an existing feature service. Form creation from an existing service, this combined with Single Sign On (SSO) will make this a huge tool for working with Enterprise clients.

**Comment by ramialouta** [comment]
Hi,

So lately i've been working with survey123 at WHO offices in geneva, and for us it would have been really easy if it was possible to connect an existing shared service to the form which will save us a lot of time and effort while creating the survey and once we need to update it. 
Therefore, we are looking forward to see that feature in the new issue of the app.

Thanks.
Rami

**Comment by sirws** [comment]
+1

**Comment by travisbutcher** [comment]
+1 on this idea.  There will be many clients who will want/need to set this form logic up against existing data schemas they already have in house instead of new data only.

**Comment by ljaupi** [comment]
+1. This is a great idea. (How) would repeats work on this?

**Comment by ArianaToth** [comment]
+1

**Comment by scoxisda** [comment]
+1

**Comment by gjwiebe** [comment]
This would be very useful for us as well. Awesome idea!

**Comment by colgateg** [comment]
+1. This combined with data preload would give an awesome data entry method for existing feature layers. This would so helpful for asset inspections, preventative maintenance workorders, and informed responses to other surveys.

**Comment by travisbutcher** [comment]
If anyone is interested in testing this I have created a python script to handle this workflow:
http://esriaiddev.maps.arcgis.com/home/item.html?id=e8ee34317a0a446c8e9f86edba00f53f

**Comment by shaunrconway** [comment]
++++++1

**Comment by slibby** [comment]
This functionality has been implemented in the latest version of Survey123 Connect. @tedrick I think this can be closed.

**Comment by survey123** [comment]
Yes, this has been added in Survey123 1.10.  Please refer to http://doc.arcgis.com/en/survey123/desktop/create-surveys/survey123witharcgisserver.htm
