### ISSUE TITLE
Submit Cancel Buttons

### ISSUE THREAD

**Issue by clareprice** [Esri/Survey123Community#87]
With the most recent beta there are no longer submit/cancel survey buttons, or any way I can tell to submit or cancel a survey via the side panel
![wraptext](https://cloud.githubusercontent.com/assets/5611508/7505200/5b0d3186-f405-11e4-87f4-8282c51855ac.PNG)

**Comment by survey123** [comment]
You need to reinitialize your database. Please make sure that you have submitted all of your previous surveys (e.g., have none left on the device) before you start.

1. On the Gallery/ My Surveys page, select **Settings** from the menu on the top right
2. On the Settings page, select **Reinitialize Database** from the menu on the top right
3. Close Survey123

When you open Survey123 again, you should be able to collect and complete surveys as expected.

**Comment by clareprice** [comment]
Thanks, this is good info to know. Deleting the app from a device and reinstall also resolved this issue.

**Comment by survey123** [comment]
An uninstall/ reinstall will only work for iOS because it completely removes all of the app files, including the database. 

If you are using an Android device the database will remain even if you have uninstalled the app and you will need to follow the steps above.

**Comment by survey123** [comment]
Closing. As of Survey123 app build 144, the 'send' and 'draft' buttons have been redesigned.
