### ISSUE TITLE
iPhone user experience - done/cancel

### ISSUE THREAD

**Issue by clareprice** [Esri/Survey123Community#89]
Typically when selecting from a drop down on an iOS device, the "done" is on the right hand side. Being a iOS user it is intuitive to hit right to submit, however using the Survey123 app, the submit and cancel are reversed.

**Comment by karmstro77** [comment]
Agree!!!
![image](https://cloud.githubusercontent.com/assets/6819070/7709916/3934f3cc-fe2e-11e4-81a5-86e8a8676f8c.png)

**Comment by survey123** [comment]
The user interface for select_one fields with a 'minimal' appearance has been updated in the latest version of Survey123. The app no longer uses this iOS-style list picker. There is no longer a 'done' and 'cancel' button on this control.
