### ISSUE TITLE
Cool to see Constraints implemented. Enhancement request.

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#9]
It is great to see 'constraints' supported!

Two quick notes:
* It would be nice if the 'constraint_message' would not be shown as a dialog, but rather by highlighting the wrong answer (in red for example as is typical in forms elsewhere) and showing the 'constraint_message' floating by the answer. A discrete transition when showing the panel would spice the UX a bit.
* I happened to click on details in the dialog and found out that the expression is not correct. See image below for details. -1 is actually < 0, not greater than.

![untitled](https://cloud.githubusercontent.com/assets/1273440/6198649/b1df007e-b3c4-11e4-8384-afea16078b46.png)

**Comment by survey123** [comment]
Fixed. Closing. Thanks.
