### ISSUE TITLE
multiple related layers for generated feature service?

### ISSUE THREAD

**Issue by DShokes** [Esri/Survey123Community#90]
Is it possible to set numerous layers when defining fields in the survey? Here is a simple use case: Stadium Inspections.
User sets name, location, and size of the stadium.
The user must also inspect bleacher sections for section label, quality, # of seats, and type of seat (and maybe centroid location) .
The number of related sections varies across stadiums. How can the section inspections be set as related features?

**Comment by survey123** [comment]
Hi Davin! It sounds like you may want to use [Repeats](http://survey123.esri.com/resources/XLSFormSupport/#repeats).  At the moment, we have not yet implemented repeats in Survey123, but they are in our road map.  You may want to add a +1 comment here to issue #21  or #67

**Comment by DShokes** [comment]
Repeat does indeed appear to be what is required for inspections, incident reports, etc. I didn't know how relationship classes were going to be handled and I had come up empty while keyword searching.
Thanks!

**Comment by DShokes** [comment]
I found this [map package](http://speedycreek.maps.arcgis.com/home/item.html?id=e52caff7763d40e48599f5abc2ac4e29) in an [Esri Blog Post](http://blogs.esri.com/esri/arcgis/2015/02/18/related-tables-exploring-new-ways-to-use-collector-for-arcgis/). Perhaps the gdb in the package could be used for the sample once repeats are implemented? It would highlight a large number of XLSform capabilities.

**Comment by survey123** [comment]
Good news! Repeats are now supported in the latest version of Survey123! 

See here for more details;
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update
