### ISSUE TITLE
Select Ones with Minimal Appearance do not show any values

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#92]
Reproduced on Windows and iOS. If using default appearance (empty) values show OK. If using minimal appearance values are not shown.

![untitled4](https://cloud.githubusercontent.com/assets/1273440/7549080/7a3db778-f5dc-11e4-8871-99411d365ce9.png)

Related to #64   (Sample XLSForm to repro provided)

**Comment by survey123** [comment]
Could you please clarify - is the drop-down list that is empty? Does the list not display your choice after it has been selected? Or is the control empty from the beginning?

**Comment by Cintruenigo** [comment]
The list displays empty when using the appearance. No default choice, no items shown when the dropdown is opened.

**Comment by survey123** [comment]
I am only able to reproduce this issue when the select_one field has labels in multiple languages. I believe this is a duplicate of #64 and will update the title of that issue to refer to multiple languages.

**Comment by Cintruenigo** [comment]
That is correct. A duplicate. Closing this one.
