### ISSUE TITLE
New Sample Form available

### ISSUE THREAD

**Issue by survey123** [Esri/Survey123Community#94]
There is a new Sample Form available for download now!

This form demonstrates the supported features in Survey123. Please use this as a resource when designing your own forms.

You can download the Sample Form package from the Survey123 Community Home Page (https://github.com/Esri/Survey123Community).

Please let us know if there are any other samples that you think would be useful for the Survey123 Community.

**Comment by Cintruenigo** [comment]
This is very useful. Thanks a lot.
The **Types** worksheet has more than just question types. I suggest this worksheet is named 'Help' or 'XLS Forms tips'.  In that worksheet it would be natural to have a link to http://survey123.esri.com/resources/XLSFormSupport/   and most importantly examples of expressions to use in formulas and calculations.
